services:
  postgres:
    restart: unless-stopped
    build:
      context: dist/images
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: "exonex"
      POSTGRES_PASSWORD: "exonex"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "cortex-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "rustfs-data:/data"
volumes:
  rustfs-data:
  cortex-data: