version: '3'

tasks:
  gen-proto:
    cmds:
      - rm -rf ./pkg/api
      - go tool buf dep update
      - go tool buf generate
      - git add .
  add-cortex-migration:
    cmds:
      - GOOSE_MIGRATION_DIR="./database/cortex/migrations" go tool goose create {{.CLI_ARGS}}