version: '3'

tasks:
  gen-proto:
    cmds:
      - rm -rf ./pkg/api
      - go tool buf dep update
      - go tool buf generate
      - git add .
  add-cortex-migration:
    cmds:
      - go tool goose create {{.CLI_ARGS}}
    env:
      GOOSE_MIGRATION_DIR: "./database/cortex/migrations"
  migrate-cortex-up:
    cmds:
      - go tool goose up
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://cortex:cortex@localhost:5432/cortex"
      GOOSE_MIGRATION_DIR: "./database/cortex/migrations"