version: '3'

tasks:
  grpcui:
    cmds:
      - grpcui -plaintext -port 1337 localhost:8080
  # =========================================================================================
  gen:
    cmds:
      - task: proto:gen
      - task: db:gen
      - task: format:sql
  # =========================================================================================
  proto:gen:
    cmds:
      - rm -rf ./pkg/api
      - go tool buf dep update
      - go tool buf generate
      - git add .
  # =========================================================================================
  db:migration:create:
    cmds:
      - go tool goose create {{.CLI_ARGS}}
    env:
      GOOSE_MIGRATION_DIR: "./database/migrations"
  # =========================================================================================
  db:up:
    cmds:
      - go tool goose up
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://exonex:exonex@localhost:5432/exonex"
      GOOSE_MIGRATION_DIR: "./database/migrations"
  db:down:
    cmds:
      - go tool goose reset
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://exonex:exonex@localhost:5432/exonex"
      GOOSE_MIGRATION_DIR: "./database/migrations"
  # =========================================================================================
  db:reset:
    cmds:
      - go tool goose reset
      - go tool goose up
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://exonex:exonex@localhost:5432/exonex"
      GOOSE_MIGRATION_DIR: "./database/migrations"
  # =========================================================================================
  db:gen:
    cmds:
      - rm -rf ./internal/dbschema
      - go tool jet -dsn=postgres://exonex:exonex@localhost:5432/exonex?sslmode=disable -schema=cortex -path=internal/dbschema
      - git add .
  # =========================================================================================
  format:sql:
    desc: "Executes pg_format on all .sql files in the project."
    cmds:
      - find . -name "*.sql" -not -path "*/node_modules/*" -exec pg_format -i -s 2 --keyword-case 2 --type-case 2 --function-case 2 --spaces 2 --nogrouping --keep-newline {} +
    silent: true
  # =========================================================================================
  format:sql:file:
    desc: "Executes pg_format on all .sql files in the project."
    cmds:
      - pg_format -i -s 2 --keyword-case 2 --type-case 2 --function-case 2 --spaces 2 --nogrouping --keep-newline {{.CLI_ARGS}}
    silent: true