//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/lib/pq"
	"time"
)

type ArtifactTypes struct {
	ID          string `sql:"primary_key"`
	Annotations string
	Finalizers  pq.StringArray
	APIGroup    string
	APIKind     string
	APIVersion  string
	Deprecated  bool
	Name        string
	Description string
	Schema      string
	CreatedAt   time.Time
	DeletedAt   *time.Time
}
