//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type Documents struct {
	ID              uuid.UUID `sql:"primary_key"`
	Annotations     string
	Finalizers      pq.StringArray
	UploadCompleted bool
	PublisherID     uuid.UUID
	MimeType        string
	SizeBytes       *int64
	StorageVolume   string
	StorageKey      string
	SourceURL       *string
	CreatedAt       time.Time
	DeletedAt       *time.Time
}
