//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Artifacts = newArtifactsTable("cortex", "artifacts", "")

type artifactsTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	Annotations  postgres.ColumnString
	Finalizers   postgres.ColumnStringArray
	ArtifactType postgres.ColumnString
	DocumentID   postgres.ColumnString
	Name         postgres.ColumnString
	Payload      postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	DeletedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ArtifactsTable struct {
	artifactsTable

	EXCLUDED artifactsTable
}

// AS creates new ArtifactsTable with assigned alias
func (a ArtifactsTable) AS(alias string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtifactsTable with assigned schema name
func (a ArtifactsTable) FromSchema(schemaName string) *ArtifactsTable {
	return newArtifactsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtifactsTable with assigned table prefix
func (a ArtifactsTable) WithPrefix(prefix string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtifactsTable with assigned table suffix
func (a ArtifactsTable) WithSuffix(suffix string) *ArtifactsTable {
	return newArtifactsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtifactsTable(schemaName, tableName, alias string) *ArtifactsTable {
	return &ArtifactsTable{
		artifactsTable: newArtifactsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newArtifactsTableImpl("", "excluded", ""),
	}
}

func newArtifactsTableImpl(schemaName, tableName, alias string) artifactsTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		AnnotationsColumn  = postgres.StringColumn("annotations")
		FinalizersColumn   = postgres.StringArrayColumn("finalizers")
		ArtifactTypeColumn = postgres.StringColumn("artifact_type")
		DocumentIDColumn   = postgres.StringColumn("document_id")
		NameColumn         = postgres.StringColumn("name")
		PayloadColumn      = postgres.StringColumn("payload")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		DeletedAtColumn    = postgres.TimestampzColumn("deleted_at")
		allColumns         = postgres.ColumnList{IDColumn, AnnotationsColumn, FinalizersColumn, ArtifactTypeColumn, DocumentIDColumn, NameColumn, PayloadColumn, CreatedAtColumn, DeletedAtColumn}
		mutableColumns     = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, ArtifactTypeColumn, DocumentIDColumn, NameColumn, PayloadColumn, DeletedAtColumn}
		defaultColumns     = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, NameColumn, CreatedAtColumn}
	)

	return artifactsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Annotations:  AnnotationsColumn,
		Finalizers:   FinalizersColumn,
		ArtifactType: ArtifactTypeColumn,
		DocumentID:   DocumentIDColumn,
		Name:         NameColumn,
		Payload:      PayloadColumn,
		CreatedAt:    CreatedAtColumn,
		DeletedAt:    DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
