//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Documents = newDocumentsTable("cortex", "documents", "")

type documentsTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	Annotations     postgres.ColumnString
	Finalizers      postgres.ColumnStringArray
	UploadCompleted postgres.ColumnBool
	PublisherID     postgres.ColumnString
	MimeType        postgres.ColumnString
	SizeBytes       postgres.ColumnInteger
	StorageVolume   postgres.ColumnString
	StorageKey      postgres.ColumnString
	SourceURL       postgres.ColumnString
	CreatedAt       postgres.ColumnTimestampz
	DeletedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DocumentsTable struct {
	documentsTable

	EXCLUDED documentsTable
}

// AS creates new DocumentsTable with assigned alias
func (a DocumentsTable) AS(alias string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DocumentsTable with assigned schema name
func (a DocumentsTable) FromSchema(schemaName string) *DocumentsTable {
	return newDocumentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DocumentsTable with assigned table prefix
func (a DocumentsTable) WithPrefix(prefix string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DocumentsTable with assigned table suffix
func (a DocumentsTable) WithSuffix(suffix string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDocumentsTable(schemaName, tableName, alias string) *DocumentsTable {
	return &DocumentsTable{
		documentsTable: newDocumentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newDocumentsTableImpl("", "excluded", ""),
	}
}

func newDocumentsTableImpl(schemaName, tableName, alias string) documentsTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		AnnotationsColumn     = postgres.StringColumn("annotations")
		FinalizersColumn      = postgres.StringArrayColumn("finalizers")
		UploadCompletedColumn = postgres.BoolColumn("upload_completed")
		PublisherIDColumn     = postgres.StringColumn("publisher_id")
		MimeTypeColumn        = postgres.StringColumn("mime_type")
		SizeBytesColumn       = postgres.IntegerColumn("size_bytes")
		StorageVolumeColumn   = postgres.StringColumn("storage_volume")
		StorageKeyColumn      = postgres.StringColumn("storage_key")
		SourceURLColumn       = postgres.StringColumn("source_url")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		DeletedAtColumn       = postgres.TimestampzColumn("deleted_at")
		allColumns            = postgres.ColumnList{IDColumn, AnnotationsColumn, FinalizersColumn, UploadCompletedColumn, PublisherIDColumn, MimeTypeColumn, SizeBytesColumn, StorageVolumeColumn, StorageKeyColumn, SourceURLColumn, CreatedAtColumn, DeletedAtColumn}
		mutableColumns        = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, UploadCompletedColumn, PublisherIDColumn, MimeTypeColumn, SizeBytesColumn, StorageVolumeColumn, StorageKeyColumn, SourceURLColumn, CreatedAtColumn, DeletedAtColumn}
		defaultColumns        = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, UploadCompletedColumn, CreatedAtColumn}
	)

	return documentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Annotations:     AnnotationsColumn,
		Finalizers:      FinalizersColumn,
		UploadCompleted: UploadCompletedColumn,
		PublisherID:     PublisherIDColumn,
		MimeType:        MimeTypeColumn,
		SizeBytes:       SizeBytesColumn,
		StorageVolume:   StorageVolumeColumn,
		StorageKey:      StorageKeyColumn,
		SourceURL:       SourceURLColumn,
		CreatedAt:       CreatedAtColumn,
		DeletedAt:       DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
