// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: exonex/cortex/v1alpha1/analysis.proto

package cortexv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalysisServiceName is the fully-qualified name of the AnalysisService service.
	AnalysisServiceName = "exonex.cortex.v1alpha1.AnalysisService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalysisServiceCreateAnalyzerProcedure is the fully-qualified name of the AnalysisService's
	// CreateAnalyzer RPC.
	AnalysisServiceCreateAnalyzerProcedure = "/exonex.cortex.v1alpha1.AnalysisService/CreateAnalyzer"
	// AnalysisServiceListAnalyzersProcedure is the fully-qualified name of the AnalysisService's
	// ListAnalyzers RPC.
	AnalysisServiceListAnalyzersProcedure = "/exonex.cortex.v1alpha1.AnalysisService/ListAnalyzers"
	// AnalysisServiceGetAnalyzerProcedure is the fully-qualified name of the AnalysisService's
	// GetAnalyzer RPC.
	AnalysisServiceGetAnalyzerProcedure = "/exonex.cortex.v1alpha1.AnalysisService/GetAnalyzer"
	// AnalysisServiceLeaseAnalyzerProcedure is the fully-qualified name of the AnalysisService's
	// LeaseAnalyzer RPC.
	AnalysisServiceLeaseAnalyzerProcedure = "/exonex.cortex.v1alpha1.AnalysisService/LeaseAnalyzer"
	// AnalysisServiceSendAnalyzerHeartbeatProcedure is the fully-qualified name of the
	// AnalysisService's SendAnalyzerHeartbeat RPC.
	AnalysisServiceSendAnalyzerHeartbeatProcedure = "/exonex.cortex.v1alpha1.AnalysisService/SendAnalyzerHeartbeat"
	// AnalysisServiceCreateAnalysisProcedure is the fully-qualified name of the AnalysisService's
	// CreateAnalysis RPC.
	AnalysisServiceCreateAnalysisProcedure = "/exonex.cortex.v1alpha1.AnalysisService/CreateAnalysis"
	// AnalysisServicePollAnalysesProcedure is the fully-qualified name of the AnalysisService's
	// PollAnalyses RPC.
	AnalysisServicePollAnalysesProcedure = "/exonex.cortex.v1alpha1.AnalysisService/PollAnalyses"
)

// AnalysisServiceClient is a client for the exonex.cortex.v1alpha1.AnalysisService service.
type AnalysisServiceClient interface {
	CreateAnalyzer(context.Context, *connect.Request[v1alpha1.CreateAnalyzerRequest]) (*connect.Response[v1alpha1.CreateAnalyzerResponse], error)
	ListAnalyzers(context.Context, *connect.Request[v1alpha1.ListAnalyzersRequest]) (*connect.Response[v1alpha1.ListAnalyzersResponse], error)
	GetAnalyzer(context.Context, *connect.Request[v1alpha1.GetAnalyzerRequest]) (*connect.Response[v1alpha1.GetAnalyzerResponse], error)
	LeaseAnalyzer(context.Context, *connect.Request[v1alpha1.LeaseAnalyzerRequest]) (*connect.Response[v1alpha1.LeaseAnalyzerResponse], error)
	SendAnalyzerHeartbeat(context.Context, *connect.Request[v1alpha1.SendAnalyzerHeartbeatRequest]) (*connect.Response[v1alpha1.SendAnalyzerHeartbeatResponse], error)
	CreateAnalysis(context.Context, *connect.Request[v1alpha1.CreateAnalysisRequest]) (*connect.Response[v1alpha1.CreateAnalysisResponse], error)
	PollAnalyses(context.Context, *connect.Request[v1alpha1.PollAnalysesRequest]) (*connect.Response[v1alpha1.PollAnalysesResponse], error)
}

// NewAnalysisServiceClient constructs a client for the exonex.cortex.v1alpha1.AnalysisService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalysisServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalysisServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analysisServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_analysis_proto.Services().ByName("AnalysisService").Methods()
	return &analysisServiceClient{
		createAnalyzer: connect.NewClient[v1alpha1.CreateAnalyzerRequest, v1alpha1.CreateAnalyzerResponse](
			httpClient,
			baseURL+AnalysisServiceCreateAnalyzerProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("CreateAnalyzer")),
			connect.WithClientOptions(opts...),
		),
		listAnalyzers: connect.NewClient[v1alpha1.ListAnalyzersRequest, v1alpha1.ListAnalyzersResponse](
			httpClient,
			baseURL+AnalysisServiceListAnalyzersProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("ListAnalyzers")),
			connect.WithClientOptions(opts...),
		),
		getAnalyzer: connect.NewClient[v1alpha1.GetAnalyzerRequest, v1alpha1.GetAnalyzerResponse](
			httpClient,
			baseURL+AnalysisServiceGetAnalyzerProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("GetAnalyzer")),
			connect.WithClientOptions(opts...),
		),
		leaseAnalyzer: connect.NewClient[v1alpha1.LeaseAnalyzerRequest, v1alpha1.LeaseAnalyzerResponse](
			httpClient,
			baseURL+AnalysisServiceLeaseAnalyzerProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("LeaseAnalyzer")),
			connect.WithClientOptions(opts...),
		),
		sendAnalyzerHeartbeat: connect.NewClient[v1alpha1.SendAnalyzerHeartbeatRequest, v1alpha1.SendAnalyzerHeartbeatResponse](
			httpClient,
			baseURL+AnalysisServiceSendAnalyzerHeartbeatProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("SendAnalyzerHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		createAnalysis: connect.NewClient[v1alpha1.CreateAnalysisRequest, v1alpha1.CreateAnalysisResponse](
			httpClient,
			baseURL+AnalysisServiceCreateAnalysisProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("CreateAnalysis")),
			connect.WithClientOptions(opts...),
		),
		pollAnalyses: connect.NewClient[v1alpha1.PollAnalysesRequest, v1alpha1.PollAnalysesResponse](
			httpClient,
			baseURL+AnalysisServicePollAnalysesProcedure,
			connect.WithSchema(analysisServiceMethods.ByName("PollAnalyses")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analysisServiceClient implements AnalysisServiceClient.
type analysisServiceClient struct {
	createAnalyzer        *connect.Client[v1alpha1.CreateAnalyzerRequest, v1alpha1.CreateAnalyzerResponse]
	listAnalyzers         *connect.Client[v1alpha1.ListAnalyzersRequest, v1alpha1.ListAnalyzersResponse]
	getAnalyzer           *connect.Client[v1alpha1.GetAnalyzerRequest, v1alpha1.GetAnalyzerResponse]
	leaseAnalyzer         *connect.Client[v1alpha1.LeaseAnalyzerRequest, v1alpha1.LeaseAnalyzerResponse]
	sendAnalyzerHeartbeat *connect.Client[v1alpha1.SendAnalyzerHeartbeatRequest, v1alpha1.SendAnalyzerHeartbeatResponse]
	createAnalysis        *connect.Client[v1alpha1.CreateAnalysisRequest, v1alpha1.CreateAnalysisResponse]
	pollAnalyses          *connect.Client[v1alpha1.PollAnalysesRequest, v1alpha1.PollAnalysesResponse]
}

// CreateAnalyzer calls exonex.cortex.v1alpha1.AnalysisService.CreateAnalyzer.
func (c *analysisServiceClient) CreateAnalyzer(ctx context.Context, req *connect.Request[v1alpha1.CreateAnalyzerRequest]) (*connect.Response[v1alpha1.CreateAnalyzerResponse], error) {
	return c.createAnalyzer.CallUnary(ctx, req)
}

// ListAnalyzers calls exonex.cortex.v1alpha1.AnalysisService.ListAnalyzers.
func (c *analysisServiceClient) ListAnalyzers(ctx context.Context, req *connect.Request[v1alpha1.ListAnalyzersRequest]) (*connect.Response[v1alpha1.ListAnalyzersResponse], error) {
	return c.listAnalyzers.CallUnary(ctx, req)
}

// GetAnalyzer calls exonex.cortex.v1alpha1.AnalysisService.GetAnalyzer.
func (c *analysisServiceClient) GetAnalyzer(ctx context.Context, req *connect.Request[v1alpha1.GetAnalyzerRequest]) (*connect.Response[v1alpha1.GetAnalyzerResponse], error) {
	return c.getAnalyzer.CallUnary(ctx, req)
}

// LeaseAnalyzer calls exonex.cortex.v1alpha1.AnalysisService.LeaseAnalyzer.
func (c *analysisServiceClient) LeaseAnalyzer(ctx context.Context, req *connect.Request[v1alpha1.LeaseAnalyzerRequest]) (*connect.Response[v1alpha1.LeaseAnalyzerResponse], error) {
	return c.leaseAnalyzer.CallUnary(ctx, req)
}

// SendAnalyzerHeartbeat calls exonex.cortex.v1alpha1.AnalysisService.SendAnalyzerHeartbeat.
func (c *analysisServiceClient) SendAnalyzerHeartbeat(ctx context.Context, req *connect.Request[v1alpha1.SendAnalyzerHeartbeatRequest]) (*connect.Response[v1alpha1.SendAnalyzerHeartbeatResponse], error) {
	return c.sendAnalyzerHeartbeat.CallUnary(ctx, req)
}

// CreateAnalysis calls exonex.cortex.v1alpha1.AnalysisService.CreateAnalysis.
func (c *analysisServiceClient) CreateAnalysis(ctx context.Context, req *connect.Request[v1alpha1.CreateAnalysisRequest]) (*connect.Response[v1alpha1.CreateAnalysisResponse], error) {
	return c.createAnalysis.CallUnary(ctx, req)
}

// PollAnalyses calls exonex.cortex.v1alpha1.AnalysisService.PollAnalyses.
func (c *analysisServiceClient) PollAnalyses(ctx context.Context, req *connect.Request[v1alpha1.PollAnalysesRequest]) (*connect.Response[v1alpha1.PollAnalysesResponse], error) {
	return c.pollAnalyses.CallUnary(ctx, req)
}

// AnalysisServiceHandler is an implementation of the exonex.cortex.v1alpha1.AnalysisService
// service.
type AnalysisServiceHandler interface {
	CreateAnalyzer(context.Context, *connect.Request[v1alpha1.CreateAnalyzerRequest]) (*connect.Response[v1alpha1.CreateAnalyzerResponse], error)
	ListAnalyzers(context.Context, *connect.Request[v1alpha1.ListAnalyzersRequest]) (*connect.Response[v1alpha1.ListAnalyzersResponse], error)
	GetAnalyzer(context.Context, *connect.Request[v1alpha1.GetAnalyzerRequest]) (*connect.Response[v1alpha1.GetAnalyzerResponse], error)
	LeaseAnalyzer(context.Context, *connect.Request[v1alpha1.LeaseAnalyzerRequest]) (*connect.Response[v1alpha1.LeaseAnalyzerResponse], error)
	SendAnalyzerHeartbeat(context.Context, *connect.Request[v1alpha1.SendAnalyzerHeartbeatRequest]) (*connect.Response[v1alpha1.SendAnalyzerHeartbeatResponse], error)
	CreateAnalysis(context.Context, *connect.Request[v1alpha1.CreateAnalysisRequest]) (*connect.Response[v1alpha1.CreateAnalysisResponse], error)
	PollAnalyses(context.Context, *connect.Request[v1alpha1.PollAnalysesRequest]) (*connect.Response[v1alpha1.PollAnalysesResponse], error)
}

// NewAnalysisServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalysisServiceHandler(svc AnalysisServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analysisServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_analysis_proto.Services().ByName("AnalysisService").Methods()
	analysisServiceCreateAnalyzerHandler := connect.NewUnaryHandler(
		AnalysisServiceCreateAnalyzerProcedure,
		svc.CreateAnalyzer,
		connect.WithSchema(analysisServiceMethods.ByName("CreateAnalyzer")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServiceListAnalyzersHandler := connect.NewUnaryHandler(
		AnalysisServiceListAnalyzersProcedure,
		svc.ListAnalyzers,
		connect.WithSchema(analysisServiceMethods.ByName("ListAnalyzers")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServiceGetAnalyzerHandler := connect.NewUnaryHandler(
		AnalysisServiceGetAnalyzerProcedure,
		svc.GetAnalyzer,
		connect.WithSchema(analysisServiceMethods.ByName("GetAnalyzer")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServiceLeaseAnalyzerHandler := connect.NewUnaryHandler(
		AnalysisServiceLeaseAnalyzerProcedure,
		svc.LeaseAnalyzer,
		connect.WithSchema(analysisServiceMethods.ByName("LeaseAnalyzer")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServiceSendAnalyzerHeartbeatHandler := connect.NewUnaryHandler(
		AnalysisServiceSendAnalyzerHeartbeatProcedure,
		svc.SendAnalyzerHeartbeat,
		connect.WithSchema(analysisServiceMethods.ByName("SendAnalyzerHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServiceCreateAnalysisHandler := connect.NewUnaryHandler(
		AnalysisServiceCreateAnalysisProcedure,
		svc.CreateAnalysis,
		connect.WithSchema(analysisServiceMethods.ByName("CreateAnalysis")),
		connect.WithHandlerOptions(opts...),
	)
	analysisServicePollAnalysesHandler := connect.NewUnaryHandler(
		AnalysisServicePollAnalysesProcedure,
		svc.PollAnalyses,
		connect.WithSchema(analysisServiceMethods.ByName("PollAnalyses")),
		connect.WithHandlerOptions(opts...),
	)
	return "/exonex.cortex.v1alpha1.AnalysisService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalysisServiceCreateAnalyzerProcedure:
			analysisServiceCreateAnalyzerHandler.ServeHTTP(w, r)
		case AnalysisServiceListAnalyzersProcedure:
			analysisServiceListAnalyzersHandler.ServeHTTP(w, r)
		case AnalysisServiceGetAnalyzerProcedure:
			analysisServiceGetAnalyzerHandler.ServeHTTP(w, r)
		case AnalysisServiceLeaseAnalyzerProcedure:
			analysisServiceLeaseAnalyzerHandler.ServeHTTP(w, r)
		case AnalysisServiceSendAnalyzerHeartbeatProcedure:
			analysisServiceSendAnalyzerHeartbeatHandler.ServeHTTP(w, r)
		case AnalysisServiceCreateAnalysisProcedure:
			analysisServiceCreateAnalysisHandler.ServeHTTP(w, r)
		case AnalysisServicePollAnalysesProcedure:
			analysisServicePollAnalysesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalysisServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalysisServiceHandler struct{}

func (UnimplementedAnalysisServiceHandler) CreateAnalyzer(context.Context, *connect.Request[v1alpha1.CreateAnalyzerRequest]) (*connect.Response[v1alpha1.CreateAnalyzerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.CreateAnalyzer is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) ListAnalyzers(context.Context, *connect.Request[v1alpha1.ListAnalyzersRequest]) (*connect.Response[v1alpha1.ListAnalyzersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.ListAnalyzers is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) GetAnalyzer(context.Context, *connect.Request[v1alpha1.GetAnalyzerRequest]) (*connect.Response[v1alpha1.GetAnalyzerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.GetAnalyzer is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) LeaseAnalyzer(context.Context, *connect.Request[v1alpha1.LeaseAnalyzerRequest]) (*connect.Response[v1alpha1.LeaseAnalyzerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.LeaseAnalyzer is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) SendAnalyzerHeartbeat(context.Context, *connect.Request[v1alpha1.SendAnalyzerHeartbeatRequest]) (*connect.Response[v1alpha1.SendAnalyzerHeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.SendAnalyzerHeartbeat is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) CreateAnalysis(context.Context, *connect.Request[v1alpha1.CreateAnalysisRequest]) (*connect.Response[v1alpha1.CreateAnalysisResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.CreateAnalysis is not implemented"))
}

func (UnimplementedAnalysisServiceHandler) PollAnalyses(context.Context, *connect.Request[v1alpha1.PollAnalysesRequest]) (*connect.Response[v1alpha1.PollAnalysesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.AnalysisService.PollAnalyses is not implemented"))
}
