// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: exonex/cortex/v1alpha1/document.proto

package cortexv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DocumentServiceName is the fully-qualified name of the DocumentService service.
	DocumentServiceName = "exonex.cortex.v1alpha1.DocumentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DocumentServiceListDocumentsProcedure is the fully-qualified name of the DocumentService's
	// ListDocuments RPC.
	DocumentServiceListDocumentsProcedure = "/exonex.cortex.v1alpha1.DocumentService/ListDocuments"
	// DocumentServiceGetDocumentProcedure is the fully-qualified name of the DocumentService's
	// GetDocument RPC.
	DocumentServiceGetDocumentProcedure = "/exonex.cortex.v1alpha1.DocumentService/GetDocument"
	// DocumentServiceCreateDocumentProcedure is the fully-qualified name of the DocumentService's
	// CreateDocument RPC.
	DocumentServiceCreateDocumentProcedure = "/exonex.cortex.v1alpha1.DocumentService/CreateDocument"
	// DocumentServiceCreateDocumentUploadUrlProcedure is the fully-qualified name of the
	// DocumentService's CreateDocumentUploadUrl RPC.
	DocumentServiceCreateDocumentUploadUrlProcedure = "/exonex.cortex.v1alpha1.DocumentService/CreateDocumentUploadUrl"
	// DocumentServiceUpdateDocumentProcedure is the fully-qualified name of the DocumentService's
	// UpdateDocument RPC.
	DocumentServiceUpdateDocumentProcedure = "/exonex.cortex.v1alpha1.DocumentService/UpdateDocument"
)

// DocumentServiceClient is a client for the exonex.cortex.v1alpha1.DocumentService service.
type DocumentServiceClient interface {
	ListDocuments(context.Context, *connect.Request[v1alpha1.ListDocumentsRequest]) (*connect.Response[v1alpha1.ListDocumentsResponse], error)
	GetDocument(context.Context, *connect.Request[v1alpha1.GetDocumentRequest]) (*connect.Response[v1alpha1.GetDocumentResponse], error)
	CreateDocument(context.Context, *connect.Request[v1alpha1.CreateDocumentRequest]) (*connect.Response[v1alpha1.CreateDocumentResponse], error)
	CreateDocumentUploadUrl(context.Context, *connect.Request[v1alpha1.CreateDocumentUploadUrlRequest]) (*connect.Response[v1alpha1.CreateDocumentUploadUrlResponse], error)
	UpdateDocument(context.Context, *connect.Request[v1alpha1.UpdateDocumentRequest]) (*connect.Response[v1alpha1.UpdateDocumentResponse], error)
}

// NewDocumentServiceClient constructs a client for the exonex.cortex.v1alpha1.DocumentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDocumentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DocumentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	documentServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_document_proto.Services().ByName("DocumentService").Methods()
	return &documentServiceClient{
		listDocuments: connect.NewClient[v1alpha1.ListDocumentsRequest, v1alpha1.ListDocumentsResponse](
			httpClient,
			baseURL+DocumentServiceListDocumentsProcedure,
			connect.WithSchema(documentServiceMethods.ByName("ListDocuments")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getDocument: connect.NewClient[v1alpha1.GetDocumentRequest, v1alpha1.GetDocumentResponse](
			httpClient,
			baseURL+DocumentServiceGetDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("GetDocument")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createDocument: connect.NewClient[v1alpha1.CreateDocumentRequest, v1alpha1.CreateDocumentResponse](
			httpClient,
			baseURL+DocumentServiceCreateDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("CreateDocument")),
			connect.WithClientOptions(opts...),
		),
		createDocumentUploadUrl: connect.NewClient[v1alpha1.CreateDocumentUploadUrlRequest, v1alpha1.CreateDocumentUploadUrlResponse](
			httpClient,
			baseURL+DocumentServiceCreateDocumentUploadUrlProcedure,
			connect.WithSchema(documentServiceMethods.ByName("CreateDocumentUploadUrl")),
			connect.WithClientOptions(opts...),
		),
		updateDocument: connect.NewClient[v1alpha1.UpdateDocumentRequest, v1alpha1.UpdateDocumentResponse](
			httpClient,
			baseURL+DocumentServiceUpdateDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("UpdateDocument")),
			connect.WithClientOptions(opts...),
		),
	}
}

// documentServiceClient implements DocumentServiceClient.
type documentServiceClient struct {
	listDocuments           *connect.Client[v1alpha1.ListDocumentsRequest, v1alpha1.ListDocumentsResponse]
	getDocument             *connect.Client[v1alpha1.GetDocumentRequest, v1alpha1.GetDocumentResponse]
	createDocument          *connect.Client[v1alpha1.CreateDocumentRequest, v1alpha1.CreateDocumentResponse]
	createDocumentUploadUrl *connect.Client[v1alpha1.CreateDocumentUploadUrlRequest, v1alpha1.CreateDocumentUploadUrlResponse]
	updateDocument          *connect.Client[v1alpha1.UpdateDocumentRequest, v1alpha1.UpdateDocumentResponse]
}

// ListDocuments calls exonex.cortex.v1alpha1.DocumentService.ListDocuments.
func (c *documentServiceClient) ListDocuments(ctx context.Context, req *connect.Request[v1alpha1.ListDocumentsRequest]) (*connect.Response[v1alpha1.ListDocumentsResponse], error) {
	return c.listDocuments.CallUnary(ctx, req)
}

// GetDocument calls exonex.cortex.v1alpha1.DocumentService.GetDocument.
func (c *documentServiceClient) GetDocument(ctx context.Context, req *connect.Request[v1alpha1.GetDocumentRequest]) (*connect.Response[v1alpha1.GetDocumentResponse], error) {
	return c.getDocument.CallUnary(ctx, req)
}

// CreateDocument calls exonex.cortex.v1alpha1.DocumentService.CreateDocument.
func (c *documentServiceClient) CreateDocument(ctx context.Context, req *connect.Request[v1alpha1.CreateDocumentRequest]) (*connect.Response[v1alpha1.CreateDocumentResponse], error) {
	return c.createDocument.CallUnary(ctx, req)
}

// CreateDocumentUploadUrl calls exonex.cortex.v1alpha1.DocumentService.CreateDocumentUploadUrl.
func (c *documentServiceClient) CreateDocumentUploadUrl(ctx context.Context, req *connect.Request[v1alpha1.CreateDocumentUploadUrlRequest]) (*connect.Response[v1alpha1.CreateDocumentUploadUrlResponse], error) {
	return c.createDocumentUploadUrl.CallUnary(ctx, req)
}

// UpdateDocument calls exonex.cortex.v1alpha1.DocumentService.UpdateDocument.
func (c *documentServiceClient) UpdateDocument(ctx context.Context, req *connect.Request[v1alpha1.UpdateDocumentRequest]) (*connect.Response[v1alpha1.UpdateDocumentResponse], error) {
	return c.updateDocument.CallUnary(ctx, req)
}

// DocumentServiceHandler is an implementation of the exonex.cortex.v1alpha1.DocumentService
// service.
type DocumentServiceHandler interface {
	ListDocuments(context.Context, *connect.Request[v1alpha1.ListDocumentsRequest]) (*connect.Response[v1alpha1.ListDocumentsResponse], error)
	GetDocument(context.Context, *connect.Request[v1alpha1.GetDocumentRequest]) (*connect.Response[v1alpha1.GetDocumentResponse], error)
	CreateDocument(context.Context, *connect.Request[v1alpha1.CreateDocumentRequest]) (*connect.Response[v1alpha1.CreateDocumentResponse], error)
	CreateDocumentUploadUrl(context.Context, *connect.Request[v1alpha1.CreateDocumentUploadUrlRequest]) (*connect.Response[v1alpha1.CreateDocumentUploadUrlResponse], error)
	UpdateDocument(context.Context, *connect.Request[v1alpha1.UpdateDocumentRequest]) (*connect.Response[v1alpha1.UpdateDocumentResponse], error)
}

// NewDocumentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDocumentServiceHandler(svc DocumentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	documentServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_document_proto.Services().ByName("DocumentService").Methods()
	documentServiceListDocumentsHandler := connect.NewUnaryHandler(
		DocumentServiceListDocumentsProcedure,
		svc.ListDocuments,
		connect.WithSchema(documentServiceMethods.ByName("ListDocuments")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceGetDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceGetDocumentProcedure,
		svc.GetDocument,
		connect.WithSchema(documentServiceMethods.ByName("GetDocument")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceCreateDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceCreateDocumentProcedure,
		svc.CreateDocument,
		connect.WithSchema(documentServiceMethods.ByName("CreateDocument")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceCreateDocumentUploadUrlHandler := connect.NewUnaryHandler(
		DocumentServiceCreateDocumentUploadUrlProcedure,
		svc.CreateDocumentUploadUrl,
		connect.WithSchema(documentServiceMethods.ByName("CreateDocumentUploadUrl")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceUpdateDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceUpdateDocumentProcedure,
		svc.UpdateDocument,
		connect.WithSchema(documentServiceMethods.ByName("UpdateDocument")),
		connect.WithHandlerOptions(opts...),
	)
	return "/exonex.cortex.v1alpha1.DocumentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DocumentServiceListDocumentsProcedure:
			documentServiceListDocumentsHandler.ServeHTTP(w, r)
		case DocumentServiceGetDocumentProcedure:
			documentServiceGetDocumentHandler.ServeHTTP(w, r)
		case DocumentServiceCreateDocumentProcedure:
			documentServiceCreateDocumentHandler.ServeHTTP(w, r)
		case DocumentServiceCreateDocumentUploadUrlProcedure:
			documentServiceCreateDocumentUploadUrlHandler.ServeHTTP(w, r)
		case DocumentServiceUpdateDocumentProcedure:
			documentServiceUpdateDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDocumentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDocumentServiceHandler struct{}

func (UnimplementedDocumentServiceHandler) ListDocuments(context.Context, *connect.Request[v1alpha1.ListDocumentsRequest]) (*connect.Response[v1alpha1.ListDocumentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.DocumentService.ListDocuments is not implemented"))
}

func (UnimplementedDocumentServiceHandler) GetDocument(context.Context, *connect.Request[v1alpha1.GetDocumentRequest]) (*connect.Response[v1alpha1.GetDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.DocumentService.GetDocument is not implemented"))
}

func (UnimplementedDocumentServiceHandler) CreateDocument(context.Context, *connect.Request[v1alpha1.CreateDocumentRequest]) (*connect.Response[v1alpha1.CreateDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.DocumentService.CreateDocument is not implemented"))
}

func (UnimplementedDocumentServiceHandler) CreateDocumentUploadUrl(context.Context, *connect.Request[v1alpha1.CreateDocumentUploadUrlRequest]) (*connect.Response[v1alpha1.CreateDocumentUploadUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.DocumentService.CreateDocumentUploadUrl is not implemented"))
}

func (UnimplementedDocumentServiceHandler) UpdateDocument(context.Context, *connect.Request[v1alpha1.UpdateDocumentRequest]) (*connect.Response[v1alpha1.UpdateDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.DocumentService.UpdateDocument is not implemented"))
}
