// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: exonex/cortex/v1alpha1/publishers.proto

package cortexv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PublisherServiceName is the fully-qualified name of the PublisherService service.
	PublisherServiceName = "exonex.cortex.v1alpha1.PublisherService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PublisherServiceListPublishersProcedure is the fully-qualified name of the PublisherService's
	// ListPublishers RPC.
	PublisherServiceListPublishersProcedure = "/exonex.cortex.v1alpha1.PublisherService/ListPublishers"
	// PublisherServiceGetPublisherProcedure is the fully-qualified name of the PublisherService's
	// GetPublisher RPC.
	PublisherServiceGetPublisherProcedure = "/exonex.cortex.v1alpha1.PublisherService/GetPublisher"
	// PublisherServiceAddPublisherProcedure is the fully-qualified name of the PublisherService's
	// AddPublisher RPC.
	PublisherServiceAddPublisherProcedure = "/exonex.cortex.v1alpha1.PublisherService/AddPublisher"
	// PublisherServiceGetPublishersForProcessionProcedure is the fully-qualified name of the
	// PublisherService's GetPublishersForProcession RPC.
	PublisherServiceGetPublishersForProcessionProcedure = "/exonex.cortex.v1alpha1.PublisherService/GetPublishersForProcession"
	// PublisherServiceGetPublishersOfLeaserHolderProcedure is the fully-qualified name of the
	// PublisherService's GetPublishersOfLeaserHolder RPC.
	PublisherServiceGetPublishersOfLeaserHolderProcedure = "/exonex.cortex.v1alpha1.PublisherService/GetPublishersOfLeaserHolder"
)

// PublisherServiceClient is a client for the exonex.cortex.v1alpha1.PublisherService service.
type PublisherServiceClient interface {
	ListPublishers(context.Context, *connect.Request[v1alpha1.ListPublishersRequest]) (*connect.Response[v1alpha1.ListPublishersResponse], error)
	GetPublisher(context.Context, *connect.Request[v1alpha1.GetPublisherRequest]) (*connect.Response[v1alpha1.GetPublisherResponse], error)
	AddPublisher(context.Context, *connect.Request[v1alpha1.AddPublisherRequest]) (*connect.Response[v1alpha1.AddPublisherResponse], error)
	GetPublishersForProcession(context.Context, *connect.Request[v1alpha1.GetPublishersForProcessionRequest]) (*connect.Response[v1alpha1.GetPublishersForProcessionResponse], error)
	GetPublishersOfLeaserHolder(context.Context, *connect.Request[v1alpha1.GetPublishersOfLeaserHolderRequest]) (*connect.Response[v1alpha1.GetPublishersOfLeaserHolderResponse], error)
}

// NewPublisherServiceClient constructs a client for the exonex.cortex.v1alpha1.PublisherService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPublisherServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PublisherServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	publisherServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_publishers_proto.Services().ByName("PublisherService").Methods()
	return &publisherServiceClient{
		listPublishers: connect.NewClient[v1alpha1.ListPublishersRequest, v1alpha1.ListPublishersResponse](
			httpClient,
			baseURL+PublisherServiceListPublishersProcedure,
			connect.WithSchema(publisherServiceMethods.ByName("ListPublishers")),
			connect.WithClientOptions(opts...),
		),
		getPublisher: connect.NewClient[v1alpha1.GetPublisherRequest, v1alpha1.GetPublisherResponse](
			httpClient,
			baseURL+PublisherServiceGetPublisherProcedure,
			connect.WithSchema(publisherServiceMethods.ByName("GetPublisher")),
			connect.WithClientOptions(opts...),
		),
		addPublisher: connect.NewClient[v1alpha1.AddPublisherRequest, v1alpha1.AddPublisherResponse](
			httpClient,
			baseURL+PublisherServiceAddPublisherProcedure,
			connect.WithSchema(publisherServiceMethods.ByName("AddPublisher")),
			connect.WithClientOptions(opts...),
		),
		getPublishersForProcession: connect.NewClient[v1alpha1.GetPublishersForProcessionRequest, v1alpha1.GetPublishersForProcessionResponse](
			httpClient,
			baseURL+PublisherServiceGetPublishersForProcessionProcedure,
			connect.WithSchema(publisherServiceMethods.ByName("GetPublishersForProcession")),
			connect.WithClientOptions(opts...),
		),
		getPublishersOfLeaserHolder: connect.NewClient[v1alpha1.GetPublishersOfLeaserHolderRequest, v1alpha1.GetPublishersOfLeaserHolderResponse](
			httpClient,
			baseURL+PublisherServiceGetPublishersOfLeaserHolderProcedure,
			connect.WithSchema(publisherServiceMethods.ByName("GetPublishersOfLeaserHolder")),
			connect.WithClientOptions(opts...),
		),
	}
}

// publisherServiceClient implements PublisherServiceClient.
type publisherServiceClient struct {
	listPublishers              *connect.Client[v1alpha1.ListPublishersRequest, v1alpha1.ListPublishersResponse]
	getPublisher                *connect.Client[v1alpha1.GetPublisherRequest, v1alpha1.GetPublisherResponse]
	addPublisher                *connect.Client[v1alpha1.AddPublisherRequest, v1alpha1.AddPublisherResponse]
	getPublishersForProcession  *connect.Client[v1alpha1.GetPublishersForProcessionRequest, v1alpha1.GetPublishersForProcessionResponse]
	getPublishersOfLeaserHolder *connect.Client[v1alpha1.GetPublishersOfLeaserHolderRequest, v1alpha1.GetPublishersOfLeaserHolderResponse]
}

// ListPublishers calls exonex.cortex.v1alpha1.PublisherService.ListPublishers.
func (c *publisherServiceClient) ListPublishers(ctx context.Context, req *connect.Request[v1alpha1.ListPublishersRequest]) (*connect.Response[v1alpha1.ListPublishersResponse], error) {
	return c.listPublishers.CallUnary(ctx, req)
}

// GetPublisher calls exonex.cortex.v1alpha1.PublisherService.GetPublisher.
func (c *publisherServiceClient) GetPublisher(ctx context.Context, req *connect.Request[v1alpha1.GetPublisherRequest]) (*connect.Response[v1alpha1.GetPublisherResponse], error) {
	return c.getPublisher.CallUnary(ctx, req)
}

// AddPublisher calls exonex.cortex.v1alpha1.PublisherService.AddPublisher.
func (c *publisherServiceClient) AddPublisher(ctx context.Context, req *connect.Request[v1alpha1.AddPublisherRequest]) (*connect.Response[v1alpha1.AddPublisherResponse], error) {
	return c.addPublisher.CallUnary(ctx, req)
}

// GetPublishersForProcession calls
// exonex.cortex.v1alpha1.PublisherService.GetPublishersForProcession.
func (c *publisherServiceClient) GetPublishersForProcession(ctx context.Context, req *connect.Request[v1alpha1.GetPublishersForProcessionRequest]) (*connect.Response[v1alpha1.GetPublishersForProcessionResponse], error) {
	return c.getPublishersForProcession.CallUnary(ctx, req)
}

// GetPublishersOfLeaserHolder calls
// exonex.cortex.v1alpha1.PublisherService.GetPublishersOfLeaserHolder.
func (c *publisherServiceClient) GetPublishersOfLeaserHolder(ctx context.Context, req *connect.Request[v1alpha1.GetPublishersOfLeaserHolderRequest]) (*connect.Response[v1alpha1.GetPublishersOfLeaserHolderResponse], error) {
	return c.getPublishersOfLeaserHolder.CallUnary(ctx, req)
}

// PublisherServiceHandler is an implementation of the exonex.cortex.v1alpha1.PublisherService
// service.
type PublisherServiceHandler interface {
	ListPublishers(context.Context, *connect.Request[v1alpha1.ListPublishersRequest]) (*connect.Response[v1alpha1.ListPublishersResponse], error)
	GetPublisher(context.Context, *connect.Request[v1alpha1.GetPublisherRequest]) (*connect.Response[v1alpha1.GetPublisherResponse], error)
	AddPublisher(context.Context, *connect.Request[v1alpha1.AddPublisherRequest]) (*connect.Response[v1alpha1.AddPublisherResponse], error)
	GetPublishersForProcession(context.Context, *connect.Request[v1alpha1.GetPublishersForProcessionRequest]) (*connect.Response[v1alpha1.GetPublishersForProcessionResponse], error)
	GetPublishersOfLeaserHolder(context.Context, *connect.Request[v1alpha1.GetPublishersOfLeaserHolderRequest]) (*connect.Response[v1alpha1.GetPublishersOfLeaserHolderResponse], error)
}

// NewPublisherServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPublisherServiceHandler(svc PublisherServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	publisherServiceMethods := v1alpha1.File_exonex_cortex_v1alpha1_publishers_proto.Services().ByName("PublisherService").Methods()
	publisherServiceListPublishersHandler := connect.NewUnaryHandler(
		PublisherServiceListPublishersProcedure,
		svc.ListPublishers,
		connect.WithSchema(publisherServiceMethods.ByName("ListPublishers")),
		connect.WithHandlerOptions(opts...),
	)
	publisherServiceGetPublisherHandler := connect.NewUnaryHandler(
		PublisherServiceGetPublisherProcedure,
		svc.GetPublisher,
		connect.WithSchema(publisherServiceMethods.ByName("GetPublisher")),
		connect.WithHandlerOptions(opts...),
	)
	publisherServiceAddPublisherHandler := connect.NewUnaryHandler(
		PublisherServiceAddPublisherProcedure,
		svc.AddPublisher,
		connect.WithSchema(publisherServiceMethods.ByName("AddPublisher")),
		connect.WithHandlerOptions(opts...),
	)
	publisherServiceGetPublishersForProcessionHandler := connect.NewUnaryHandler(
		PublisherServiceGetPublishersForProcessionProcedure,
		svc.GetPublishersForProcession,
		connect.WithSchema(publisherServiceMethods.ByName("GetPublishersForProcession")),
		connect.WithHandlerOptions(opts...),
	)
	publisherServiceGetPublishersOfLeaserHolderHandler := connect.NewUnaryHandler(
		PublisherServiceGetPublishersOfLeaserHolderProcedure,
		svc.GetPublishersOfLeaserHolder,
		connect.WithSchema(publisherServiceMethods.ByName("GetPublishersOfLeaserHolder")),
		connect.WithHandlerOptions(opts...),
	)
	return "/exonex.cortex.v1alpha1.PublisherService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PublisherServiceListPublishersProcedure:
			publisherServiceListPublishersHandler.ServeHTTP(w, r)
		case PublisherServiceGetPublisherProcedure:
			publisherServiceGetPublisherHandler.ServeHTTP(w, r)
		case PublisherServiceAddPublisherProcedure:
			publisherServiceAddPublisherHandler.ServeHTTP(w, r)
		case PublisherServiceGetPublishersForProcessionProcedure:
			publisherServiceGetPublishersForProcessionHandler.ServeHTTP(w, r)
		case PublisherServiceGetPublishersOfLeaserHolderProcedure:
			publisherServiceGetPublishersOfLeaserHolderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPublisherServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPublisherServiceHandler struct{}

func (UnimplementedPublisherServiceHandler) ListPublishers(context.Context, *connect.Request[v1alpha1.ListPublishersRequest]) (*connect.Response[v1alpha1.ListPublishersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.PublisherService.ListPublishers is not implemented"))
}

func (UnimplementedPublisherServiceHandler) GetPublisher(context.Context, *connect.Request[v1alpha1.GetPublisherRequest]) (*connect.Response[v1alpha1.GetPublisherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.PublisherService.GetPublisher is not implemented"))
}

func (UnimplementedPublisherServiceHandler) AddPublisher(context.Context, *connect.Request[v1alpha1.AddPublisherRequest]) (*connect.Response[v1alpha1.AddPublisherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.PublisherService.AddPublisher is not implemented"))
}

func (UnimplementedPublisherServiceHandler) GetPublishersForProcession(context.Context, *connect.Request[v1alpha1.GetPublishersForProcessionRequest]) (*connect.Response[v1alpha1.GetPublishersForProcessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.PublisherService.GetPublishersForProcession is not implemented"))
}

func (UnimplementedPublisherServiceHandler) GetPublishersOfLeaserHolder(context.Context, *connect.Request[v1alpha1.GetPublishersOfLeaserHolderRequest]) (*connect.Response[v1alpha1.GetPublishersOfLeaserHolderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("exonex.cortex.v1alpha1.PublisherService.GetPublishersOfLeaserHolder is not implemented"))
}
