syntax = "proto3";

package cortex.v1alpha1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

// =====================================================================================================================

enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0;
  ORDER_STATUS_PLANNED = 1;
  ORDER_STATUS_SUCCEEDED = 2;
  ORDER_STATUS_FAILED = 3;
}

enum ScrapeTrigger {
  SCRAPE_TRIGGER_UNSPECIFIED = 0;
  SCRAPE_TRIGGER_FEED = 1;
  SCRAPE_TRIGGER_LEGAL = 2;
  SCRAPE_TRIGGER_CRAWL = 3;
  SCRAPE_TRIGGER_MANUAL = 4;
}

enum TdmStatus {
  TDM_STATUS_UNSPECIFIED = 0;
  TDM_STATUS_ALLOWED = 1;
  TDM_STATUS_OPT_OUT_DETECTED = 2;
}

enum ArtifactFormat {
  ARTIFACT_FORMAT_UNSPECIFIED = 0;
  ARTIFACT_FORMAT_HTML = 1;
  ARTIFACT_FORMAT_PDF = 2;
  ARTIFACT_FORMAT_IMAGE = 3;
  ARTIFACT_FORMAT_MARKDOWN = 4;
  ARTIFACT_FORMAT_CLEAN_MARKDOWN = 5;
}

enum ExecutionStatus {
  EXECUTION_STATUS_UNSPECIFIED = 0;
  EXECUTION_STATUS_IN_PROGRESS = 1;
  EXECUTION_STATUS_SUCCEEDED = 2;
  EXECUTION_STATUS_FAILED = 3;
}

enum FeedType {
  FEED_TYPE_UNSPECIFIED = 0;
  FEED_TYPE_LEGAL = 1; // legal feed entries will be added directly as target for a ScrapeOrder.
  FEED_TYPE_RSS = 2;
  FEED_TYPE_ATOM = 3;
  FEED_TYPE_SITEMAP = 4;
}

enum DocumentType {
  DOCUMENT_TYPE_UNSPECIFIED = 0;
  DOCUMENT_TYPE_LEGAL_NOTICE = 1;
  DOCUMENT_TYPE_ROBOTS_TXT = 2;
  DOCUMENT_TYPE_ARTICLE = 3;
  DOCUMENT_TYPE_SOCIAL = 4;
  DOCUMENT_TYPE_JOB_POSTING = 5;
}

// =====================================================================================================================

// A Publisher is a entity that is publishing content, e.g. a News Agency.
message Publisher {
  string id = 1;
  string name = 2;
  string description = 3;
  string web_url = 4;
  repeated Feed feeds = 5;
  TdmStatus tdm_status = 6;
  repeated TdmStatusHistory tdm_status_history = 7;
  optional string lease_holder = 8;
  optional google.protobuf.Timestamp lease_until = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
}

// A Feed is a URL that is used to create Scrape- or Crawl-Orders for a Publisher.
message Feed {
  FeedType feed_type = 1;
  string url = 2;
  optional int32 poll_interval_seconds = 3;
  optional google.protobuf.Timestamp last_polled_at = 4;
  optional google.protobuf.Timestamp last_polled_last_modified = 5;
  optional string last_polled_etag = 6;
}

// The TdmStatusHistory tracks the history of the TDM Status for a Publisher.
// A new history item is added when the Analysis of a Document produces a different TdmStatus then
// currently stored for the Publisher.
message TdmStatusHistory {
  string document_id = 1;
  TdmStatus tdm_status = 2;
  google.protobuf.Timestamp created_at = 3;
}

// =====================================================================================================================

// A CrawlOrder is a order to Crawl a Website to discover possible Documents that can then be scraped by a scrape order.
message CrawlOrder {
  string id = 1;
  string publisher_id = 2;
  string entrypoint_url = 3;
  optional string lease_holder = 4;
  optional google.protobuf.Timestamp lease_until = 5;
  optional CrawlOrderResult crawl_result = 6;
  google.protobuf.Timestamp created_at = 7;
}

// A result tracks metadata to a Crawl- or ScrapeOrder.
// It is typically present after the Order has been executed.
message CrawlOrderResult {
  // The status_reason field can be used to add additional context on why the CrawlOrderResult is in the
  // current OrderStatus.
  OrderStatus status = 1;
  optional string status_reason = 2;
  repeated string scrape_order_ids = 3;
  google.protobuf.Timestamp finished_at = 4;
}

// =====================================================================================================================

// A ScrapeOrder is a concrete order to scrape one web resource and save it as a Document.
message ScrapeOrder {
  string id = 1;
  string publisher_id = 2;
  string url = 3;
  ScrapeTrigger trigger = 4;
  optional string trigger_reference = 5;
  optional string lease_holder = 6;
  optional google.protobuf.Timestamp lease_until = 7;
  optional ScrapeOrderResult scrape_result = 8;
  google.protobuf.Timestamp created_at = 9;
}

// A ScrapeOrderResult tracks metadata to a ScrapeOrder.
// It is typically present after the Order has been executed.
message ScrapeOrderResult {
  OrderStatus status = 1;
  // The status_reason field can be used to add additional context on why the ScrapeOrderResult is in the
  // current OrderStatus.
  optional string status_reason = 2;
  string document_id = 3;
  google.protobuf.Timestamp finished_at = 4;
}

// =====================================================================================================================

// A Document is one discovered Document like a News Article.
message Document {
  string id = 1;
  string publisher_id = 2;
  // original_url is the URL that lead to the creation of this document.
  string original_url = 3;
  // scrape_order_id is a reference to the ScrapeOrder that produced this document.
  string scrape_order_id = 4;
  DocumentType document_type = 5;
  repeated DocumentArtifact artifacts = 6;
  repeated AnalysisExecution analysis_executions = 7;
  TdmStatus tdm_status = 8;
  optional google.protobuf.Timestamp published_at = 9;
  google.protobuf.Timestamp created_at = 10;
}

// An Artifact is a file that has been produced for a Document either from Scraping or from Analysis.
message DocumentArtifact {
  string id = 1;
  // The analysis_execution_id is an optional reference if this artifact has been produced not by a scrape job
  // but by a AnalysisExecution.
  optional string analysis_execution_id = 2;
  ArtifactFormat format = 3;
  string storage_url = 4;
  int64 size_bytes = 5;
  string mime_type = 6;
  google.protobuf.Timestamp created_at = 7;
}

// One specific Result of a Analysis that has been performed for a Document.
message DocumentAnalysis {
  optional DocumentSummaryResult primary_summary = 1;
  repeated DocumentSummaryResult summary_results = 2;
  optional EntityAnalysis primary_entity_analysis = 3;
  repeated EntityAnalysis entity_analyses = 4;
}

// AnalysisExecution is a specific Analysis that should or have been executed for a Document.
message AnalysisExecution {
  string id = 1;
  string executor_id = 2;
  ExecutionStatus execution_status = 3;
  // The status_reason field can be used to add additional context on why the AnalysisExecution is in the
  // current ExecutionStatus.
  optional string status_reason = 4;
  optional string lease_holder = 5;
  optional google.protobuf.Timestamp lease_until = 6;
  google.protobuf.Timestamp created_at = 7;
}

// =====================================================================================================================

// The DocumentSummaryResult contains basic data about an Document, like a title and short summary.
message DocumentSummaryResult {
  string analysis_execution_id = 1;
  string executor_id = 2;
  string title = 3;
  string short_summary = 4;
  string executive_summary = 5;
  repeated string key_takeaways = 6;
}

// =====================================================================================================================

// A single Entity that has been recognized as part of an Entity Analysis.
message RecognizedEntity {
  string name = 1;
  string category = 2;
  float relevance = 3;
}

// Contains important Entities that haven been extracted from the Document.
message EntityAnalysis {
  string analysis_execution_id = 1;
  string executor_id = 2;
  repeated RecognizedEntity entities = 3;
}
