syntax = "proto3";
package exonex.cortex.v1alpha1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

enum ListOrder {
  LIST_ORDER_UNSPECIFIED = 0;
  LIST_ORDER_OLDEST_FIRST = 1;
  LIST_ORDER_NEWEST_FIRST = 2;
}

enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0;
  ORDER_STATUS_PLANNED = 1;
  ORDER_STATUS_SUCCEEDED = 2;
  ORDER_STATUS_FAILED = 3;
  ORDER_STATUS_ABORTED = 4;
}

// ObjectMeta defines typical metadata that is available for most objects.
message ObjectMeta {
  map<string, string> annotations = 1;
  repeated string finalizers = 2;
  google.protobuf.Timestamp created_at = 3;
  repeated LogEvent log_events = 4;
  optional Lease lease = 5;
}

// A LogEvent contains a Log information about an Object.
message LogEvent {
  google.protobuf.Timestamp time = 1;
  string author = 2;
  string message = 3;
  optional google.protobuf.Timestamp retention_time = 4;
}

// A Lease is the signal that the Object is currently hold by another process for processing.
message Lease {
  string holder = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp renewed_at = 3;
  google.protobuf.Timestamp expires_at = 4;
}
