syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/cortex/v1alpha1/common.proto";
import "google/protobuf/timestamp.proto";

// =====================================================================================================================

enum CrawlOrderStatus {
  CRAWL_ORDER_STATUS_UNSPECIFIED = 0;
  CRAWL_ORDER_STATUS_PLANNED = 1;
  CRAWL_ORDER_STATUS_SUCCEEDED = 2;
  CRAWL_ORDER_STATUS_FAILED = 3;
  CRAWL_ORDER_STATUS_ABORTED = 4;
}

// A CrawlOrder is a order to Crawl a Website to discover possible Documents that can then be scraped by a scrape order.
message CrawlOrder {
  string id = 1;
  ObjectMeta meta = 2;
  string publisher_id = 3;
  string entrypoint_url = 4;
  optional Lease lease = 5;
  optional CrawlOrderResult crawl_result = 6;
  google.protobuf.Timestamp created_at = 7;
  repeated LogEvent events = 8;
}

// A result tracks metadata to a Crawl- or ScrapeOrder.
// It is typically present after the Order has been executed.
message CrawlOrderResult {
  // The status_reason field can be used to add additional context on why the CrawlOrderResult is in the
  // current OrderStatus.
  OrderStatus status = 1;
  optional string status_reason = 2;
  repeated string scrape_order_ids = 3;
  google.protobuf.Timestamp finished_at = 4;
}