syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/api/v1/meta.proto";
import "exonex/api/v1/annotations.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/field_mask.proto";
import "google/api/resource.proto";
import "google/api/field_behavior.proto";

// =====================================================================================================================

message Document {
  option (google.api.resource) = {
    type: "cortex.exonex.io/Document"
    pattern: "publishers/{publisher}/documents/{document}"
    singular: "document"
    plural: "documents"
  };
  // General metadata about the Resource.
  exonex.api.v1.ResourceMeta meta = 1;
  // The UUID that is used to uniquely identify a Document.
  string id = 2 [
    (google.api.field_behavior) = IDENTIFIER
  ];
  // Reference to the cortex.exonex.io/Publisher that published the file.
  // This field is immutable once set and can be used to evaluate policies, e.g. regarding procession.
  string publisher = 4 [
    (google.api.field_behavior) = IMMUTABLE,
    (google.api.resource_reference) = {
      type: "cortex.exonex.io/Publisher"
    }
  ];
  // Indicates if the upload of the file for this document has already been finished.
  bool file_upload_completed = 5 [
    (exonex.api.v1.field_update_permission) = "documents.update/file_upload_completed"
  ];
  // The MIME type of the uploaded file.
  // This field is immutable once set and will be used as restriction when generating Upload URLs.
  string file_mime_type = 6 [
    (google.api.field_behavior) = IMMUTABLE
  ];
  // The size of the uploaded file in bytes.
  // This field may be an estimate until the upload of the file is completed.
  int64 file_size_bytes = 7 [
    (exonex.api.v1.field_update_permission) = "documents.update/file_size_bytes"
  ];
  // Name of the volume that stores the file.
  string file_storage_volume = 8 [
    (google.api.field_behavior) = OUTPUT_ONLY
  ];
  // Key or path on the storage volume where the file of this document is stored.
  string file_storage_key = 9 [
    (google.api.field_behavior) = OUTPUT_ONLY
  ];
}

// =====================================================================================================================

service DocumentService {
  rpc ListDocuments(ListDocumentsRequest) returns (ListDocumentsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (exonex.api.v1.method_permission) = "documents.read";
  }
  rpc GetDocument(GetDocumentRequest) returns (GetDocumentResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (exonex.api.v1.method_permission) = "documents.read";
  }
  rpc CreateDocument(CreateDocumentRequest) returns (CreateDocumentResponse) {
    option (exonex.api.v1.method_permission) = "documents.create";
  }
  rpc CreateDocumentUploadUrl(CreateDocumentUploadUrlRequest) returns (CreateDocumentUploadUrlResponse) {
    option (exonex.api.v1.method_permission) = "documents.upload_url.create";
  }
  rpc UpdateDocument(UpdateDocumentRequest) returns (UpdateDocumentResponse) {
    option (exonex.api.v1.method_permission) = "documents.update";
  }
}

// =====================================================================================================================

message ListDocumentsRequest {
  optional int64 page_size = 1;
  optional string page_token = 2;
  optional string filter = 3;
  optional string order_by = 4;
  optional bool show_deleted = 5;
}

message ListDocumentsResponse {
  repeated Document documents = 1;
  optional string next_page_token = 2;
}

// =====================================================================================================================

message GetDocumentRequest {
  string id = 1;
}

message GetDocumentResponse {
  Document document = 1;
}

// =====================================================================================================================

message CreateDocumentRequest {
  optional google.protobuf.Struct annotations = 1;
  string publisher = 2 [
    (google.api.resource_reference) = {
      type: "cortex.exonex.io/Publisher"
    }
  ];
  string file_mime_type = 3;
  string file_extension = 4;
  int64 file_size_bytes = 5;
}

message CreateDocumentResponse {
  Document document = 1;
}

// =====================================================================================================================

message CreateDocumentUploadUrlRequest {
  string id = 1;
}

message CreateDocumentUploadUrlResponse {
  string upload_url = 1;
  google.protobuf.Timestamp expires_at = 2;
}

// =====================================================================================================================

message UpdateDocumentRequest {
  google.protobuf.FieldMask update_mask = 2;
}

message UpdateDocumentResponse {
  Document document = 1;
}

// =====================================================================================================================

message LeaseDocumentRequest {
  string id = 1;
  string lease_holder_identity = 2;
  google.protobuf.Duration lease_duration = 3;
}

message LeaseDocumentResponse {}

// =====================================================================================================================

message DeleteDocumentRequest {
  string id = 1;
}

message DeleteDocumentResponse {}

