syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/cortex/v1alpha1/common.proto";
import "google/protobuf/timestamp.proto";

// =====================================================================================================================

enum DocumentType {
  DOCUMENT_TYPE_UNSPECIFIED = 0;
  DOCUMENT_TYPE_LEGAL = 1;
  DOCUMENT_TYPE_ROBOTS_TXT = 2;
  DOCUMENT_TYPE_ARTICLE = 3;
  DOCUMENT_TYPE_SOCIAL = 4;
  DOCUMENT_TYPE_JOB_POSTING = 5;
}

enum ArtifactFormat {
  ARTIFACT_FORMAT_UNSPECIFIED = 0;
  ARTIFACT_FORMAT_HTML = 1;
  ARTIFACT_FORMAT_PDF = 2;
  ARTIFACT_FORMAT_IMAGE = 3;
  ARTIFACT_FORMAT_MARKDOWN = 4;
  ARTIFACT_FORMAT_CLEAN_MARKDOWN = 5;
}

enum DocumentTdmStatus {
  DOCUMENT_TDM_STATUS_UNSPECIFIED = 0;
  DOCUMENT_TDM_STATUS_ALLOWED = 1;
  DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED = 2;
}

// A Document is one discovered Document like a News Article.
message Document {
  string id = 1;
  ObjectMeta meta = 2;
  string publisher_id = 3;
  // original_url is the URL that lead to the creation of this document.
  string original_url = 4;
  // original_tile is the title that is extracted from the document (if it had any).
  optional string original_title = 5;
  DocumentType document_type = 6;
  repeated DocumentArtifact artifacts = 7;
  // tdm_status tracks if the Document that has been scraped had a machine-readable TDM opt-out.
  DocumentTdmStatus tdm_status = 8;
  optional google.protobuf.Timestamp published_at = 9;
}

// An Artifact is a file that has been produced for a Document either from Scraping or from Analysis.
message DocumentArtifact {
  string id = 1;
  ObjectMeta meta = 2;
  ArtifactFormat format = 3;
  string storage_url = 4;
  int64 size_bytes = 5;
  string mime_type = 6;
}
