syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/cortex/v1alpha1/common.proto";
import "google/protobuf/timestamp.proto";

// =====================================================================================================================

enum DocumentType {
  DOCUMENT_TYPE_UNSPECIFIED = 0;
  DOCUMENT_TYPE_ATTACHMENT = 1;            // An attachment that adds context to another document.
  DOCUMENT_TYPE_LEGAL = 2;                 // A legal document, like the Terms of Service of website.
  DOCUMENT_TYPE_ROBOTS_TXT = 3;            // A robots.txt File.
  DOCUMENT_TYPE_ARTICLE = 4;               // An article that is e.g. published by news portal or a blog.
  DOCUMENT_TYPE_SOCIAL = 5;                // A social media posting.
  DOCUMENT_TYPE_JOB_POSTING = 6;           // A job offering.
  DOCUMENT_TYPE_RESOLUTION_PROPOSAL = 7;   // A resolution proposal for a formal resolution, e.g. used in politics.
  DOCUMENT_TYPE_RESOLUTION = 8;            // A resolution (formal decision), e.g. used in politics.
}

enum ArtifactFormat {
  ARTIFACT_FORMAT_UNSPECIFIED = 0;
  ARTIFACT_FORMAT_HTML = 1;
  ARTIFACT_FORMAT_PDF = 2;
  ARTIFACT_FORMAT_IMAGE = 3;
  ARTIFACT_FORMAT_MARKDOWN = 4;
  ARTIFACT_FORMAT_CLEAN_MARKDOWN = 5;
}

enum DocumentTdmStatus {
  DOCUMENT_TDM_STATUS_UNSPECIFIED = 0;
  DOCUMENT_TDM_STATUS_ALLOWED = 1;
  DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED = 2;
}

// A Document is one discovered Document like a News Article.
message Document {
  string id = 1;
  ObjectMeta meta = 2;
  string publisher_id = 3;
  optional string parent_document_id = 4;
  // original_url is the URL that lead to the creation of this document.
  string original_url = 5;
  // original_tile is the title that is extracted from the document (if it had any).
  optional string original_title = 6;
  DocumentType document_type = 7;
  repeated DocumentArtifact artifacts = 8;
  // tdm_status tracks if the Document that has been scraped had a machine-readable TDM opt-out.
  DocumentTdmStatus tdm_status = 9;
  optional google.protobuf.Timestamp published_at = 10;
}

// An Artifact is a file that has been produced for a Document either from Scraping or from Analysis.
message DocumentArtifact {
  string id = 1;
  ObjectMeta meta = 2;
  ArtifactFormat format = 3;
  File file = 4;
}
