syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/cortex/v1alpha1/common.proto";
import "buf/validate/validate.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

// =====================================================================================================================

enum PublisherType {
  PUBLISHER_TYPE_UNSPECIFIED = 0;
  PUBLISHER_TYPE_PUBLIC_AUTHORITY = 1;
  PUBLISHER_TYPE_CORPORATE = 2;
  PUBLISHER_TYPE_MEDIA = 3;
  PUBLISHER_TYPE_ORGANIZATION = 4;
  PUBLISHER_TYPE_INDIVIDUAL = 5;
  PUBLISHER_TYPE_ACADEMIC = 6;
}

// The PublisherTdmPolicy defines a TDM Policy that applies to all resources of a publisher.
enum PublisherTdmPolicy {
  PUBLISHER_TDM_POLICY_UNSPECIFIED = 0;  // no special policy has been detected for a publisher.
  PUBLISHER_TDM_POLICY_ALLOWED = 1;      // the publisher explicitly allows TDM.
  PUBLISHER_TDM_POLICY_OPT_OUT = 2;      // the publisher opted-out of using his contents for TDM.
}

// The FeedType defines the
enum FeedType {
  FEED_TYPE_UNSPECIFIED = 0;  // This should not be used and marks a missing information.
  FEED_TYPE_HTML_SINGLE = 1;  // HTML page that will be used as target for a ScrapeOrder when the feed is polled.
  FEED_TYPE_HTML_CRAWL = 2;   // HTML page that will be used as entrypoint for a CrawlOrder when the feed is polled.
  FEED_TYPE_RSS = 3;          // RSS-Feed that will generate ScrapeOrders for all entries when the feed is polled.
  FEED_TYPE_ATOM = 4;         // Atom-Feed that will generate ScrapeOrders for all entries when the feed is polled.
  FEED_TYPE_OPARL = 5;        // OPARL base URL that will generate ScrapeOrders for all
}

// A Publisher is a entity that is publishing content. This can be e.g. a News Agency.
message Publisher {
  string id = 1;
  ObjectMeta meta = 2;
  PublisherType publisher_type = 3;
  string name = 4;
  string description = 5;
  string web_url = 6;
  repeated Feed feeds = 7;
  PublisherTdmPolicy tdm_policy = 8;
  repeated TdmPolicyHistory tdm_status_history = 9;
  optional Lease lease = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 12;
}

// The TdmStatusHistory tracks the history of the TDM Status for a Publisher.
// A new history item is added when the Analysis of a Document produces a different TdmStatus then
// currently stored for the Publisher.
message TdmPolicyHistory {
  string document_id = 1;
  PublisherTdmPolicy tdm_policy = 2;
  google.protobuf.Timestamp created_at = 3;
}


// A Feed is a URL that is used to create Scrape- or Crawl-Orders.
// It always belongs to one publisher.
message Feed {
  string id = 1;
  ObjectMeta meta = 2;
  string publisher_id = 3;
  FeedType feed_type = 4;
  string url = 5;
  PollInterval poll_interval = 6;
  optional FeedPoll last_poll = 7;
}

// A single Poll of a Feed.
message FeedPoll {
  optional google.protobuf.Timestamp created_at = 4;
  optional google.protobuf.Timestamp result_last_modified = 6;
  optional string result_etag = 7;
}

// =====================================================================================================================

service PublisherService {
  rpc ListPublishers(ListPublishersRequest) returns (ListPublishersResponse) {}
  rpc GetPublisher(GetPublisherRequest) returns (GetPublisherResponse) {}
  rpc AddPublisher(AddPublisherRequest) returns (AddPublisherResponse) {}
  rpc GetPublishersForProcession(GetPublishersForProcessionRequest) returns (GetPublishersForProcessionResponse) {}
  rpc GetPublishersOfLeaserHolder(GetPublishersOfLeaserHolderRequest) returns (GetPublishersOfLeaserHolderResponse) {}
}

// =====================================================================================================================

message ListPublishersRequest {
  google.protobuf.FieldMask field_mask = 1;
  ListOrder list_order = 2;
  optional int64 limit = 3 [(buf.validate.field).int64 = {gte: 1, lte: 1000}];
  optional int64 offset = 4 [(buf.validate.field).int64 = {gte: 0}];
}

message ListPublishersResponse {
  uint64 total_count = 1;
  repeated Publisher items = 2;
}

// =====================================================================================================================

message GetPublisherRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message GetPublisherResponse {
  Publisher item = 1;
}

// =====================================================================================================================

message AddPublisherRequest {
  message Feed {
    FeedType feed_type = 1;
    string url = 2;
    optional int32 poll_interval_seconds = 3;
  }
  string name = 1;
  string description = 2;
  string web_url = 3;
}

message AddPublisherResponse {
  Publisher item = 1;
}

// =====================================================================================================================

message GetPublishersForProcessionRequest {
  string lease_holder = 1;
  google.protobuf.Duration lease_duration = 2 [(buf.validate.field).duration = {gte: {seconds: 60}, lte: {seconds: 600}}];
  int32 limit = 3 [(buf.validate.field).int32 = {gte: 1}];
}

message GetPublishersForProcessionResponse {
  repeated Publisher items = 2;
}

// =====================================================================================================================

message GetPublishersOfLeaserHolderRequest {
  string lease_holder = 1;
}

message GetPublishersOfLeaserHolderResponse {
  repeated Publisher items = 2;
}
