syntax = "proto3";
package exonex.cortex.v1alpha1;

import "exonex/cortex/v1alpha1/common.proto";
import "google/protobuf/timestamp.proto";

// =====================================================================================================================

// A ScrapeOrder is a concrete order to scrape one web resource and save it as a Document.
message ScrapeOrder {
  string id = 1;
  ObjectMeta meta = 2;
  string publisher_id = 3;
  string url = 4;
  OrderStatus status = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp finished_at = 7;
}
