// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/analysis.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_exonex_cortex_v1alpha1_analysis_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_analysis_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/analysis.proto\x12\x16exonex.cortex.v1alpha1B\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rAnalysisProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var file_exonex_cortex_v1alpha1_analysis_proto_goTypes = []any{}
var file_exonex_cortex_v1alpha1_analysis_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_analysis_proto_init() }
func file_exonex_cortex_v1alpha1_analysis_proto_init() {
	if File_exonex_cortex_v1alpha1_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc), len(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_analysis_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_analysis_proto_depIdxs,
	}.Build()
	File_exonex_cortex_v1alpha1_analysis_proto = out.File
	file_exonex_cortex_v1alpha1_analysis_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_analysis_proto_depIdxs = nil
}
