// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/analysis.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Analysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	AnalyzerId    string                 `protobuf:"bytes,3,opt,name=analyzer_id,json=analyzerId,proto3" json:"analyzer_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *Analysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Analysis) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Analysis) GetAnalyzerId() string {
	if x != nil {
		return x.AnalyzerId
	}
	return ""
}

func (x *Analysis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Analysis) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type Analyzer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Group             string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Kind              string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Name              string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	NeedArtifactTypes []string               `protobuf:"bytes,8,rep,name=need_artifact_types,json=needArtifactTypes,proto3" json:"need_artifact_types,omitempty"`
	Instances         []*AnalyzerInstance    `protobuf:"bytes,9,rep,name=instances,proto3" json:"instances,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Analyzer) Reset() {
	*x = Analyzer{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analyzer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analyzer) ProtoMessage() {}

func (x *Analyzer) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analyzer.ProtoReflect.Descriptor instead.
func (*Analyzer) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *Analyzer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Analyzer) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Analyzer) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Analyzer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Analyzer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Analyzer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Analyzer) GetNeedArtifactTypes() []string {
	if x != nil {
		return x.NeedArtifactTypes
	}
	return nil
}

func (x *Analyzer) GetInstances() []*AnalyzerInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *Analyzer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AnalyzerInstance struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastHeartbeatReceivedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_heartbeat_received_at,json=lastHeartbeatReceivedAt,proto3" json:"last_heartbeat_received_at,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AnalyzerInstance) Reset() {
	*x = AnalyzerInstance{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzerInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzerInstance) ProtoMessage() {}

func (x *AnalyzerInstance) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzerInstance.ProtoReflect.Descriptor instead.
func (*AnalyzerInstance) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzerInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalyzerInstance) GetLastHeartbeatReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatReceivedAt
	}
	return nil
}

func (x *AnalyzerInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAnalyzerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Group             string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Kind              string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	NeedArtifactTypes []string               `protobuf:"bytes,6,rep,name=need_artifact_types,json=needArtifactTypes,proto3" json:"need_artifact_types,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAnalyzerRequest) Reset() {
	*x = CreateAnalyzerRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyzerRequest) ProtoMessage() {}

func (x *CreateAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*CreateAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAnalyzerRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateAnalyzerRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateAnalyzerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateAnalyzerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAnalyzerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAnalyzerRequest) GetNeedArtifactTypes() []string {
	if x != nil {
		return x.NeedArtifactTypes
	}
	return nil
}

type CreateAnalyzerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalyzerResponse) Reset() {
	*x = CreateAnalyzerResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalyzerResponse) ProtoMessage() {}

func (x *CreateAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*CreateAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{4}
}

type ListAnalyzersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         *uint64                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint64                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalyzersRequest) Reset() {
	*x = ListAnalyzersRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalyzersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalyzersRequest) ProtoMessage() {}

func (x *ListAnalyzersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalyzersRequest.ProtoReflect.Descriptor instead.
func (*ListAnalyzersRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ListAnalyzersRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListAnalyzersRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type ListAnalyzersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyzers     []*Analyzer            `protobuf:"bytes,1,rep,name=analyzers,proto3" json:"analyzers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalyzersResponse) Reset() {
	*x = ListAnalyzersResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalyzersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalyzersResponse) ProtoMessage() {}

func (x *ListAnalyzersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalyzersResponse.ProtoReflect.Descriptor instead.
func (*ListAnalyzersResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *ListAnalyzersResponse) GetAnalyzers() []*Analyzer {
	if x != nil {
		return x.Analyzers
	}
	return nil
}

type GetAnalyzerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalyzerId    string                 `protobuf:"bytes,1,opt,name=analyzer_id,json=analyzerId,proto3" json:"analyzer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyzerRequest) Reset() {
	*x = GetAnalyzerRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyzerRequest) ProtoMessage() {}

func (x *GetAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnalyzerRequest) GetAnalyzerId() string {
	if x != nil {
		return x.AnalyzerId
	}
	return ""
}

type GetAnalyzerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyzer      *Analyzer              `protobuf:"bytes,1,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyzerResponse) Reset() {
	*x = GetAnalyzerResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyzerResponse) ProtoMessage() {}

func (x *GetAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnalyzerResponse) GetAnalyzer() *Analyzer {
	if x != nil {
		return x.Analyzer
	}
	return nil
}

type LeaseAnalyzerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseIdentity *string                `protobuf:"bytes,1,opt,name=lease_identity,json=leaseIdentity,proto3,oneof" json:"lease_identity,omitempty"`
	LeaseDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=lease_duration,json=leaseDuration,proto3,oneof" json:"lease_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseAnalyzerRequest) Reset() {
	*x = LeaseAnalyzerRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseAnalyzerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseAnalyzerRequest) ProtoMessage() {}

func (x *LeaseAnalyzerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseAnalyzerRequest.ProtoReflect.Descriptor instead.
func (*LeaseAnalyzerRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *LeaseAnalyzerRequest) GetLeaseIdentity() string {
	if x != nil && x.LeaseIdentity != nil {
		return *x.LeaseIdentity
	}
	return ""
}

func (x *LeaseAnalyzerRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

type LeaseAnalyzerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseAnalyzerResponse) Reset() {
	*x = LeaseAnalyzerResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseAnalyzerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseAnalyzerResponse) ProtoMessage() {}

func (x *LeaseAnalyzerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseAnalyzerResponse.ProtoReflect.Descriptor instead.
func (*LeaseAnalyzerResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{10}
}

type SendAnalyzerHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalyzerId    string                 `protobuf:"bytes,1,opt,name=analyzer_id,json=analyzerId,proto3" json:"analyzer_id,omitempty"`
	InstanceName  string                 `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyzerHeartbeatRequest) Reset() {
	*x = SendAnalyzerHeartbeatRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyzerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyzerHeartbeatRequest) ProtoMessage() {}

func (x *SendAnalyzerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyzerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*SendAnalyzerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{11}
}

func (x *SendAnalyzerHeartbeatRequest) GetAnalyzerId() string {
	if x != nil {
		return x.AnalyzerId
	}
	return ""
}

func (x *SendAnalyzerHeartbeatRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type SendAnalyzerHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyzerHeartbeatResponse) Reset() {
	*x = SendAnalyzerHeartbeatResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyzerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyzerHeartbeatResponse) ProtoMessage() {}

func (x *SendAnalyzerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyzerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*SendAnalyzerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{12}
}

type CreateAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	AnalyzerId    string                 `protobuf:"bytes,2,opt,name=analyzer_id,json=analyzerId,proto3" json:"analyzer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalysisRequest) Reset() {
	*x = CreateAnalysisRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalysisRequest) ProtoMessage() {}

func (x *CreateAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalysisRequest.ProtoReflect.Descriptor instead.
func (*CreateAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAnalysisRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateAnalysisRequest) GetAnalyzerId() string {
	if x != nil {
		return x.AnalyzerId
	}
	return ""
}

type CreateAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnalysisResponse) Reset() {
	*x = CreateAnalysisResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnalysisResponse) ProtoMessage() {}

func (x *CreateAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnalysisResponse.ProtoReflect.Descriptor instead.
func (*CreateAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAnalysisResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PollAnalysesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         bool                   `protobuf:"varint,1,opt,name=lease,proto3" json:"lease,omitempty"`
	LeaseIdentity *string                `protobuf:"bytes,2,opt,name=lease_identity,json=leaseIdentity,proto3,oneof" json:"lease_identity,omitempty"`
	LeaseDuration *durationpb.Duration   `protobuf:"bytes,3,opt,name=lease_duration,json=leaseDuration,proto3,oneof" json:"lease_duration,omitempty"`
	Limit         uint64                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollAnalysesRequest) Reset() {
	*x = PollAnalysesRequest{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAnalysesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAnalysesRequest) ProtoMessage() {}

func (x *PollAnalysesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAnalysesRequest.ProtoReflect.Descriptor instead.
func (*PollAnalysesRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{15}
}

func (x *PollAnalysesRequest) GetLease() bool {
	if x != nil {
		return x.Lease
	}
	return false
}

func (x *PollAnalysesRequest) GetLeaseIdentity() string {
	if x != nil && x.LeaseIdentity != nil {
		return *x.LeaseIdentity
	}
	return ""
}

func (x *PollAnalysesRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *PollAnalysesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PollAnalysesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyses      []*Analysis            `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollAnalysesResponse) Reset() {
	*x = PollAnalysesResponse{}
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollAnalysesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAnalysesResponse) ProtoMessage() {}

func (x *PollAnalysesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAnalysesResponse.ProtoReflect.Descriptor instead.
func (*PollAnalysesResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP(), []int{16}
}

func (x *PollAnalysesResponse) GetAnalyses() []*Analysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

var File_exonex_cortex_v1alpha1_analysis_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_analysis_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/analysis.proto\x12\x16exonex.cortex.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xec\x01\n" +
	"\bAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vanalyzer_id\x18\x03 \x01(\tR\n" +
	"analyzerId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vcompletedAt\x88\x01\x01B\x0f\n" +
	"\r_completed_at\"\xc7\x02\n" +
	"\bAnalyzer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12.\n" +
	"\x13need_artifact_types\x18\b \x03(\tR\x11needArtifactTypes\x12F\n" +
	"\tinstances\x18\t \x03(\v2(.exonex.cortex.v1alpha1.AnalyzerInstanceR\tinstances\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb6\x01\n" +
	"\x10AnalyzerInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12W\n" +
	"\x1alast_heartbeat_received_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x17lastHeartbeatReceivedAt\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc1\x01\n" +
	"\x15CreateAnalyzerRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12.\n" +
	"\x13need_artifact_types\x18\x06 \x03(\tR\x11needArtifactTypes\"\x18\n" +
	"\x16CreateAnalyzerResponse\"c\n" +
	"\x14ListAnalyzersRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x04H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x04H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"W\n" +
	"\x15ListAnalyzersResponse\x12>\n" +
	"\tanalyzers\x18\x01 \x03(\v2 .exonex.cortex.v1alpha1.AnalyzerR\tanalyzers\"5\n" +
	"\x12GetAnalyzerRequest\x12\x1f\n" +
	"\vanalyzer_id\x18\x01 \x01(\tR\n" +
	"analyzerId\"S\n" +
	"\x13GetAnalyzerResponse\x12<\n" +
	"\banalyzer\x18\x01 \x01(\v2 .exonex.cortex.v1alpha1.AnalyzerR\banalyzer\"\xaf\x01\n" +
	"\x14LeaseAnalyzerRequest\x12*\n" +
	"\x0elease_identity\x18\x01 \x01(\tH\x00R\rleaseIdentity\x88\x01\x01\x12E\n" +
	"\x0elease_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationH\x01R\rleaseDuration\x88\x01\x01B\x11\n" +
	"\x0f_lease_identityB\x11\n" +
	"\x0f_lease_duration\"\x17\n" +
	"\x15LeaseAnalyzerResponse\"d\n" +
	"\x1cSendAnalyzerHeartbeatRequest\x12\x1f\n" +
	"\vanalyzer_id\x18\x01 \x01(\tR\n" +
	"analyzerId\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\"\x1f\n" +
	"\x1dSendAnalyzerHeartbeatResponse\"Y\n" +
	"\x15CreateAnalysisRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vanalyzer_id\x18\x02 \x01(\tR\n" +
	"analyzerId\"(\n" +
	"\x16CreateAnalysisResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xda\x01\n" +
	"\x13PollAnalysesRequest\x12\x14\n" +
	"\x05lease\x18\x01 \x01(\bR\x05lease\x12*\n" +
	"\x0elease_identity\x18\x02 \x01(\tH\x00R\rleaseIdentity\x88\x01\x01\x12E\n" +
	"\x0elease_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x01R\rleaseDuration\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limitB\x11\n" +
	"\x0f_lease_identityB\x11\n" +
	"\x0f_lease_duration\"T\n" +
	"\x14PollAnalysesResponse\x12<\n" +
	"\banalyses\x18\x01 \x03(\v2 .exonex.cortex.v1alpha1.AnalysisR\banalyses2\xb7\x06\n" +
	"\x0fAnalysisService\x12q\n" +
	"\x0eCreateAnalyzer\x12-.exonex.cortex.v1alpha1.CreateAnalyzerRequest\x1a..exonex.cortex.v1alpha1.CreateAnalyzerResponse\"\x00\x12n\n" +
	"\rListAnalyzers\x12,.exonex.cortex.v1alpha1.ListAnalyzersRequest\x1a-.exonex.cortex.v1alpha1.ListAnalyzersResponse\"\x00\x12h\n" +
	"\vGetAnalyzer\x12*.exonex.cortex.v1alpha1.GetAnalyzerRequest\x1a+.exonex.cortex.v1alpha1.GetAnalyzerResponse\"\x00\x12n\n" +
	"\rLeaseAnalyzer\x12,.exonex.cortex.v1alpha1.LeaseAnalyzerRequest\x1a-.exonex.cortex.v1alpha1.LeaseAnalyzerResponse\"\x00\x12\x86\x01\n" +
	"\x15SendAnalyzerHeartbeat\x124.exonex.cortex.v1alpha1.SendAnalyzerHeartbeatRequest\x1a5.exonex.cortex.v1alpha1.SendAnalyzerHeartbeatResponse\"\x00\x12q\n" +
	"\x0eCreateAnalysis\x12-.exonex.cortex.v1alpha1.CreateAnalysisRequest\x1a..exonex.cortex.v1alpha1.CreateAnalysisResponse\"\x00\x12k\n" +
	"\fPollAnalyses\x12+.exonex.cortex.v1alpha1.PollAnalysesRequest\x1a,.exonex.cortex.v1alpha1.PollAnalysesResponse\"\x00B\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rAnalysisProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_analysis_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_analysis_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_analysis_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_analysis_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc), len(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_analysis_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_exonex_cortex_v1alpha1_analysis_proto_goTypes = []any{
	(*Analysis)(nil),                      // 0: exonex.cortex.v1alpha1.Analysis
	(*Analyzer)(nil),                      // 1: exonex.cortex.v1alpha1.Analyzer
	(*AnalyzerInstance)(nil),              // 2: exonex.cortex.v1alpha1.AnalyzerInstance
	(*CreateAnalyzerRequest)(nil),         // 3: exonex.cortex.v1alpha1.CreateAnalyzerRequest
	(*CreateAnalyzerResponse)(nil),        // 4: exonex.cortex.v1alpha1.CreateAnalyzerResponse
	(*ListAnalyzersRequest)(nil),          // 5: exonex.cortex.v1alpha1.ListAnalyzersRequest
	(*ListAnalyzersResponse)(nil),         // 6: exonex.cortex.v1alpha1.ListAnalyzersResponse
	(*GetAnalyzerRequest)(nil),            // 7: exonex.cortex.v1alpha1.GetAnalyzerRequest
	(*GetAnalyzerResponse)(nil),           // 8: exonex.cortex.v1alpha1.GetAnalyzerResponse
	(*LeaseAnalyzerRequest)(nil),          // 9: exonex.cortex.v1alpha1.LeaseAnalyzerRequest
	(*LeaseAnalyzerResponse)(nil),         // 10: exonex.cortex.v1alpha1.LeaseAnalyzerResponse
	(*SendAnalyzerHeartbeatRequest)(nil),  // 11: exonex.cortex.v1alpha1.SendAnalyzerHeartbeatRequest
	(*SendAnalyzerHeartbeatResponse)(nil), // 12: exonex.cortex.v1alpha1.SendAnalyzerHeartbeatResponse
	(*CreateAnalysisRequest)(nil),         // 13: exonex.cortex.v1alpha1.CreateAnalysisRequest
	(*CreateAnalysisResponse)(nil),        // 14: exonex.cortex.v1alpha1.CreateAnalysisResponse
	(*PollAnalysesRequest)(nil),           // 15: exonex.cortex.v1alpha1.PollAnalysesRequest
	(*PollAnalysesResponse)(nil),          // 16: exonex.cortex.v1alpha1.PollAnalysesResponse
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),           // 18: google.protobuf.Duration
}
var file_exonex_cortex_v1alpha1_analysis_proto_depIdxs = []int32{
	17, // 0: exonex.cortex.v1alpha1.Analysis.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: exonex.cortex.v1alpha1.Analysis.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 2: exonex.cortex.v1alpha1.Analyzer.instances:type_name -> exonex.cortex.v1alpha1.AnalyzerInstance
	17, // 3: exonex.cortex.v1alpha1.Analyzer.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: exonex.cortex.v1alpha1.AnalyzerInstance.last_heartbeat_received_at:type_name -> google.protobuf.Timestamp
	17, // 5: exonex.cortex.v1alpha1.AnalyzerInstance.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: exonex.cortex.v1alpha1.ListAnalyzersResponse.analyzers:type_name -> exonex.cortex.v1alpha1.Analyzer
	1,  // 7: exonex.cortex.v1alpha1.GetAnalyzerResponse.analyzer:type_name -> exonex.cortex.v1alpha1.Analyzer
	18, // 8: exonex.cortex.v1alpha1.LeaseAnalyzerRequest.lease_duration:type_name -> google.protobuf.Duration
	18, // 9: exonex.cortex.v1alpha1.PollAnalysesRequest.lease_duration:type_name -> google.protobuf.Duration
	0,  // 10: exonex.cortex.v1alpha1.PollAnalysesResponse.analyses:type_name -> exonex.cortex.v1alpha1.Analysis
	3,  // 11: exonex.cortex.v1alpha1.AnalysisService.CreateAnalyzer:input_type -> exonex.cortex.v1alpha1.CreateAnalyzerRequest
	5,  // 12: exonex.cortex.v1alpha1.AnalysisService.ListAnalyzers:input_type -> exonex.cortex.v1alpha1.ListAnalyzersRequest
	7,  // 13: exonex.cortex.v1alpha1.AnalysisService.GetAnalyzer:input_type -> exonex.cortex.v1alpha1.GetAnalyzerRequest
	9,  // 14: exonex.cortex.v1alpha1.AnalysisService.LeaseAnalyzer:input_type -> exonex.cortex.v1alpha1.LeaseAnalyzerRequest
	11, // 15: exonex.cortex.v1alpha1.AnalysisService.SendAnalyzerHeartbeat:input_type -> exonex.cortex.v1alpha1.SendAnalyzerHeartbeatRequest
	13, // 16: exonex.cortex.v1alpha1.AnalysisService.CreateAnalysis:input_type -> exonex.cortex.v1alpha1.CreateAnalysisRequest
	15, // 17: exonex.cortex.v1alpha1.AnalysisService.PollAnalyses:input_type -> exonex.cortex.v1alpha1.PollAnalysesRequest
	4,  // 18: exonex.cortex.v1alpha1.AnalysisService.CreateAnalyzer:output_type -> exonex.cortex.v1alpha1.CreateAnalyzerResponse
	6,  // 19: exonex.cortex.v1alpha1.AnalysisService.ListAnalyzers:output_type -> exonex.cortex.v1alpha1.ListAnalyzersResponse
	8,  // 20: exonex.cortex.v1alpha1.AnalysisService.GetAnalyzer:output_type -> exonex.cortex.v1alpha1.GetAnalyzerResponse
	10, // 21: exonex.cortex.v1alpha1.AnalysisService.LeaseAnalyzer:output_type -> exonex.cortex.v1alpha1.LeaseAnalyzerResponse
	12, // 22: exonex.cortex.v1alpha1.AnalysisService.SendAnalyzerHeartbeat:output_type -> exonex.cortex.v1alpha1.SendAnalyzerHeartbeatResponse
	14, // 23: exonex.cortex.v1alpha1.AnalysisService.CreateAnalysis:output_type -> exonex.cortex.v1alpha1.CreateAnalysisResponse
	16, // 24: exonex.cortex.v1alpha1.AnalysisService.PollAnalyses:output_type -> exonex.cortex.v1alpha1.PollAnalysesResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_analysis_proto_init() }
func file_exonex_cortex_v1alpha1_analysis_proto_init() {
	if File_exonex_cortex_v1alpha1_analysis_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[5].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[9].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_analysis_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc), len(file_exonex_cortex_v1alpha1_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_analysis_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_analysis_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_analysis_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_analysis_proto = out.File
	file_exonex_cortex_v1alpha1_analysis_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_analysis_proto_depIdxs = nil
}
