// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/artifact.proto

package cortexv1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Annotations   *structpb.Struct       `protobuf:"bytes,2,opt,name=annotations,proto3" json:"annotations,omitempty"`
	ArtifactType  string                 `protobuf:"bytes,3,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	Document      string                 `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Etag          string                 `protobuf:"bytes,8,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_exonex_cortex_v1alpha1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Artifact) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *Artifact) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *Artifact) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Artifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Artifact) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Artifact) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ArtifactType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Schema        *structpb.Struct       `protobuf:"bytes,7,opt,name=schema,proto3" json:"schema,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Etag          string                 `protobuf:"bytes,9,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactType) Reset() {
	*x = ArtifactType{}
	mi := &file_exonex_cortex_v1alpha1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactType) ProtoMessage() {}

func (x *ArtifactType) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactType.ProtoReflect.Descriptor instead.
func (*ArtifactType) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactType) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ArtifactType) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArtifactType) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ArtifactType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArtifactType) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ArtifactType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ArtifactType) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_exonex_cortex_v1alpha1_artifact_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_artifact_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/artifact.proto\x12\x16exonex.cortex.v1alpha1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xfc\x03\n" +
	"\bArtifact\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\bR\x02id\x129\n" +
	"\vannotations\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vannotations\x12H\n" +
	"\rartifact_type\x18\x03 \x01(\tB#\xfaA \n" +
	"\x1ecortex.exonex.io//ArtifactTypeR\fartifactType\x12:\n" +
	"\bdocument\x18\x04 \x01(\tB\x1e\xfaA\x1b\n" +
	"\x19cortex.exonex.io/DocumentR\bdocument\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01\x12\x12\n" +
	"\x04etag\x18\b \x01(\tR\x04etag:I\xeaAF\n" +
	"\x19cortex.exonex.io/Artifact\x12)documents/{document}/artifacts/{artifact}B\r\n" +
	"\v_deleted_at\"\x9d\x02\n" +
	"\fArtifactType\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\bR\x02id\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12/\n" +
	"\x06schema\x18\a \x01(\v2\x17.google.protobuf.StructR\x06schema\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04etag\x18\t \x01(\tR\x04etag2\x11\n" +
	"\x0fArtifactServiceB\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rArtifactProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_artifact_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_artifact_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_artifact_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_artifact_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_artifact_proto_rawDesc), len(file_exonex_cortex_v1alpha1_artifact_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_artifact_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exonex_cortex_v1alpha1_artifact_proto_goTypes = []any{
	(*Artifact)(nil),              // 0: exonex.cortex.v1alpha1.Artifact
	(*ArtifactType)(nil),          // 1: exonex.cortex.v1alpha1.ArtifactType
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_exonex_cortex_v1alpha1_artifact_proto_depIdxs = []int32{
	2, // 0: exonex.cortex.v1alpha1.Artifact.annotations:type_name -> google.protobuf.Struct
	2, // 1: exonex.cortex.v1alpha1.Artifact.payload:type_name -> google.protobuf.Struct
	3, // 2: exonex.cortex.v1alpha1.Artifact.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: exonex.cortex.v1alpha1.Artifact.deleted_at:type_name -> google.protobuf.Timestamp
	2, // 4: exonex.cortex.v1alpha1.ArtifactType.schema:type_name -> google.protobuf.Struct
	3, // 5: exonex.cortex.v1alpha1.ArtifactType.created_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_artifact_proto_init() }
func file_exonex_cortex_v1alpha1_artifact_proto_init() {
	if File_exonex_cortex_v1alpha1_artifact_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_artifact_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_artifact_proto_rawDesc), len(file_exonex_cortex_v1alpha1_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_artifact_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_artifact_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_artifact_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_artifact_proto = out.File
	file_exonex_cortex_v1alpha1_artifact_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_artifact_proto_depIdxs = nil
}
