// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/auth.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_exonex_cortex_v1alpha1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_auth_proto_rawDescGZIP(), []int{0}
}

type WhoAmIResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveRoles       []string               `protobuf:"bytes,1,rep,name=active_roles,json=activeRoles,proto3" json:"active_roles,omitempty"`
	ActivePermissions []string               `protobuf:"bytes,2,rep,name=active_permissions,json=activePermissions,proto3" json:"active_permissions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_exonex_cortex_v1alpha1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *WhoAmIResponse) GetActiveRoles() []string {
	if x != nil {
		return x.ActiveRoles
	}
	return nil
}

func (x *WhoAmIResponse) GetActivePermissions() []string {
	if x != nil {
		return x.ActivePermissions
	}
	return nil
}

var File_exonex_cortex_v1alpha1_auth_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_auth_proto_rawDesc = "" +
	"\n" +
	"!exonex/cortex/v1alpha1/auth.proto\x12\x16exonex.cortex.v1alpha1\"\x0f\n" +
	"\rWhoAmIRequest\"b\n" +
	"\x0eWhoAmIResponse\x12!\n" +
	"\factive_roles\x18\x01 \x03(\tR\vactiveRoles\x12-\n" +
	"\x12active_permissions\x18\x02 \x03(\tR\x11activePermissions2h\n" +
	"\vAuthService\x12Y\n" +
	"\x06WhoAmI\x12%.exonex.cortex.v1alpha1.WhoAmIRequest\x1a&.exonex.cortex.v1alpha1.WhoAmIResponse\"\x00B\xef\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\tAuthProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_auth_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_auth_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_auth_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_auth_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_auth_proto_rawDesc), len(file_exonex_cortex_v1alpha1_auth_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_auth_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exonex_cortex_v1alpha1_auth_proto_goTypes = []any{
	(*WhoAmIRequest)(nil),  // 0: exonex.cortex.v1alpha1.WhoAmIRequest
	(*WhoAmIResponse)(nil), // 1: exonex.cortex.v1alpha1.WhoAmIResponse
}
var file_exonex_cortex_v1alpha1_auth_proto_depIdxs = []int32{
	0, // 0: exonex.cortex.v1alpha1.AuthService.WhoAmI:input_type -> exonex.cortex.v1alpha1.WhoAmIRequest
	1, // 1: exonex.cortex.v1alpha1.AuthService.WhoAmI:output_type -> exonex.cortex.v1alpha1.WhoAmIResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_auth_proto_init() }
func file_exonex_cortex_v1alpha1_auth_proto_init() {
	if File_exonex_cortex_v1alpha1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_auth_proto_rawDesc), len(file_exonex_cortex_v1alpha1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_auth_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_auth_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_auth_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_auth_proto = out.File
	file_exonex_cortex_v1alpha1_auth_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_auth_proto_depIdxs = nil
}
