// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/common.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOrder int32

const (
	ListOrder_LIST_ORDER_UNSPECIFIED  ListOrder = 0
	ListOrder_LIST_ORDER_OLDEST_FIRST ListOrder = 1
	ListOrder_LIST_ORDER_NEWEST_FIRST ListOrder = 2
)

// Enum value maps for ListOrder.
var (
	ListOrder_name = map[int32]string{
		0: "LIST_ORDER_UNSPECIFIED",
		1: "LIST_ORDER_OLDEST_FIRST",
		2: "LIST_ORDER_NEWEST_FIRST",
	}
	ListOrder_value = map[string]int32{
		"LIST_ORDER_UNSPECIFIED":  0,
		"LIST_ORDER_OLDEST_FIRST": 1,
		"LIST_ORDER_NEWEST_FIRST": 2,
	}
)

func (x ListOrder) Enum() *ListOrder {
	p := new(ListOrder)
	*p = x
	return p
}

func (x ListOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_common_proto_enumTypes[0].Descriptor()
}

func (ListOrder) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_common_proto_enumTypes[0]
}

func (x ListOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListOrder.Descriptor instead.
func (ListOrder) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PLANNED     OrderStatus = 1
	OrderStatus_ORDER_STATUS_SUCCEEDED   OrderStatus = 2
	OrderStatus_ORDER_STATUS_FAILED      OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PLANNED",
		2: "ORDER_STATUS_SUCCEEDED",
		3: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PLANNED":     1,
		"ORDER_STATUS_SUCCEEDED":   2,
		"ORDER_STATUS_FAILED":      3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_common_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_common_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

var File_exonex_cortex_v1alpha1_common_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_common_proto_rawDesc = "" +
	"\n" +
	"#exonex/cortex/v1alpha1/common.proto\x12\x16exonex.cortex.v1alpha1*a\n" +
	"\tListOrder\x12\x1a\n" +
	"\x16LIST_ORDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LIST_ORDER_OLDEST_FIRST\x10\x01\x12\x1b\n" +
	"\x17LIST_ORDER_NEWEST_FIRST\x10\x02*z\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PLANNED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_SUCCEEDED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x03B\xf1\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\vCommonProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_common_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_common_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_common_proto_rawDesc), len(file_exonex_cortex_v1alpha1_common_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_common_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exonex_cortex_v1alpha1_common_proto_goTypes = []any{
	(ListOrder)(0),   // 0: exonex.cortex.v1alpha1.ListOrder
	(OrderStatus)(0), // 1: exonex.cortex.v1alpha1.OrderStatus
}
var file_exonex_cortex_v1alpha1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_common_proto_init() }
func file_exonex_cortex_v1alpha1_common_proto_init() {
	if File_exonex_cortex_v1alpha1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_common_proto_rawDesc), len(file_exonex_cortex_v1alpha1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_common_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_common_proto_enumTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_common_proto = out.File
	file_exonex_cortex_v1alpha1_common_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_common_proto_depIdxs = nil
}
