// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/common.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOrder int32

const (
	ListOrder_LIST_ORDER_UNSPECIFIED  ListOrder = 0
	ListOrder_LIST_ORDER_OLDEST_FIRST ListOrder = 1
	ListOrder_LIST_ORDER_NEWEST_FIRST ListOrder = 2
)

// Enum value maps for ListOrder.
var (
	ListOrder_name = map[int32]string{
		0: "LIST_ORDER_UNSPECIFIED",
		1: "LIST_ORDER_OLDEST_FIRST",
		2: "LIST_ORDER_NEWEST_FIRST",
	}
	ListOrder_value = map[string]int32{
		"LIST_ORDER_UNSPECIFIED":  0,
		"LIST_ORDER_OLDEST_FIRST": 1,
		"LIST_ORDER_NEWEST_FIRST": 2,
	}
)

func (x ListOrder) Enum() *ListOrder {
	p := new(ListOrder)
	*p = x
	return p
}

func (x ListOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_common_proto_enumTypes[0].Descriptor()
}

func (ListOrder) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_common_proto_enumTypes[0]
}

func (x ListOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListOrder.Descriptor instead.
func (ListOrder) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PLANNED     OrderStatus = 1
	OrderStatus_ORDER_STATUS_SUCCEEDED   OrderStatus = 2
	OrderStatus_ORDER_STATUS_FAILED      OrderStatus = 3
	OrderStatus_ORDER_STATUS_ABORTED     OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PLANNED",
		2: "ORDER_STATUS_SUCCEEDED",
		3: "ORDER_STATUS_FAILED",
		4: "ORDER_STATUS_ABORTED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PLANNED":     1,
		"ORDER_STATUS_SUCCEEDED":   2,
		"ORDER_STATUS_FAILED":      3,
		"ORDER_STATUS_ABORTED":     4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_common_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_common_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

// ObjectMeta defines typical metadata that is available for most objects.
type ObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   map[string]string      `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Finalizers    []string               `protobuf:"bytes,2,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LogEvents     []*LogEvent            `protobuf:"bytes,4,rep,name=log_events,json=logEvents,proto3" json:"log_events,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,5,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *ObjectMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectMeta) GetLogEvents() []*LogEvent {
	if x != nil {
		return x.LogEvents
	}
	return nil
}

func (x *ObjectMeta) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

// A LogEvent contains a Log information about an Object.
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RetentionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=retention_time,json=retentionTime,proto3,oneof" json:"retention_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{1}
}

func (x *LogEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogEvent) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetRetentionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RetentionTime
	}
	return nil
}

// A Lease is the signal that the Object is currently hold by another process for processing.
type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        string                 `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RenewedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=renewed_at,json=renewedAt,proto3" json:"renewed_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Lease) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Lease) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lease) GetRenewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RenewedAt
	}
	return nil
}

func (x *Lease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_exonex_cortex_v1alpha1_common_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_common_proto_rawDesc = "" +
	"\n" +
	"#exonex/cortex/v1alpha1/common.proto\x12\x16exonex.cortex.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x83\x03\n" +
	"\n" +
	"ObjectMeta\x12U\n" +
	"\vannotations\x18\x01 \x03(\v23.exonex.cortex.v1alpha1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1e\n" +
	"\n" +
	"finalizers\x18\x02 \x03(\tR\n" +
	"finalizers\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\n" +
	"log_events\x18\x04 \x03(\v2 .exonex.cortex.v1alpha1.LogEventR\tlogEvents\x128\n" +
	"\x05lease\x18\x05 \x01(\v2\x1d.exonex.cortex.v1alpha1.LeaseH\x00R\x05lease\x88\x01\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_lease\"\xc7\x01\n" +
	"\bLogEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12F\n" +
	"\x0eretention_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rretentionTime\x88\x01\x01B\x11\n" +
	"\x0f_retention_time\"\xd0\x01\n" +
	"\x05Lease\x12\x16\n" +
	"\x06holder\x18\x01 \x01(\tR\x06holder\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"renewed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trenewedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt*a\n" +
	"\tListOrder\x12\x1a\n" +
	"\x16LIST_ORDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LIST_ORDER_OLDEST_FIRST\x10\x01\x12\x1b\n" +
	"\x17LIST_ORDER_NEWEST_FIRST\x10\x02*\x94\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PLANNED\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_SUCCEEDED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x03\x12\x18\n" +
	"\x14ORDER_STATUS_ABORTED\x10\x04B\xf1\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\vCommonProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_common_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_common_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_common_proto_rawDesc), len(file_exonex_cortex_v1alpha1_common_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_common_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exonex_cortex_v1alpha1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_exonex_cortex_v1alpha1_common_proto_goTypes = []any{
	(ListOrder)(0),                // 0: exonex.cortex.v1alpha1.ListOrder
	(OrderStatus)(0),              // 1: exonex.cortex.v1alpha1.OrderStatus
	(*ObjectMeta)(nil),            // 2: exonex.cortex.v1alpha1.ObjectMeta
	(*LogEvent)(nil),              // 3: exonex.cortex.v1alpha1.LogEvent
	(*Lease)(nil),                 // 4: exonex.cortex.v1alpha1.Lease
	nil,                           // 5: exonex.cortex.v1alpha1.ObjectMeta.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_exonex_cortex_v1alpha1_common_proto_depIdxs = []int32{
	5, // 0: exonex.cortex.v1alpha1.ObjectMeta.annotations:type_name -> exonex.cortex.v1alpha1.ObjectMeta.AnnotationsEntry
	6, // 1: exonex.cortex.v1alpha1.ObjectMeta.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: exonex.cortex.v1alpha1.ObjectMeta.log_events:type_name -> exonex.cortex.v1alpha1.LogEvent
	4, // 3: exonex.cortex.v1alpha1.ObjectMeta.lease:type_name -> exonex.cortex.v1alpha1.Lease
	6, // 4: exonex.cortex.v1alpha1.LogEvent.time:type_name -> google.protobuf.Timestamp
	6, // 5: exonex.cortex.v1alpha1.LogEvent.retention_time:type_name -> google.protobuf.Timestamp
	6, // 6: exonex.cortex.v1alpha1.Lease.created_at:type_name -> google.protobuf.Timestamp
	6, // 7: exonex.cortex.v1alpha1.Lease.renewed_at:type_name -> google.protobuf.Timestamp
	6, // 8: exonex.cortex.v1alpha1.Lease.expires_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_common_proto_init() }
func file_exonex_cortex_v1alpha1_common_proto_init() {
	if File_exonex_cortex_v1alpha1_common_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_common_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_common_proto_rawDesc), len(file_exonex_cortex_v1alpha1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_common_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_common_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_common_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_common_proto = out.File
	file_exonex_cortex_v1alpha1_common_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_common_proto_depIdxs = nil
}
