// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/crawling.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrawlOrderStatus int32

const (
	CrawlOrderStatus_CRAWL_ORDER_STATUS_UNSPECIFIED CrawlOrderStatus = 0
	CrawlOrderStatus_CRAWL_ORDER_STATUS_PLANNED     CrawlOrderStatus = 1
	CrawlOrderStatus_CRAWL_ORDER_STATUS_SUCCEEDED   CrawlOrderStatus = 2
	CrawlOrderStatus_CRAWL_ORDER_STATUS_FAILED      CrawlOrderStatus = 3
	CrawlOrderStatus_CRAWL_ORDER_STATUS_ABORTED     CrawlOrderStatus = 4
)

// Enum value maps for CrawlOrderStatus.
var (
	CrawlOrderStatus_name = map[int32]string{
		0: "CRAWL_ORDER_STATUS_UNSPECIFIED",
		1: "CRAWL_ORDER_STATUS_PLANNED",
		2: "CRAWL_ORDER_STATUS_SUCCEEDED",
		3: "CRAWL_ORDER_STATUS_FAILED",
		4: "CRAWL_ORDER_STATUS_ABORTED",
	}
	CrawlOrderStatus_value = map[string]int32{
		"CRAWL_ORDER_STATUS_UNSPECIFIED": 0,
		"CRAWL_ORDER_STATUS_PLANNED":     1,
		"CRAWL_ORDER_STATUS_SUCCEEDED":   2,
		"CRAWL_ORDER_STATUS_FAILED":      3,
		"CRAWL_ORDER_STATUS_ABORTED":     4,
	}
)

func (x CrawlOrderStatus) Enum() *CrawlOrderStatus {
	p := new(CrawlOrderStatus)
	*p = x
	return p
}

func (x CrawlOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrawlOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_crawling_proto_enumTypes[0].Descriptor()
}

func (CrawlOrderStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_crawling_proto_enumTypes[0]
}

func (x CrawlOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrawlOrderStatus.Descriptor instead.
func (CrawlOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_crawling_proto_rawDescGZIP(), []int{0}
}

// A CrawlOrder is a order to Crawl a Website to discover possible Documents that can then be scraped by a scrape order.
type CrawlOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	PublisherId   string                 `protobuf:"bytes,3,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	EntrypointUrl string                 `protobuf:"bytes,4,opt,name=entrypoint_url,json=entrypointUrl,proto3" json:"entrypoint_url,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,5,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	CrawlResult   *CrawlOrderResult      `protobuf:"bytes,6,opt,name=crawl_result,json=crawlResult,proto3,oneof" json:"crawl_result,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Events        []*LogEvent            `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlOrder) Reset() {
	*x = CrawlOrder{}
	mi := &file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlOrder) ProtoMessage() {}

func (x *CrawlOrder) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlOrder.ProtoReflect.Descriptor instead.
func (*CrawlOrder) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_crawling_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrawlOrder) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CrawlOrder) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *CrawlOrder) GetEntrypointUrl() string {
	if x != nil {
		return x.EntrypointUrl
	}
	return ""
}

func (x *CrawlOrder) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *CrawlOrder) GetCrawlResult() *CrawlOrderResult {
	if x != nil {
		return x.CrawlResult
	}
	return nil
}

func (x *CrawlOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CrawlOrder) GetEvents() []*LogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// A result tracks metadata to a Crawl- or ScrapeOrder.
// It is typically present after the Order has been executed.
type CrawlOrderResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The status_reason field can be used to add additional context on why the CrawlOrderResult is in the
	// current OrderStatus.
	Status         OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=exonex.cortex.v1alpha1.OrderStatus" json:"status,omitempty"`
	StatusReason   *string                `protobuf:"bytes,2,opt,name=status_reason,json=statusReason,proto3,oneof" json:"status_reason,omitempty"`
	ScrapeOrderIds []string               `protobuf:"bytes,3,rep,name=scrape_order_ids,json=scrapeOrderIds,proto3" json:"scrape_order_ids,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrawlOrderResult) Reset() {
	*x = CrawlOrderResult{}
	mi := &file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlOrderResult) ProtoMessage() {}

func (x *CrawlOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlOrderResult.ProtoReflect.Descriptor instead.
func (*CrawlOrderResult) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_crawling_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlOrderResult) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *CrawlOrderResult) GetStatusReason() string {
	if x != nil && x.StatusReason != nil {
		return *x.StatusReason
	}
	return ""
}

func (x *CrawlOrderResult) GetScrapeOrderIds() []string {
	if x != nil {
		return x.ScrapeOrderIds
	}
	return nil
}

func (x *CrawlOrderResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_exonex_cortex_v1alpha1_crawling_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_crawling_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/crawling.proto\x12\x16exonex.cortex.v1alpha1\x1a#exonex/cortex/v1alpha1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xba\x03\n" +
	"\n" +
	"CrawlOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".exonex.cortex.v1alpha1.ObjectMetaR\x04meta\x12!\n" +
	"\fpublisher_id\x18\x03 \x01(\tR\vpublisherId\x12%\n" +
	"\x0eentrypoint_url\x18\x04 \x01(\tR\rentrypointUrl\x128\n" +
	"\x05lease\x18\x05 \x01(\v2\x1d.exonex.cortex.v1alpha1.LeaseH\x00R\x05lease\x88\x01\x01\x12P\n" +
	"\fcrawl_result\x18\x06 \x01(\v2(.exonex.cortex.v1alpha1.CrawlOrderResultH\x01R\vcrawlResult\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\x06events\x18\b \x03(\v2 .exonex.cortex.v1alpha1.LogEventR\x06eventsB\b\n" +
	"\x06_leaseB\x0f\n" +
	"\r_crawl_result\"\xf2\x01\n" +
	"\x10CrawlOrderResult\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.exonex.cortex.v1alpha1.OrderStatusR\x06status\x12(\n" +
	"\rstatus_reason\x18\x02 \x01(\tH\x00R\fstatusReason\x88\x01\x01\x12(\n" +
	"\x10scrape_order_ids\x18\x03 \x03(\tR\x0escrapeOrderIds\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAtB\x10\n" +
	"\x0e_status_reason*\xb7\x01\n" +
	"\x10CrawlOrderStatus\x12\"\n" +
	"\x1eCRAWL_ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCRAWL_ORDER_STATUS_PLANNED\x10\x01\x12 \n" +
	"\x1cCRAWL_ORDER_STATUS_SUCCEEDED\x10\x02\x12\x1d\n" +
	"\x19CRAWL_ORDER_STATUS_FAILED\x10\x03\x12\x1e\n" +
	"\x1aCRAWL_ORDER_STATUS_ABORTED\x10\x04B\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rCrawlingProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_crawling_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_crawling_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_crawling_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_crawling_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_crawling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_crawling_proto_rawDesc), len(file_exonex_cortex_v1alpha1_crawling_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_crawling_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_crawling_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exonex_cortex_v1alpha1_crawling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exonex_cortex_v1alpha1_crawling_proto_goTypes = []any{
	(CrawlOrderStatus)(0),         // 0: exonex.cortex.v1alpha1.CrawlOrderStatus
	(*CrawlOrder)(nil),            // 1: exonex.cortex.v1alpha1.CrawlOrder
	(*CrawlOrderResult)(nil),      // 2: exonex.cortex.v1alpha1.CrawlOrderResult
	(*ObjectMeta)(nil),            // 3: exonex.cortex.v1alpha1.ObjectMeta
	(*Lease)(nil),                 // 4: exonex.cortex.v1alpha1.Lease
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*LogEvent)(nil),              // 6: exonex.cortex.v1alpha1.LogEvent
	(OrderStatus)(0),              // 7: exonex.cortex.v1alpha1.OrderStatus
}
var file_exonex_cortex_v1alpha1_crawling_proto_depIdxs = []int32{
	3, // 0: exonex.cortex.v1alpha1.CrawlOrder.meta:type_name -> exonex.cortex.v1alpha1.ObjectMeta
	4, // 1: exonex.cortex.v1alpha1.CrawlOrder.lease:type_name -> exonex.cortex.v1alpha1.Lease
	2, // 2: exonex.cortex.v1alpha1.CrawlOrder.crawl_result:type_name -> exonex.cortex.v1alpha1.CrawlOrderResult
	5, // 3: exonex.cortex.v1alpha1.CrawlOrder.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: exonex.cortex.v1alpha1.CrawlOrder.events:type_name -> exonex.cortex.v1alpha1.LogEvent
	7, // 5: exonex.cortex.v1alpha1.CrawlOrderResult.status:type_name -> exonex.cortex.v1alpha1.OrderStatus
	5, // 6: exonex.cortex.v1alpha1.CrawlOrderResult.finished_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_crawling_proto_init() }
func file_exonex_cortex_v1alpha1_crawling_proto_init() {
	if File_exonex_cortex_v1alpha1_crawling_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_common_proto_init()
	file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_crawling_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_crawling_proto_rawDesc), len(file_exonex_cortex_v1alpha1_crawling_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_crawling_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_crawling_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_crawling_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_crawling_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_crawling_proto = out.File
	file_exonex_cortex_v1alpha1_crawling_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_crawling_proto_depIdxs = nil
}
