// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/documents.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentType int32

const (
	DocumentType_DOCUMENT_TYPE_UNSPECIFIED         DocumentType = 0
	DocumentType_DOCUMENT_TYPE_ATTACHMENT          DocumentType = 1 // An attachment that adds context to another document.
	DocumentType_DOCUMENT_TYPE_LEGAL               DocumentType = 2 // A legal document, like the Terms of Service of website.
	DocumentType_DOCUMENT_TYPE_ROBOTS_TXT          DocumentType = 3 // A robots.txt File.
	DocumentType_DOCUMENT_TYPE_ARTICLE             DocumentType = 4 // An article that is e.g. published by news portal or a blog.
	DocumentType_DOCUMENT_TYPE_SOCIAL              DocumentType = 5 // A social media posting.
	DocumentType_DOCUMENT_TYPE_JOB_POSTING         DocumentType = 6 // A job offering.
	DocumentType_DOCUMENT_TYPE_RESOLUTION_PROPOSAL DocumentType = 7 // A resolution proposal for a formal resolution, e.g. used in politics.
	DocumentType_DOCUMENT_TYPE_RESOLUTION          DocumentType = 8 // A resolution (formal decision), e.g. used in politics.
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOCUMENT_TYPE_UNSPECIFIED",
		1: "DOCUMENT_TYPE_ATTACHMENT",
		2: "DOCUMENT_TYPE_LEGAL",
		3: "DOCUMENT_TYPE_ROBOTS_TXT",
		4: "DOCUMENT_TYPE_ARTICLE",
		5: "DOCUMENT_TYPE_SOCIAL",
		6: "DOCUMENT_TYPE_JOB_POSTING",
		7: "DOCUMENT_TYPE_RESOLUTION_PROPOSAL",
		8: "DOCUMENT_TYPE_RESOLUTION",
	}
	DocumentType_value = map[string]int32{
		"DOCUMENT_TYPE_UNSPECIFIED":         0,
		"DOCUMENT_TYPE_ATTACHMENT":          1,
		"DOCUMENT_TYPE_LEGAL":               2,
		"DOCUMENT_TYPE_ROBOTS_TXT":          3,
		"DOCUMENT_TYPE_ARTICLE":             4,
		"DOCUMENT_TYPE_SOCIAL":              5,
		"DOCUMENT_TYPE_JOB_POSTING":         6,
		"DOCUMENT_TYPE_RESOLUTION_PROPOSAL": 7,
		"DOCUMENT_TYPE_RESOLUTION":          8,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{0}
}

type ArtifactFormat int32

const (
	ArtifactFormat_ARTIFACT_FORMAT_UNSPECIFIED    ArtifactFormat = 0
	ArtifactFormat_ARTIFACT_FORMAT_HTML           ArtifactFormat = 1
	ArtifactFormat_ARTIFACT_FORMAT_PDF            ArtifactFormat = 2
	ArtifactFormat_ARTIFACT_FORMAT_IMAGE          ArtifactFormat = 3
	ArtifactFormat_ARTIFACT_FORMAT_MARKDOWN       ArtifactFormat = 4
	ArtifactFormat_ARTIFACT_FORMAT_CLEAN_MARKDOWN ArtifactFormat = 5
)

// Enum value maps for ArtifactFormat.
var (
	ArtifactFormat_name = map[int32]string{
		0: "ARTIFACT_FORMAT_UNSPECIFIED",
		1: "ARTIFACT_FORMAT_HTML",
		2: "ARTIFACT_FORMAT_PDF",
		3: "ARTIFACT_FORMAT_IMAGE",
		4: "ARTIFACT_FORMAT_MARKDOWN",
		5: "ARTIFACT_FORMAT_CLEAN_MARKDOWN",
	}
	ArtifactFormat_value = map[string]int32{
		"ARTIFACT_FORMAT_UNSPECIFIED":    0,
		"ARTIFACT_FORMAT_HTML":           1,
		"ARTIFACT_FORMAT_PDF":            2,
		"ARTIFACT_FORMAT_IMAGE":          3,
		"ARTIFACT_FORMAT_MARKDOWN":       4,
		"ARTIFACT_FORMAT_CLEAN_MARKDOWN": 5,
	}
)

func (x ArtifactFormat) Enum() *ArtifactFormat {
	p := new(ArtifactFormat)
	*p = x
	return p
}

func (x ArtifactFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[1].Descriptor()
}

func (ArtifactFormat) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[1]
}

func (x ArtifactFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactFormat.Descriptor instead.
func (ArtifactFormat) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{1}
}

type DocumentTdmStatus int32

const (
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_UNSPECIFIED      DocumentTdmStatus = 0
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_ALLOWED          DocumentTdmStatus = 1
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED DocumentTdmStatus = 2
)

// Enum value maps for DocumentTdmStatus.
var (
	DocumentTdmStatus_name = map[int32]string{
		0: "DOCUMENT_TDM_STATUS_UNSPECIFIED",
		1: "DOCUMENT_TDM_STATUS_ALLOWED",
		2: "DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED",
	}
	DocumentTdmStatus_value = map[string]int32{
		"DOCUMENT_TDM_STATUS_UNSPECIFIED":      0,
		"DOCUMENT_TDM_STATUS_ALLOWED":          1,
		"DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED": 2,
	}
)

func (x DocumentTdmStatus) Enum() *DocumentTdmStatus {
	p := new(DocumentTdmStatus)
	*p = x
	return p
}

func (x DocumentTdmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentTdmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[2].Descriptor()
}

func (DocumentTdmStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[2]
}

func (x DocumentTdmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentTdmStatus.Descriptor instead.
func (DocumentTdmStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{2}
}

// A Document is one discovered Document like a News Article.
type Document struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta             *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	PublisherId      string                 `protobuf:"bytes,3,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	ParentDocumentId *string                `protobuf:"bytes,4,opt,name=parent_document_id,json=parentDocumentId,proto3,oneof" json:"parent_document_id,omitempty"`
	// original_url is the URL that lead to the creation of this document.
	OriginalUrl string `protobuf:"bytes,5,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// original_tile is the title that is extracted from the document (if it had any).
	OriginalTitle *string             `protobuf:"bytes,6,opt,name=original_title,json=originalTitle,proto3,oneof" json:"original_title,omitempty"`
	DocumentType  DocumentType        `protobuf:"varint,7,opt,name=document_type,json=documentType,proto3,enum=exonex.cortex.v1alpha1.DocumentType" json:"document_type,omitempty"`
	Artifacts     []*DocumentArtifact `protobuf:"bytes,8,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// tdm_status tracks if the Document that has been scraped had a machine-readable TDM opt-out.
	TdmStatus     DocumentTdmStatus      `protobuf:"varint,9,opt,name=tdm_status,json=tdmStatus,proto3,enum=exonex.cortex.v1alpha1.DocumentTdmStatus" json:"tdm_status,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Document) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *Document) GetParentDocumentId() string {
	if x != nil && x.ParentDocumentId != nil {
		return *x.ParentDocumentId
	}
	return ""
}

func (x *Document) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Document) GetOriginalTitle() string {
	if x != nil && x.OriginalTitle != nil {
		return *x.OriginalTitle
	}
	return ""
}

func (x *Document) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *Document) GetArtifacts() []*DocumentArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Document) GetTdmStatus() DocumentTdmStatus {
	if x != nil {
		return x.TdmStatus
	}
	return DocumentTdmStatus_DOCUMENT_TDM_STATUS_UNSPECIFIED
}

func (x *Document) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// An Artifact is a file that has been produced for a Document either from Scraping or from Analysis.
type DocumentArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Format        ArtifactFormat         `protobuf:"varint,3,opt,name=format,proto3,enum=exonex.cortex.v1alpha1.ArtifactFormat" json:"format,omitempty"`
	File          *File                  `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentArtifact) Reset() {
	*x = DocumentArtifact{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentArtifact) ProtoMessage() {}

func (x *DocumentArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentArtifact.ProtoReflect.Descriptor instead.
func (*DocumentArtifact) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentArtifact) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DocumentArtifact) GetFormat() ArtifactFormat {
	if x != nil {
		return x.Format
	}
	return ArtifactFormat_ARTIFACT_FORMAT_UNSPECIFIED
}

func (x *DocumentArtifact) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

var File_exonex_cortex_v1alpha1_documents_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_documents_proto_rawDesc = "" +
	"\n" +
	"&exonex/cortex/v1alpha1/documents.proto\x12\x16exonex.cortex.v1alpha1\x1a#exonex/cortex/v1alpha1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x04\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".exonex.cortex.v1alpha1.ObjectMetaR\x04meta\x12!\n" +
	"\fpublisher_id\x18\x03 \x01(\tR\vpublisherId\x121\n" +
	"\x12parent_document_id\x18\x04 \x01(\tH\x00R\x10parentDocumentId\x88\x01\x01\x12!\n" +
	"\foriginal_url\x18\x05 \x01(\tR\voriginalUrl\x12*\n" +
	"\x0eoriginal_title\x18\x06 \x01(\tH\x01R\roriginalTitle\x88\x01\x01\x12I\n" +
	"\rdocument_type\x18\a \x01(\x0e2$.exonex.cortex.v1alpha1.DocumentTypeR\fdocumentType\x12F\n" +
	"\tartifacts\x18\b \x03(\v2(.exonex.cortex.v1alpha1.DocumentArtifactR\tartifacts\x12H\n" +
	"\n" +
	"tdm_status\x18\t \x01(\x0e2).exonex.cortex.v1alpha1.DocumentTdmStatusR\ttdmStatus\x12B\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vpublishedAt\x88\x01\x01B\x15\n" +
	"\x13_parent_document_idB\x11\n" +
	"\x0f_original_titleB\x0f\n" +
	"\r_published_at\"\xcc\x01\n" +
	"\x10DocumentArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".exonex.cortex.v1alpha1.ObjectMetaR\x04meta\x12>\n" +
	"\x06format\x18\x03 \x01(\x0e2&.exonex.cortex.v1alpha1.ArtifactFormatR\x06format\x120\n" +
	"\x04file\x18\x04 \x01(\v2\x1c.exonex.cortex.v1alpha1.FileR\x04file*\x9b\x02\n" +
	"\fDocumentType\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DOCUMENT_TYPE_ATTACHMENT\x10\x01\x12\x17\n" +
	"\x13DOCUMENT_TYPE_LEGAL\x10\x02\x12\x1c\n" +
	"\x18DOCUMENT_TYPE_ROBOTS_TXT\x10\x03\x12\x19\n" +
	"\x15DOCUMENT_TYPE_ARTICLE\x10\x04\x12\x18\n" +
	"\x14DOCUMENT_TYPE_SOCIAL\x10\x05\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_JOB_POSTING\x10\x06\x12%\n" +
	"!DOCUMENT_TYPE_RESOLUTION_PROPOSAL\x10\a\x12\x1c\n" +
	"\x18DOCUMENT_TYPE_RESOLUTION\x10\b*\xc1\x01\n" +
	"\x0eArtifactFormat\x12\x1f\n" +
	"\x1bARTIFACT_FORMAT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_FORMAT_HTML\x10\x01\x12\x17\n" +
	"\x13ARTIFACT_FORMAT_PDF\x10\x02\x12\x19\n" +
	"\x15ARTIFACT_FORMAT_IMAGE\x10\x03\x12\x1c\n" +
	"\x18ARTIFACT_FORMAT_MARKDOWN\x10\x04\x12\"\n" +
	"\x1eARTIFACT_FORMAT_CLEAN_MARKDOWN\x10\x05*\x83\x01\n" +
	"\x11DocumentTdmStatus\x12#\n" +
	"\x1fDOCUMENT_TDM_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDOCUMENT_TDM_STATUS_ALLOWED\x10\x01\x12(\n" +
	"$DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED\x10\x02B\xf4\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\x0eDocumentsProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_documents_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_documents_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_documents_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_documents_proto_rawDesc), len(file_exonex_cortex_v1alpha1_documents_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_documents_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_exonex_cortex_v1alpha1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exonex_cortex_v1alpha1_documents_proto_goTypes = []any{
	(DocumentType)(0),             // 0: exonex.cortex.v1alpha1.DocumentType
	(ArtifactFormat)(0),           // 1: exonex.cortex.v1alpha1.ArtifactFormat
	(DocumentTdmStatus)(0),        // 2: exonex.cortex.v1alpha1.DocumentTdmStatus
	(*Document)(nil),              // 3: exonex.cortex.v1alpha1.Document
	(*DocumentArtifact)(nil),      // 4: exonex.cortex.v1alpha1.DocumentArtifact
	(*ObjectMeta)(nil),            // 5: exonex.cortex.v1alpha1.ObjectMeta
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*File)(nil),                  // 7: exonex.cortex.v1alpha1.File
}
var file_exonex_cortex_v1alpha1_documents_proto_depIdxs = []int32{
	5, // 0: exonex.cortex.v1alpha1.Document.meta:type_name -> exonex.cortex.v1alpha1.ObjectMeta
	0, // 1: exonex.cortex.v1alpha1.Document.document_type:type_name -> exonex.cortex.v1alpha1.DocumentType
	4, // 2: exonex.cortex.v1alpha1.Document.artifacts:type_name -> exonex.cortex.v1alpha1.DocumentArtifact
	2, // 3: exonex.cortex.v1alpha1.Document.tdm_status:type_name -> exonex.cortex.v1alpha1.DocumentTdmStatus
	6, // 4: exonex.cortex.v1alpha1.Document.published_at:type_name -> google.protobuf.Timestamp
	5, // 5: exonex.cortex.v1alpha1.DocumentArtifact.meta:type_name -> exonex.cortex.v1alpha1.ObjectMeta
	1, // 6: exonex.cortex.v1alpha1.DocumentArtifact.format:type_name -> exonex.cortex.v1alpha1.ArtifactFormat
	7, // 7: exonex.cortex.v1alpha1.DocumentArtifact.file:type_name -> exonex.cortex.v1alpha1.File
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_documents_proto_init() }
func file_exonex_cortex_v1alpha1_documents_proto_init() {
	if File_exonex_cortex_v1alpha1_documents_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_common_proto_init()
	file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_documents_proto_rawDesc), len(file_exonex_cortex_v1alpha1_documents_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_documents_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_documents_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_documents_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_documents_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_documents_proto = out.File
	file_exonex_cortex_v1alpha1_documents_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_documents_proto_depIdxs = nil
}
