// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/document.proto

package cortexv1alpha1

import (
	_ "github.com/alexzimmer96/exonex/pkg/api/exonex/api/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID that is used to uniquely identify a Document.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Annotations are small chunks of information that are added to a Document and can be queried.
	// They are stored as JSON object that is
	Annotations *structpb.Struct `protobuf:"bytes,2,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Finalizers are indicators that certain background actions for a Document must be performed before the
	// Document resource can be deleted from the Database.
	// For example, removing the uploaded file from the storage volume.
	Finalizers []string `protobuf:"bytes,3,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	// Indicates if the upload of the file for this document has already been finished.
	FileUploadCompleted bool `protobuf:"varint,4,opt,name=file_upload_completed,json=fileUploadCompleted,proto3" json:"file_upload_completed,omitempty"`
	// The MIME type of the uploaded file.
	// This field is immutable once set and will be used as restriction when generating Upload URLs.
	FileMimeType string `protobuf:"bytes,5,opt,name=file_mime_type,json=fileMimeType,proto3" json:"file_mime_type,omitempty"`
	// The size of the uploaded file in bytes.
	// This field may be an estimate until the upload of the file is completed.
	FileSizeBytes int64 `protobuf:"varint,6,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	// Name of the volume that stores the file.
	FileStorageVolume string `protobuf:"bytes,7,opt,name=file_storage_volume,json=fileStorageVolume,proto3" json:"file_storage_volume,omitempty"`
	// Key or path on the storage volume where the file of this document is stored.
	FileStorageKey string `protobuf:"bytes,8,opt,name=file_storage_key,json=fileStorageKey,proto3" json:"file_storage_key,omitempty"`
	// Reference to the cortex.exonex.io/Publisher that published the file.
	// This field is immutable once set and can be used to evaluate policies, e.g. regarding procession.
	Publisher string `protobuf:"bytes,9,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// The time this document has been created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time this document has been updated the last time.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The time this object has been marked for deletion.
	// Documents follow a soft-deletion process, where all
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// The Entity Tag (ETag) indicates
	Etag          string `protobuf:"bytes,13,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Document) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *Document) GetFileUploadCompleted() bool {
	if x != nil {
		return x.FileUploadCompleted
	}
	return false
}

func (x *Document) GetFileMimeType() string {
	if x != nil {
		return x.FileMimeType
	}
	return ""
}

func (x *Document) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *Document) GetFileStorageVolume() string {
	if x != nil {
		return x.FileStorageVolume
	}
	return ""
}

func (x *Document) GetFileStorageKey() string {
	if x != nil {
		return x.FileStorageKey
	}
	return ""
}

func (x *Document) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Document) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Document) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *int64                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	Filter        *string                `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`                  // this is currently not implemented.
	OrderBy       *string                `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"` // this is currently not implemented.
	ShowDeleted   *bool                  `protobuf:"varint,5,opt,name=show_deleted,json=showDeleted,proto3,oneof" json:"show_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsRequest) GetPageSize() int64 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

func (x *ListDocumentsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ListDocumentsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListDocumentsRequest) GetShowDeleted() bool {
	if x != nil && x.ShowDeleted != nil {
		return *x.ShowDeleted
	}
	return false
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublisherId   string                 `protobuf:"bytes,1,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SourceUrl     *string                `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3,oneof" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDocumentRequest) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *CreateDocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateDocumentRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateDocumentRequest) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

type CreateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDocumentResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateDocumentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateDocumentUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentUploadUrlRequest) Reset() {
	*x = CreateDocumentUploadUrlRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentUploadUrlRequest) ProtoMessage() {}

func (x *CreateDocumentUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDocumentUploadUrlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateDocumentUploadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentUploadUrlResponse) Reset() {
	*x = CreateDocumentUploadUrlResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentUploadUrlResponse) ProtoMessage() {}

func (x *CreateDocumentUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDocumentUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateDocumentUploadUrlResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDocumentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{10}
}

type LeaseDocumentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeaseHolderIdentity string                 `protobuf:"bytes,2,opt,name=lease_holder_identity,json=leaseHolderIdentity,proto3" json:"lease_holder_identity,omitempty"`
	LeaseDuration       *durationpb.Duration   `protobuf:"bytes,3,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LeaseDocumentRequest) Reset() {
	*x = LeaseDocumentRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseDocumentRequest) ProtoMessage() {}

func (x *LeaseDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseDocumentRequest.ProtoReflect.Descriptor instead.
func (*LeaseDocumentRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{11}
}

func (x *LeaseDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LeaseDocumentRequest) GetLeaseHolderIdentity() string {
	if x != nil {
		return x.LeaseHolderIdentity
	}
	return ""
}

func (x *LeaseDocumentRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

type LeaseDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseDocumentResponse) Reset() {
	*x = LeaseDocumentResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseDocumentResponse) ProtoMessage() {}

func (x *LeaseDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseDocumentResponse.ProtoReflect.Descriptor instead.
func (*LeaseDocumentResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{12}
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP(), []int{14}
}

var File_exonex_cortex_v1alpha1_document_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_document_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/document.proto\x12\x16exonex.cortex.v1alpha1\x1a\x1fexonex/api/v1/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xf9\x05\n" +
	"\bDocument\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\bR\x02id\x12>\n" +
	"\vannotations\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x03R\vannotations\x12#\n" +
	"\n" +
	"finalizers\x18\x03 \x03(\tB\x03\xe0A\x03R\n" +
	"finalizers\x12^\n" +
	"\x15file_upload_completed\x18\x04 \x01(\bB*\x92\xb5\x18&documents.update/file_upload_completedR\x13fileUploadCompleted\x12)\n" +
	"\x0efile_mime_type\x18\x05 \x01(\tB\x03\xe0A\x05R\ffileMimeType\x12L\n" +
	"\x0ffile_size_bytes\x18\x06 \x01(\x03B$\x92\xb5\x18 documents.update/file_size_bytesR\rfileSizeBytes\x123\n" +
	"\x13file_storage_volume\x18\a \x01(\tB\x03\xe0A\x03R\x11fileStorageVolume\x12-\n" +
	"\x10file_storage_key\x18\b \x01(\tB\x03\xe0A\x03R\x0efileStorageKey\x12I\n" +
	"\tpublisher\x18\t \x01(\tB+\xe0A\x05\xfaA%\n" +
	"#cortex.exonex.io/v1alpha1/PublisherR\tpublisher\x12>\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12C\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x00R\tdeletedAt\x88\x01\x01\x12\x17\n" +
	"\x04etag\x18\r \x01(\tB\x03\xe0A\x03R\x04etagB\r\n" +
	"\v_deleted_at\"\x87\x02\n" +
	"\x14ListDocumentsRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\x03H\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01\x12\x1b\n" +
	"\x06filter\x18\x03 \x01(\tH\x02R\x06filter\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x04 \x01(\tH\x03R\aorderBy\x88\x01\x01\x12&\n" +
	"\fshow_deleted\x18\x05 \x01(\bH\x04R\vshowDeleted\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\t\n" +
	"\a_filterB\v\n" +
	"\t_order_byB\x0f\n" +
	"\r_show_deleted\"\x98\x01\n" +
	"\x15ListDocumentsResponse\x12>\n" +
	"\tdocuments\x18\x01 \x03(\v2 .exonex.cortex.v1alpha1.DocumentR\tdocuments\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x13GetDocumentResponse\x12<\n" +
	"\bdocument\x18\x01 \x01(\v2 .exonex.cortex.v1alpha1.DocumentR\bdocument\"\xa9\x01\n" +
	"\x15CreateDocumentRequest\x12!\n" +
	"\fpublisher_id\x18\x01 \x01(\tR\vpublisherId\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\"\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tH\x00R\tsourceUrl\x88\x01\x01B\r\n" +
	"\v_source_url\"\x82\x01\n" +
	"\x16CreateDocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"0\n" +
	"\x1eCreateDocumentUploadUrlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x1fCreateDocumentUploadUrlResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"T\n" +
	"\x15UpdateDocumentRequest\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x18\n" +
	"\x16UpdateDocumentResponse\"\x9c\x01\n" +
	"\x14LeaseDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x15lease_holder_identity\x18\x02 \x01(\tR\x13leaseHolderIdentity\x12@\n" +
	"\x0elease_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\"\x17\n" +
	"\x15LeaseDocumentResponse\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteDocumentResponse2\xce\x05\n" +
	"\x0fDocumentService\x12\x80\x01\n" +
	"\rListDocuments\x12,.exonex.cortex.v1alpha1.ListDocumentsRequest\x1a-.exonex.cortex.v1alpha1.ListDocumentsResponse\"\x12\x8a\xb5\x18\x0edocuments.read\x12z\n" +
	"\vGetDocument\x12*.exonex.cortex.v1alpha1.GetDocumentRequest\x1a+.exonex.cortex.v1alpha1.GetDocumentResponse\"\x12\x8a\xb5\x18\x0edocuments.read\x12\x85\x01\n" +
	"\x0eCreateDocument\x12-.exonex.cortex.v1alpha1.CreateDocumentRequest\x1a..exonex.cortex.v1alpha1.CreateDocumentResponse\"\x14\x8a\xb5\x18\x10documents.create\x12\xab\x01\n" +
	"\x17CreateDocumentUploadUrl\x126.exonex.cortex.v1alpha1.CreateDocumentUploadUrlRequest\x1a7.exonex.cortex.v1alpha1.CreateDocumentUploadUrlResponse\"\x1f\x8a\xb5\x18\x1bdocuments.upload_url.create\x12\x85\x01\n" +
	"\x0eUpdateDocument\x12-.exonex.cortex.v1alpha1.UpdateDocumentRequest\x1a..exonex.cortex.v1alpha1.UpdateDocumentResponse\"\x14\x8a\xb5\x18\x10documents.updateB\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rDocumentProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_document_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_document_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_document_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_document_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_document_proto_rawDesc), len(file_exonex_cortex_v1alpha1_document_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_document_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_exonex_cortex_v1alpha1_document_proto_goTypes = []any{
	(*Document)(nil),                        // 0: exonex.cortex.v1alpha1.Document
	(*ListDocumentsRequest)(nil),            // 1: exonex.cortex.v1alpha1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),           // 2: exonex.cortex.v1alpha1.ListDocumentsResponse
	(*GetDocumentRequest)(nil),              // 3: exonex.cortex.v1alpha1.GetDocumentRequest
	(*GetDocumentResponse)(nil),             // 4: exonex.cortex.v1alpha1.GetDocumentResponse
	(*CreateDocumentRequest)(nil),           // 5: exonex.cortex.v1alpha1.CreateDocumentRequest
	(*CreateDocumentResponse)(nil),          // 6: exonex.cortex.v1alpha1.CreateDocumentResponse
	(*CreateDocumentUploadUrlRequest)(nil),  // 7: exonex.cortex.v1alpha1.CreateDocumentUploadUrlRequest
	(*CreateDocumentUploadUrlResponse)(nil), // 8: exonex.cortex.v1alpha1.CreateDocumentUploadUrlResponse
	(*UpdateDocumentRequest)(nil),           // 9: exonex.cortex.v1alpha1.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil),          // 10: exonex.cortex.v1alpha1.UpdateDocumentResponse
	(*LeaseDocumentRequest)(nil),            // 11: exonex.cortex.v1alpha1.LeaseDocumentRequest
	(*LeaseDocumentResponse)(nil),           // 12: exonex.cortex.v1alpha1.LeaseDocumentResponse
	(*DeleteDocumentRequest)(nil),           // 13: exonex.cortex.v1alpha1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),          // 14: exonex.cortex.v1alpha1.DeleteDocumentResponse
	(*structpb.Struct)(nil),                 // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),           // 17: google.protobuf.FieldMask
	(*durationpb.Duration)(nil),             // 18: google.protobuf.Duration
}
var file_exonex_cortex_v1alpha1_document_proto_depIdxs = []int32{
	15, // 0: exonex.cortex.v1alpha1.Document.annotations:type_name -> google.protobuf.Struct
	16, // 1: exonex.cortex.v1alpha1.Document.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: exonex.cortex.v1alpha1.Document.updated_at:type_name -> google.protobuf.Timestamp
	16, // 3: exonex.cortex.v1alpha1.Document.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 4: exonex.cortex.v1alpha1.ListDocumentsResponse.documents:type_name -> exonex.cortex.v1alpha1.Document
	0,  // 5: exonex.cortex.v1alpha1.GetDocumentResponse.document:type_name -> exonex.cortex.v1alpha1.Document
	16, // 6: exonex.cortex.v1alpha1.CreateDocumentResponse.expires_at:type_name -> google.protobuf.Timestamp
	16, // 7: exonex.cortex.v1alpha1.CreateDocumentUploadUrlResponse.expires_at:type_name -> google.protobuf.Timestamp
	17, // 8: exonex.cortex.v1alpha1.UpdateDocumentRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 9: exonex.cortex.v1alpha1.LeaseDocumentRequest.lease_duration:type_name -> google.protobuf.Duration
	1,  // 10: exonex.cortex.v1alpha1.DocumentService.ListDocuments:input_type -> exonex.cortex.v1alpha1.ListDocumentsRequest
	3,  // 11: exonex.cortex.v1alpha1.DocumentService.GetDocument:input_type -> exonex.cortex.v1alpha1.GetDocumentRequest
	5,  // 12: exonex.cortex.v1alpha1.DocumentService.CreateDocument:input_type -> exonex.cortex.v1alpha1.CreateDocumentRequest
	7,  // 13: exonex.cortex.v1alpha1.DocumentService.CreateDocumentUploadUrl:input_type -> exonex.cortex.v1alpha1.CreateDocumentUploadUrlRequest
	9,  // 14: exonex.cortex.v1alpha1.DocumentService.UpdateDocument:input_type -> exonex.cortex.v1alpha1.UpdateDocumentRequest
	2,  // 15: exonex.cortex.v1alpha1.DocumentService.ListDocuments:output_type -> exonex.cortex.v1alpha1.ListDocumentsResponse
	4,  // 16: exonex.cortex.v1alpha1.DocumentService.GetDocument:output_type -> exonex.cortex.v1alpha1.GetDocumentResponse
	6,  // 17: exonex.cortex.v1alpha1.DocumentService.CreateDocument:output_type -> exonex.cortex.v1alpha1.CreateDocumentResponse
	8,  // 18: exonex.cortex.v1alpha1.DocumentService.CreateDocumentUploadUrl:output_type -> exonex.cortex.v1alpha1.CreateDocumentUploadUrlResponse
	10, // 19: exonex.cortex.v1alpha1.DocumentService.UpdateDocument:output_type -> exonex.cortex.v1alpha1.UpdateDocumentResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_document_proto_init() }
func file_exonex_cortex_v1alpha1_document_proto_init() {
	if File_exonex_cortex_v1alpha1_document_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_document_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_document_proto_msgTypes[1].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_document_proto_msgTypes[2].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_document_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_document_proto_rawDesc), len(file_exonex_cortex_v1alpha1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_document_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_document_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_document_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_document_proto = out.File
	file_exonex_cortex_v1alpha1_document_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_document_proto_depIdxs = nil
}
