// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/documents.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentType int32

const (
	DocumentType_DOCUMENT_TYPE_UNSPECIFIED  DocumentType = 0
	DocumentType_DOCUMENT_TYPE_LEGAL_NOTICE DocumentType = 1
	DocumentType_DOCUMENT_TYPE_ROBOTS_TXT   DocumentType = 2
	DocumentType_DOCUMENT_TYPE_ARTICLE      DocumentType = 3
	DocumentType_DOCUMENT_TYPE_SOCIAL       DocumentType = 4
	DocumentType_DOCUMENT_TYPE_JOB_POSTING  DocumentType = 5
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOCUMENT_TYPE_UNSPECIFIED",
		1: "DOCUMENT_TYPE_LEGAL_NOTICE",
		2: "DOCUMENT_TYPE_ROBOTS_TXT",
		3: "DOCUMENT_TYPE_ARTICLE",
		4: "DOCUMENT_TYPE_SOCIAL",
		5: "DOCUMENT_TYPE_JOB_POSTING",
	}
	DocumentType_value = map[string]int32{
		"DOCUMENT_TYPE_UNSPECIFIED":  0,
		"DOCUMENT_TYPE_LEGAL_NOTICE": 1,
		"DOCUMENT_TYPE_ROBOTS_TXT":   2,
		"DOCUMENT_TYPE_ARTICLE":      3,
		"DOCUMENT_TYPE_SOCIAL":       4,
		"DOCUMENT_TYPE_JOB_POSTING":  5,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{0}
}

type ArtifactFormat int32

const (
	ArtifactFormat_ARTIFACT_FORMAT_UNSPECIFIED    ArtifactFormat = 0
	ArtifactFormat_ARTIFACT_FORMAT_HTML           ArtifactFormat = 1
	ArtifactFormat_ARTIFACT_FORMAT_PDF            ArtifactFormat = 2
	ArtifactFormat_ARTIFACT_FORMAT_IMAGE          ArtifactFormat = 3
	ArtifactFormat_ARTIFACT_FORMAT_MARKDOWN       ArtifactFormat = 4
	ArtifactFormat_ARTIFACT_FORMAT_CLEAN_MARKDOWN ArtifactFormat = 5
)

// Enum value maps for ArtifactFormat.
var (
	ArtifactFormat_name = map[int32]string{
		0: "ARTIFACT_FORMAT_UNSPECIFIED",
		1: "ARTIFACT_FORMAT_HTML",
		2: "ARTIFACT_FORMAT_PDF",
		3: "ARTIFACT_FORMAT_IMAGE",
		4: "ARTIFACT_FORMAT_MARKDOWN",
		5: "ARTIFACT_FORMAT_CLEAN_MARKDOWN",
	}
	ArtifactFormat_value = map[string]int32{
		"ARTIFACT_FORMAT_UNSPECIFIED":    0,
		"ARTIFACT_FORMAT_HTML":           1,
		"ARTIFACT_FORMAT_PDF":            2,
		"ARTIFACT_FORMAT_IMAGE":          3,
		"ARTIFACT_FORMAT_MARKDOWN":       4,
		"ARTIFACT_FORMAT_CLEAN_MARKDOWN": 5,
	}
)

func (x ArtifactFormat) Enum() *ArtifactFormat {
	p := new(ArtifactFormat)
	*p = x
	return p
}

func (x ArtifactFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[1].Descriptor()
}

func (ArtifactFormat) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[1]
}

func (x ArtifactFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactFormat.Descriptor instead.
func (ArtifactFormat) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{1}
}

type DocumentTdmStatus int32

const (
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_UNSPECIFIED      DocumentTdmStatus = 0
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_ALLOWED          DocumentTdmStatus = 1
	DocumentTdmStatus_DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED DocumentTdmStatus = 2
)

// Enum value maps for DocumentTdmStatus.
var (
	DocumentTdmStatus_name = map[int32]string{
		0: "DOCUMENT_TDM_STATUS_UNSPECIFIED",
		1: "DOCUMENT_TDM_STATUS_ALLOWED",
		2: "DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED",
	}
	DocumentTdmStatus_value = map[string]int32{
		"DOCUMENT_TDM_STATUS_UNSPECIFIED":      0,
		"DOCUMENT_TDM_STATUS_ALLOWED":          1,
		"DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED": 2,
	}
)

func (x DocumentTdmStatus) Enum() *DocumentTdmStatus {
	p := new(DocumentTdmStatus)
	*p = x
	return p
}

func (x DocumentTdmStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentTdmStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[2].Descriptor()
}

func (DocumentTdmStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[2]
}

func (x DocumentTdmStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentTdmStatus.Descriptor instead.
func (DocumentTdmStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{2}
}

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_IN_PROGRESS ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_SUCCEEDED   ExecutionStatus = 2
	ExecutionStatus_EXECUTION_STATUS_FAILED      ExecutionStatus = 3
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_IN_PROGRESS",
		2: "EXECUTION_STATUS_SUCCEEDED",
		3: "EXECUTION_STATUS_FAILED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_IN_PROGRESS": 1,
		"EXECUTION_STATUS_SUCCEEDED":   2,
		"EXECUTION_STATUS_FAILED":      3,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_documents_proto_enumTypes[3].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_documents_proto_enumTypes[3]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{3}
}

// A Document is one discovered Document like a News Article.
type Document struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublisherId string                 `protobuf:"bytes,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	// original_url is the URL that lead to the creation of this document.
	OriginalUrl string `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// scrape_order_id is a reference to the ScrapeOrder that produced this document.
	ScrapeOrderId      string                 `protobuf:"bytes,4,opt,name=scrape_order_id,json=scrapeOrderId,proto3" json:"scrape_order_id,omitempty"`
	DocumentType       DocumentType           `protobuf:"varint,5,opt,name=document_type,json=documentType,proto3,enum=exonex.cortex.v1alpha1.DocumentType" json:"document_type,omitempty"`
	Artifacts          []*DocumentArtifact    `protobuf:"bytes,6,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	AnalysisExecutions []*AnalysisExecution   `protobuf:"bytes,7,rep,name=analysis_executions,json=analysisExecutions,proto3" json:"analysis_executions,omitempty"`
	TdmStatus          DocumentTdmStatus      `protobuf:"varint,8,opt,name=tdm_status,json=tdmStatus,proto3,enum=exonex.cortex.v1alpha1.DocumentTdmStatus" json:"tdm_status,omitempty"`
	PublishedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *Document) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Document) GetScrapeOrderId() string {
	if x != nil {
		return x.ScrapeOrderId
	}
	return ""
}

func (x *Document) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *Document) GetArtifacts() []*DocumentArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Document) GetAnalysisExecutions() []*AnalysisExecution {
	if x != nil {
		return x.AnalysisExecutions
	}
	return nil
}

func (x *Document) GetTdmStatus() DocumentTdmStatus {
	if x != nil {
		return x.TdmStatus
	}
	return DocumentTdmStatus_DOCUMENT_TDM_STATUS_UNSPECIFIED
}

func (x *Document) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// An Artifact is a file that has been produced for a Document either from Scraping or from Analysis.
type DocumentArtifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The analysis_execution_id is an optional reference if this artifact has been produced not by a scrape job
	// but by a AnalysisExecution.
	AnalysisExecutionId *string                `protobuf:"bytes,2,opt,name=analysis_execution_id,json=analysisExecutionId,proto3,oneof" json:"analysis_execution_id,omitempty"`
	Format              ArtifactFormat         `protobuf:"varint,3,opt,name=format,proto3,enum=exonex.cortex.v1alpha1.ArtifactFormat" json:"format,omitempty"`
	StorageUrl          string                 `protobuf:"bytes,4,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"`
	SizeBytes           int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MimeType            string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DocumentArtifact) Reset() {
	*x = DocumentArtifact{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentArtifact) ProtoMessage() {}

func (x *DocumentArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentArtifact.ProtoReflect.Descriptor instead.
func (*DocumentArtifact) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentArtifact) GetAnalysisExecutionId() string {
	if x != nil && x.AnalysisExecutionId != nil {
		return *x.AnalysisExecutionId
	}
	return ""
}

func (x *DocumentArtifact) GetFormat() ArtifactFormat {
	if x != nil {
		return x.Format
	}
	return ArtifactFormat_ARTIFACT_FORMAT_UNSPECIFIED
}

func (x *DocumentArtifact) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

func (x *DocumentArtifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DocumentArtifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *DocumentArtifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// One specific Result of a Analysis that has been performed for a Document.
type DocumentAnalysis struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	PrimarySummary        *DocumentSummaryResult   `protobuf:"bytes,1,opt,name=primary_summary,json=primarySummary,proto3,oneof" json:"primary_summary,omitempty"`
	SummaryResults        []*DocumentSummaryResult `protobuf:"bytes,2,rep,name=summary_results,json=summaryResults,proto3" json:"summary_results,omitempty"`
	PrimaryEntityAnalysis *EntityAnalysis          `protobuf:"bytes,3,opt,name=primary_entity_analysis,json=primaryEntityAnalysis,proto3,oneof" json:"primary_entity_analysis,omitempty"`
	EntityAnalyses        []*EntityAnalysis        `protobuf:"bytes,4,rep,name=entity_analyses,json=entityAnalyses,proto3" json:"entity_analyses,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DocumentAnalysis) Reset() {
	*x = DocumentAnalysis{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentAnalysis) ProtoMessage() {}

func (x *DocumentAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentAnalysis.ProtoReflect.Descriptor instead.
func (*DocumentAnalysis) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentAnalysis) GetPrimarySummary() *DocumentSummaryResult {
	if x != nil {
		return x.PrimarySummary
	}
	return nil
}

func (x *DocumentAnalysis) GetSummaryResults() []*DocumentSummaryResult {
	if x != nil {
		return x.SummaryResults
	}
	return nil
}

func (x *DocumentAnalysis) GetPrimaryEntityAnalysis() *EntityAnalysis {
	if x != nil {
		return x.PrimaryEntityAnalysis
	}
	return nil
}

func (x *DocumentAnalysis) GetEntityAnalyses() []*EntityAnalysis {
	if x != nil {
		return x.EntityAnalyses
	}
	return nil
}

// AnalysisExecution is a specific Analysis that should or have been executed for a Document.
type AnalysisExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutorId      string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutionStatus ExecutionStatus        `protobuf:"varint,3,opt,name=execution_status,json=executionStatus,proto3,enum=exonex.cortex.v1alpha1.ExecutionStatus" json:"execution_status,omitempty"`
	// The status_reason field can be used to add additional context on why the AnalysisExecution is in the
	// current ExecutionStatus.
	StatusReason  *string                `protobuf:"bytes,4,opt,name=status_reason,json=statusReason,proto3,oneof" json:"status_reason,omitempty"`
	LeaseHolder   *string                `protobuf:"bytes,5,opt,name=lease_holder,json=leaseHolder,proto3,oneof" json:"lease_holder,omitempty"`
	LeaseUntil    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lease_until,json=leaseUntil,proto3,oneof" json:"lease_until,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisExecution) Reset() {
	*x = AnalysisExecution{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisExecution) ProtoMessage() {}

func (x *AnalysisExecution) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisExecution.ProtoReflect.Descriptor instead.
func (*AnalysisExecution) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{3}
}

func (x *AnalysisExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnalysisExecution) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *AnalysisExecution) GetExecutionStatus() ExecutionStatus {
	if x != nil {
		return x.ExecutionStatus
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *AnalysisExecution) GetStatusReason() string {
	if x != nil && x.StatusReason != nil {
		return *x.StatusReason
	}
	return ""
}

func (x *AnalysisExecution) GetLeaseHolder() string {
	if x != nil && x.LeaseHolder != nil {
		return *x.LeaseHolder
	}
	return ""
}

func (x *AnalysisExecution) GetLeaseUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseUntil
	}
	return nil
}

func (x *AnalysisExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// The DocumentSummaryResult contains basic data about an Document, like a title and short summary.
type DocumentSummaryResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AnalysisExecutionId string                 `protobuf:"bytes,1,opt,name=analysis_execution_id,json=analysisExecutionId,proto3" json:"analysis_execution_id,omitempty"`
	ExecutorId          string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ShortSummary        string                 `protobuf:"bytes,4,opt,name=short_summary,json=shortSummary,proto3" json:"short_summary,omitempty"`
	ExecutiveSummary    string                 `protobuf:"bytes,5,opt,name=executive_summary,json=executiveSummary,proto3" json:"executive_summary,omitempty"`
	KeyTakeaways        []string               `protobuf:"bytes,6,rep,name=key_takeaways,json=keyTakeaways,proto3" json:"key_takeaways,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DocumentSummaryResult) Reset() {
	*x = DocumentSummaryResult{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSummaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSummaryResult) ProtoMessage() {}

func (x *DocumentSummaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSummaryResult.ProtoReflect.Descriptor instead.
func (*DocumentSummaryResult) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentSummaryResult) GetAnalysisExecutionId() string {
	if x != nil {
		return x.AnalysisExecutionId
	}
	return ""
}

func (x *DocumentSummaryResult) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *DocumentSummaryResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentSummaryResult) GetShortSummary() string {
	if x != nil {
		return x.ShortSummary
	}
	return ""
}

func (x *DocumentSummaryResult) GetExecutiveSummary() string {
	if x != nil {
		return x.ExecutiveSummary
	}
	return ""
}

func (x *DocumentSummaryResult) GetKeyTakeaways() []string {
	if x != nil {
		return x.KeyTakeaways
	}
	return nil
}

// A single Entity that has been recognized as part of an Entity Analysis.
type RecognizedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Relevance     float32                `protobuf:"fixed32,3,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizedEntity) Reset() {
	*x = RecognizedEntity{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizedEntity) ProtoMessage() {}

func (x *RecognizedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizedEntity.ProtoReflect.Descriptor instead.
func (*RecognizedEntity) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{5}
}

func (x *RecognizedEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecognizedEntity) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecognizedEntity) GetRelevance() float32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

// Contains important Entities that haven been extracted from the Document.
type EntityAnalysis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AnalysisExecutionId string                 `protobuf:"bytes,1,opt,name=analysis_execution_id,json=analysisExecutionId,proto3" json:"analysis_execution_id,omitempty"`
	ExecutorId          string                 `protobuf:"bytes,2,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	Entities            []*RecognizedEntity    `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EntityAnalysis) Reset() {
	*x = EntityAnalysis{}
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAnalysis) ProtoMessage() {}

func (x *EntityAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_documents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAnalysis.ProtoReflect.Descriptor instead.
func (*EntityAnalysis) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP(), []int{6}
}

func (x *EntityAnalysis) GetAnalysisExecutionId() string {
	if x != nil {
		return x.AnalysisExecutionId
	}
	return ""
}

func (x *EntityAnalysis) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *EntityAnalysis) GetEntities() []*RecognizedEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_exonex_cortex_v1alpha1_documents_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_documents_proto_rawDesc = "" +
	"\n" +
	"&exonex/cortex/v1alpha1/documents.proto\x12\x16exonex.cortex.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd1\x04\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\tR\vpublisherId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12&\n" +
	"\x0fscrape_order_id\x18\x04 \x01(\tR\rscrapeOrderId\x12I\n" +
	"\rdocument_type\x18\x05 \x01(\x0e2$.exonex.cortex.v1alpha1.DocumentTypeR\fdocumentType\x12F\n" +
	"\tartifacts\x18\x06 \x03(\v2(.exonex.cortex.v1alpha1.DocumentArtifactR\tartifacts\x12Z\n" +
	"\x13analysis_executions\x18\a \x03(\v2).exonex.cortex.v1alpha1.AnalysisExecutionR\x12analysisExecutions\x12H\n" +
	"\n" +
	"tdm_status\x18\b \x01(\x0e2).exonex.cortex.v1alpha1.DocumentTdmStatusR\ttdmStatus\x12B\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\vpublishedAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0f\n" +
	"\r_published_at\"\xcd\x02\n" +
	"\x10DocumentArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x15analysis_execution_id\x18\x02 \x01(\tH\x00R\x13analysisExecutionId\x88\x01\x01\x12>\n" +
	"\x06format\x18\x03 \x01(\x0e2&.exonex.cortex.v1alpha1.ArtifactFormatR\x06format\x12\x1f\n" +
	"\vstorage_url\x18\x04 \x01(\tR\n" +
	"storageUrl\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x18\n" +
	"\x16_analysis_execution_id\"\xad\x03\n" +
	"\x10DocumentAnalysis\x12[\n" +
	"\x0fprimary_summary\x18\x01 \x01(\v2-.exonex.cortex.v1alpha1.DocumentSummaryResultH\x00R\x0eprimarySummary\x88\x01\x01\x12V\n" +
	"\x0fsummary_results\x18\x02 \x03(\v2-.exonex.cortex.v1alpha1.DocumentSummaryResultR\x0esummaryResults\x12c\n" +
	"\x17primary_entity_analysis\x18\x03 \x01(\v2&.exonex.cortex.v1alpha1.EntityAnalysisH\x01R\x15primaryEntityAnalysis\x88\x01\x01\x12O\n" +
	"\x0fentity_analyses\x18\x04 \x03(\v2&.exonex.cortex.v1alpha1.EntityAnalysisR\x0eentityAnalysesB\x12\n" +
	"\x10_primary_summaryB\x1a\n" +
	"\x18_primary_entity_analysis\"\x9a\x03\n" +
	"\x11AnalysisExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x12R\n" +
	"\x10execution_status\x18\x03 \x01(\x0e2'.exonex.cortex.v1alpha1.ExecutionStatusR\x0fexecutionStatus\x12(\n" +
	"\rstatus_reason\x18\x04 \x01(\tH\x00R\fstatusReason\x88\x01\x01\x12&\n" +
	"\flease_holder\x18\x05 \x01(\tH\x01R\vleaseHolder\x88\x01\x01\x12@\n" +
	"\vlease_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\n" +
	"leaseUntil\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x10\n" +
	"\x0e_status_reasonB\x0f\n" +
	"\r_lease_holderB\x0e\n" +
	"\f_lease_until\"\xf9\x01\n" +
	"\x15DocumentSummaryResult\x122\n" +
	"\x15analysis_execution_id\x18\x01 \x01(\tR\x13analysisExecutionId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12#\n" +
	"\rshort_summary\x18\x04 \x01(\tR\fshortSummary\x12+\n" +
	"\x11executive_summary\x18\x05 \x01(\tR\x10executiveSummary\x12#\n" +
	"\rkey_takeaways\x18\x06 \x03(\tR\fkeyTakeaways\"`\n" +
	"\x10RecognizedEntity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1c\n" +
	"\trelevance\x18\x03 \x01(\x02R\trelevance\"\xab\x01\n" +
	"\x0eEntityAnalysis\x122\n" +
	"\x15analysis_execution_id\x18\x01 \x01(\tR\x13analysisExecutionId\x12\x1f\n" +
	"\vexecutor_id\x18\x02 \x01(\tR\n" +
	"executorId\x12D\n" +
	"\bentities\x18\x03 \x03(\v2(.exonex.cortex.v1alpha1.RecognizedEntityR\bentities*\xbf\x01\n" +
	"\fDocumentType\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDOCUMENT_TYPE_LEGAL_NOTICE\x10\x01\x12\x1c\n" +
	"\x18DOCUMENT_TYPE_ROBOTS_TXT\x10\x02\x12\x19\n" +
	"\x15DOCUMENT_TYPE_ARTICLE\x10\x03\x12\x18\n" +
	"\x14DOCUMENT_TYPE_SOCIAL\x10\x04\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_JOB_POSTING\x10\x05*\xc1\x01\n" +
	"\x0eArtifactFormat\x12\x1f\n" +
	"\x1bARTIFACT_FORMAT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_FORMAT_HTML\x10\x01\x12\x17\n" +
	"\x13ARTIFACT_FORMAT_PDF\x10\x02\x12\x19\n" +
	"\x15ARTIFACT_FORMAT_IMAGE\x10\x03\x12\x1c\n" +
	"\x18ARTIFACT_FORMAT_MARKDOWN\x10\x04\x12\"\n" +
	"\x1eARTIFACT_FORMAT_CLEAN_MARKDOWN\x10\x05*\x83\x01\n" +
	"\x11DocumentTdmStatus\x12#\n" +
	"\x1fDOCUMENT_TDM_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDOCUMENT_TDM_STATUS_ALLOWED\x10\x01\x12(\n" +
	"$DOCUMENT_TDM_STATUS_OPT_OUT_DETECTED\x10\x02*\x92\x01\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cEXECUTION_STATUS_IN_PROGRESS\x10\x01\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_SUCCEEDED\x10\x02\x12\x1b\n" +
	"\x17EXECUTION_STATUS_FAILED\x10\x03B\xf4\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\x0eDocumentsProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_documents_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_documents_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_documents_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_documents_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_documents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_documents_proto_rawDesc), len(file_exonex_cortex_v1alpha1_documents_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_documents_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_documents_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_exonex_cortex_v1alpha1_documents_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_exonex_cortex_v1alpha1_documents_proto_goTypes = []any{
	(DocumentType)(0),             // 0: exonex.cortex.v1alpha1.DocumentType
	(ArtifactFormat)(0),           // 1: exonex.cortex.v1alpha1.ArtifactFormat
	(DocumentTdmStatus)(0),        // 2: exonex.cortex.v1alpha1.DocumentTdmStatus
	(ExecutionStatus)(0),          // 3: exonex.cortex.v1alpha1.ExecutionStatus
	(*Document)(nil),              // 4: exonex.cortex.v1alpha1.Document
	(*DocumentArtifact)(nil),      // 5: exonex.cortex.v1alpha1.DocumentArtifact
	(*DocumentAnalysis)(nil),      // 6: exonex.cortex.v1alpha1.DocumentAnalysis
	(*AnalysisExecution)(nil),     // 7: exonex.cortex.v1alpha1.AnalysisExecution
	(*DocumentSummaryResult)(nil), // 8: exonex.cortex.v1alpha1.DocumentSummaryResult
	(*RecognizedEntity)(nil),      // 9: exonex.cortex.v1alpha1.RecognizedEntity
	(*EntityAnalysis)(nil),        // 10: exonex.cortex.v1alpha1.EntityAnalysis
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_exonex_cortex_v1alpha1_documents_proto_depIdxs = []int32{
	0,  // 0: exonex.cortex.v1alpha1.Document.document_type:type_name -> exonex.cortex.v1alpha1.DocumentType
	5,  // 1: exonex.cortex.v1alpha1.Document.artifacts:type_name -> exonex.cortex.v1alpha1.DocumentArtifact
	7,  // 2: exonex.cortex.v1alpha1.Document.analysis_executions:type_name -> exonex.cortex.v1alpha1.AnalysisExecution
	2,  // 3: exonex.cortex.v1alpha1.Document.tdm_status:type_name -> exonex.cortex.v1alpha1.DocumentTdmStatus
	11, // 4: exonex.cortex.v1alpha1.Document.published_at:type_name -> google.protobuf.Timestamp
	11, // 5: exonex.cortex.v1alpha1.Document.created_at:type_name -> google.protobuf.Timestamp
	1,  // 6: exonex.cortex.v1alpha1.DocumentArtifact.format:type_name -> exonex.cortex.v1alpha1.ArtifactFormat
	11, // 7: exonex.cortex.v1alpha1.DocumentArtifact.created_at:type_name -> google.protobuf.Timestamp
	8,  // 8: exonex.cortex.v1alpha1.DocumentAnalysis.primary_summary:type_name -> exonex.cortex.v1alpha1.DocumentSummaryResult
	8,  // 9: exonex.cortex.v1alpha1.DocumentAnalysis.summary_results:type_name -> exonex.cortex.v1alpha1.DocumentSummaryResult
	10, // 10: exonex.cortex.v1alpha1.DocumentAnalysis.primary_entity_analysis:type_name -> exonex.cortex.v1alpha1.EntityAnalysis
	10, // 11: exonex.cortex.v1alpha1.DocumentAnalysis.entity_analyses:type_name -> exonex.cortex.v1alpha1.EntityAnalysis
	3,  // 12: exonex.cortex.v1alpha1.AnalysisExecution.execution_status:type_name -> exonex.cortex.v1alpha1.ExecutionStatus
	11, // 13: exonex.cortex.v1alpha1.AnalysisExecution.lease_until:type_name -> google.protobuf.Timestamp
	11, // 14: exonex.cortex.v1alpha1.AnalysisExecution.created_at:type_name -> google.protobuf.Timestamp
	9,  // 15: exonex.cortex.v1alpha1.EntityAnalysis.entities:type_name -> exonex.cortex.v1alpha1.RecognizedEntity
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_documents_proto_init() }
func file_exonex_cortex_v1alpha1_documents_proto_init() {
	if File_exonex_cortex_v1alpha1_documents_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_documents_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_documents_proto_msgTypes[1].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_documents_proto_msgTypes[2].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_documents_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_documents_proto_rawDesc), len(file_exonex_cortex_v1alpha1_documents_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_documents_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_documents_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_documents_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_documents_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_documents_proto = out.File
	file_exonex_cortex_v1alpha1_documents_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_documents_proto_depIdxs = nil
}
