// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/feed.proto

package cortexv1alpha1

import (
	v1 "github.com/alexzimmer96/exonex/pkg/api/exonex/api/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Feed is a Datasource under which a Publisher publishes information in a machine-readable format.
type Feed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// General metadata about the Resource.
	Meta *v1.ResourceMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The UUID that is used to uniquely identify the Feed.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The kind of this Feed.
	// Can be something like RSS, Atom, OParl or something other.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// URL under which the Feed can be accessed.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// The interval between two crawls of the Feed.
	CrawlInterval *durationpb.Duration `protobuf:"bytes,5,opt,name=crawl_interval,json=crawlInterval,proto3" json:"crawl_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_exonex_cortex_v1alpha1_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_feed_proto_rawDescGZIP(), []int{0}
}

func (x *Feed) GetMeta() *v1.ResourceMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Feed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Feed) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetCrawlInterval() *durationpb.Duration {
	if x != nil {
		return x.CrawlInterval
	}
	return nil
}

var File_exonex_cortex_v1alpha1_feed_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_feed_proto_rawDesc = "" +
	"\n" +
	"!exonex/cortex/v1alpha1/feed.proto\x12\x16exonex.cortex.v1alpha1\x1a\x18exonex/api/v1/meta.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x82\x02\n" +
	"\x04Feed\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.exonex.api.v1.ResourceMetaR\x04meta\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\bR\x02id\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12@\n" +
	"\x0ecrawl_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\rcrawlInterval:L\xeaAI\n" +
	"\x15cortex.exonex.io/Feed\x12#publishers/{publisher}/feeds/{feed}*\x05feeds2\x04feedB\xef\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\tFeedProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_feed_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_feed_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_feed_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_feed_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_feed_proto_rawDesc), len(file_exonex_cortex_v1alpha1_feed_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_feed_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exonex_cortex_v1alpha1_feed_proto_goTypes = []any{
	(*Feed)(nil),                // 0: exonex.cortex.v1alpha1.Feed
	(*v1.ResourceMeta)(nil),     // 1: exonex.api.v1.ResourceMeta
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_exonex_cortex_v1alpha1_feed_proto_depIdxs = []int32{
	1, // 0: exonex.cortex.v1alpha1.Feed.meta:type_name -> exonex.api.v1.ResourceMeta
	2, // 1: exonex.cortex.v1alpha1.Feed.crawl_interval:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_feed_proto_init() }
func file_exonex_cortex_v1alpha1_feed_proto_init() {
	if File_exonex_cortex_v1alpha1_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_feed_proto_rawDesc), len(file_exonex_cortex_v1alpha1_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_feed_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_feed_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_feed_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_feed_proto = out.File
	file_exonex_cortex_v1alpha1_feed_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_feed_proto_depIdxs = nil
}
