// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/publishers.proto

package cortexv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The PublisherTdmPolicy defines a TDM Policy that applies to all resources of a publisher.
type PublisherTdmPolicy int32

const (
	PublisherTdmPolicy_PUBLISHER_TDM_POLICY_UNSPECIFIED PublisherTdmPolicy = 0 // no special policy has been detected for a publisher.
	PublisherTdmPolicy_PUBLISHER_TDM_POLICY_ALLOWED     PublisherTdmPolicy = 1 // the publisher explicitly allows TDM.
	PublisherTdmPolicy_PUBLISHER_TDM_POLICY_OPT_OUT     PublisherTdmPolicy = 2 // the publisher opted-out of using his contents for TDM.
)

// Enum value maps for PublisherTdmPolicy.
var (
	PublisherTdmPolicy_name = map[int32]string{
		0: "PUBLISHER_TDM_POLICY_UNSPECIFIED",
		1: "PUBLISHER_TDM_POLICY_ALLOWED",
		2: "PUBLISHER_TDM_POLICY_OPT_OUT",
	}
	PublisherTdmPolicy_value = map[string]int32{
		"PUBLISHER_TDM_POLICY_UNSPECIFIED": 0,
		"PUBLISHER_TDM_POLICY_ALLOWED":     1,
		"PUBLISHER_TDM_POLICY_OPT_OUT":     2,
	}
)

func (x PublisherTdmPolicy) Enum() *PublisherTdmPolicy {
	p := new(PublisherTdmPolicy)
	*p = x
	return p
}

func (x PublisherTdmPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublisherTdmPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_publishers_proto_enumTypes[0].Descriptor()
}

func (PublisherTdmPolicy) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_publishers_proto_enumTypes[0]
}

func (x PublisherTdmPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublisherTdmPolicy.Descriptor instead.
func (PublisherTdmPolicy) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{0}
}

// The FeedType defines the
type FeedType int32

const (
	FeedType_FEED_TYPE_UNSPECIFIED FeedType = 0 // This should not be used.
	FeedType_FEED_TYPE_HTML_SINGLE FeedType = 1 // A HTML page that will be used as target for a ScrapeOrder when the feed is polled.
	FeedType_FEED_TYPE_HTML_CRAWL  FeedType = 2 // A HTML page that will be used as entrypoint for a CrawlOrder when the feed is polled.
	FeedType_FEED_TYPE_RSS         FeedType = 3 // An RSS-Feed that will generate ScrapeOrders for all entries when the feed is polled.
	FeedType_FEED_TYPE_ATOM        FeedType = 4 // An Atom-Feed that will generate ScrapeOrders for all entries when the feed is polled.
)

// Enum value maps for FeedType.
var (
	FeedType_name = map[int32]string{
		0: "FEED_TYPE_UNSPECIFIED",
		1: "FEED_TYPE_HTML_SINGLE",
		2: "FEED_TYPE_HTML_CRAWL",
		3: "FEED_TYPE_RSS",
		4: "FEED_TYPE_ATOM",
	}
	FeedType_value = map[string]int32{
		"FEED_TYPE_UNSPECIFIED": 0,
		"FEED_TYPE_HTML_SINGLE": 1,
		"FEED_TYPE_HTML_CRAWL":  2,
		"FEED_TYPE_RSS":         3,
		"FEED_TYPE_ATOM":        4,
	}
)

func (x FeedType) Enum() *FeedType {
	p := new(FeedType)
	*p = x
	return p
}

func (x FeedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedType) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_publishers_proto_enumTypes[1].Descriptor()
}

func (FeedType) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_publishers_proto_enumTypes[1]
}

func (x FeedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedType.Descriptor instead.
func (FeedType) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{1}
}

// A Publisher is a entity that is publishing content. This can be e.g. a News Agency.
type Publisher struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta             *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	WebUrl           string                 `protobuf:"bytes,5,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	Feeds            []*Feed                `protobuf:"bytes,6,rep,name=feeds,proto3" json:"feeds,omitempty"`
	TdmPolicy        PublisherTdmPolicy     `protobuf:"varint,7,opt,name=tdm_policy,json=tdmPolicy,proto3,enum=exonex.cortex.v1alpha1.PublisherTdmPolicy" json:"tdm_policy,omitempty"`
	TdmStatusHistory []*TdmPolicyHistory    `protobuf:"bytes,8,rep,name=tdm_status_history,json=tdmStatusHistory,proto3" json:"tdm_status_history,omitempty"`
	Lease            *Lease                 `protobuf:"bytes,9,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{0}
}

func (x *Publisher) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Publisher) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Publisher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Publisher) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Publisher) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

func (x *Publisher) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *Publisher) GetTdmPolicy() PublisherTdmPolicy {
	if x != nil {
		return x.TdmPolicy
	}
	return PublisherTdmPolicy_PUBLISHER_TDM_POLICY_UNSPECIFIED
}

func (x *Publisher) GetTdmStatusHistory() []*TdmPolicyHistory {
	if x != nil {
		return x.TdmStatusHistory
	}
	return nil
}

func (x *Publisher) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Publisher) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Publisher) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// A Feed is a URL that is used to create Scrape- or Crawl-Orders.
// It always belongs to one publisher.
type Feed struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FeedType               FeedType               `protobuf:"varint,1,opt,name=feed_type,json=feedType,proto3,enum=exonex.cortex.v1alpha1.FeedType" json:"feed_type,omitempty"`
	Url                    string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PollIntervalSeconds    *int32                 `protobuf:"varint,3,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3,oneof" json:"poll_interval_seconds,omitempty"`
	LastPolledAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_polled_at,json=lastPolledAt,proto3,oneof" json:"last_polled_at,omitempty"`
	LastPolledLastModified *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_polled_last_modified,json=lastPolledLastModified,proto3,oneof" json:"last_polled_last_modified,omitempty"`
	LastPolledEtag         *string                `protobuf:"bytes,6,opt,name=last_polled_etag,json=lastPolledEtag,proto3,oneof" json:"last_polled_etag,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{1}
}

func (x *Feed) GetFeedType() FeedType {
	if x != nil {
		return x.FeedType
	}
	return FeedType_FEED_TYPE_UNSPECIFIED
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetPollIntervalSeconds() int32 {
	if x != nil && x.PollIntervalSeconds != nil {
		return *x.PollIntervalSeconds
	}
	return 0
}

func (x *Feed) GetLastPolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPolledAt
	}
	return nil
}

func (x *Feed) GetLastPolledLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPolledLastModified
	}
	return nil
}

func (x *Feed) GetLastPolledEtag() string {
	if x != nil && x.LastPolledEtag != nil {
		return *x.LastPolledEtag
	}
	return ""
}

// The TdmStatusHistory tracks the history of the TDM Status for a Publisher.
// A new history item is added when the Analysis of a Document produces a different TdmStatus then
// currently stored for the Publisher.
type TdmPolicyHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TdmPolicy     PublisherTdmPolicy     `protobuf:"varint,2,opt,name=tdm_policy,json=tdmPolicy,proto3,enum=exonex.cortex.v1alpha1.PublisherTdmPolicy" json:"tdm_policy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TdmPolicyHistory) Reset() {
	*x = TdmPolicyHistory{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TdmPolicyHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TdmPolicyHistory) ProtoMessage() {}

func (x *TdmPolicyHistory) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TdmPolicyHistory.ProtoReflect.Descriptor instead.
func (*TdmPolicyHistory) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{2}
}

func (x *TdmPolicyHistory) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *TdmPolicyHistory) GetTdmPolicy() PublisherTdmPolicy {
	if x != nil {
		return x.TdmPolicy
	}
	return PublisherTdmPolicy_PUBLISHER_TDM_POLICY_UNSPECIFIED
}

func (x *TdmPolicyHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPublishersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	ListOrder     ListOrder              `protobuf:"varint,2,opt,name=list_order,json=listOrder,proto3,enum=exonex.cortex.v1alpha1.ListOrder" json:"list_order,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int64                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishersRequest) Reset() {
	*x = ListPublishersRequest{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishersRequest) ProtoMessage() {}

func (x *ListPublishersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishersRequest.ProtoReflect.Descriptor instead.
func (*ListPublishersRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{3}
}

func (x *ListPublishersRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *ListPublishersRequest) GetListOrder() ListOrder {
	if x != nil {
		return x.ListOrder
	}
	return ListOrder_LIST_ORDER_UNSPECIFIED
}

func (x *ListPublishersRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListPublishersRequest) GetOffset() int64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type ListPublishersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    uint64                 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Items         []*Publisher           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishersResponse) Reset() {
	*x = ListPublishersResponse{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishersResponse) ProtoMessage() {}

func (x *ListPublishersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishersResponse.ProtoReflect.Descriptor instead.
func (*ListPublishersResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{4}
}

func (x *ListPublishersResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPublishersResponse) GetItems() []*Publisher {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublisherRequest) Reset() {
	*x = GetPublisherRequest{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublisherRequest) ProtoMessage() {}

func (x *GetPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublisherRequest.ProtoReflect.Descriptor instead.
func (*GetPublisherRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{5}
}

func (x *GetPublisherRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Publisher             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublisherResponse) Reset() {
	*x = GetPublisherResponse{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublisherResponse) ProtoMessage() {}

func (x *GetPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublisherResponse.ProtoReflect.Descriptor instead.
func (*GetPublisherResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{6}
}

func (x *GetPublisherResponse) GetItem() *Publisher {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddPublisherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	WebUrl        string                 `protobuf:"bytes,3,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPublisherRequest) Reset() {
	*x = AddPublisherRequest{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublisherRequest) ProtoMessage() {}

func (x *AddPublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublisherRequest.ProtoReflect.Descriptor instead.
func (*AddPublisherRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{7}
}

func (x *AddPublisherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPublisherRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddPublisherRequest) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

type AddPublisherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Publisher             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPublisherResponse) Reset() {
	*x = AddPublisherResponse{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublisherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublisherResponse) ProtoMessage() {}

func (x *AddPublisherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublisherResponse.ProtoReflect.Descriptor instead.
func (*AddPublisherResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{8}
}

func (x *AddPublisherResponse) GetItem() *Publisher {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetPublishersForProcessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseHolder   string                 `protobuf:"bytes,1,opt,name=lease_holder,json=leaseHolder,proto3" json:"lease_holder,omitempty"`
	LeaseDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishersForProcessionRequest) Reset() {
	*x = GetPublishersForProcessionRequest{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishersForProcessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishersForProcessionRequest) ProtoMessage() {}

func (x *GetPublishersForProcessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishersForProcessionRequest.ProtoReflect.Descriptor instead.
func (*GetPublishersForProcessionRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{9}
}

func (x *GetPublishersForProcessionRequest) GetLeaseHolder() string {
	if x != nil {
		return x.LeaseHolder
	}
	return ""
}

func (x *GetPublishersForProcessionRequest) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

func (x *GetPublishersForProcessionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPublishersForProcessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Publisher           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishersForProcessionResponse) Reset() {
	*x = GetPublishersForProcessionResponse{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishersForProcessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishersForProcessionResponse) ProtoMessage() {}

func (x *GetPublishersForProcessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishersForProcessionResponse.ProtoReflect.Descriptor instead.
func (*GetPublishersForProcessionResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{10}
}

func (x *GetPublishersForProcessionResponse) GetItems() []*Publisher {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetPublishersOfLeaserHolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseHolder   string                 `protobuf:"bytes,1,opt,name=lease_holder,json=leaseHolder,proto3" json:"lease_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishersOfLeaserHolderRequest) Reset() {
	*x = GetPublishersOfLeaserHolderRequest{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishersOfLeaserHolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishersOfLeaserHolderRequest) ProtoMessage() {}

func (x *GetPublishersOfLeaserHolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishersOfLeaserHolderRequest.ProtoReflect.Descriptor instead.
func (*GetPublishersOfLeaserHolderRequest) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{11}
}

func (x *GetPublishersOfLeaserHolderRequest) GetLeaseHolder() string {
	if x != nil {
		return x.LeaseHolder
	}
	return ""
}

type GetPublishersOfLeaserHolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Publisher           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishersOfLeaserHolderResponse) Reset() {
	*x = GetPublishersOfLeaserHolderResponse{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishersOfLeaserHolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishersOfLeaserHolderResponse) ProtoMessage() {}

func (x *GetPublishersOfLeaserHolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishersOfLeaserHolderResponse.ProtoReflect.Descriptor instead.
func (*GetPublishersOfLeaserHolderResponse) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{12}
}

func (x *GetPublishersOfLeaserHolderResponse) GetItems() []*Publisher {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddPublisherRequest_Feed struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FeedType            FeedType               `protobuf:"varint,1,opt,name=feed_type,json=feedType,proto3,enum=exonex.cortex.v1alpha1.FeedType" json:"feed_type,omitempty"`
	Url                 string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PollIntervalSeconds *int32                 `protobuf:"varint,3,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3,oneof" json:"poll_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddPublisherRequest_Feed) Reset() {
	*x = AddPublisherRequest_Feed{}
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPublisherRequest_Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPublisherRequest_Feed) ProtoMessage() {}

func (x *AddPublisherRequest_Feed) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPublisherRequest_Feed.ProtoReflect.Descriptor instead.
func (*AddPublisherRequest_Feed) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP(), []int{7, 0}
}

func (x *AddPublisherRequest_Feed) GetFeedType() FeedType {
	if x != nil {
		return x.FeedType
	}
	return FeedType_FEED_TYPE_UNSPECIFIED
}

func (x *AddPublisherRequest_Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddPublisherRequest_Feed) GetPollIntervalSeconds() int32 {
	if x != nil && x.PollIntervalSeconds != nil {
		return *x.PollIntervalSeconds
	}
	return 0
}

var File_exonex_cortex_v1alpha1_publishers_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_publishers_proto_rawDesc = "" +
	"\n" +
	"'exonex/cortex/v1alpha1/publishers.proto\x12\x16exonex.cortex.v1alpha1\x1a#exonex/cortex/v1alpha1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb3\x04\n" +
	"\tPublisher\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".exonex.cortex.v1alpha1.ObjectMetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x17\n" +
	"\aweb_url\x18\x05 \x01(\tR\x06webUrl\x122\n" +
	"\x05feeds\x18\x06 \x03(\v2\x1c.exonex.cortex.v1alpha1.FeedR\x05feeds\x12I\n" +
	"\n" +
	"tdm_policy\x18\a \x01(\x0e2*.exonex.cortex.v1alpha1.PublisherTdmPolicyR\ttdmPolicy\x12V\n" +
	"\x12tdm_status_history\x18\b \x03(\v2(.exonex.cortex.v1alpha1.TdmPolicyHistoryR\x10tdmStatusHistory\x128\n" +
	"\x05lease\x18\t \x01(\v2\x1d.exonex.cortex.v1alpha1.LeaseH\x00R\x05lease\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06_lease\"\xc2\x03\n" +
	"\x04Feed\x12=\n" +
	"\tfeed_type\x18\x01 \x01(\x0e2 .exonex.cortex.v1alpha1.FeedTypeR\bfeedType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x127\n" +
	"\x15poll_interval_seconds\x18\x03 \x01(\x05H\x00R\x13pollIntervalSeconds\x88\x01\x01\x12E\n" +
	"\x0elast_polled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\flastPolledAt\x88\x01\x01\x12Z\n" +
	"\x19last_polled_last_modified\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x16lastPolledLastModified\x88\x01\x01\x12-\n" +
	"\x10last_polled_etag\x18\x06 \x01(\tH\x03R\x0elastPolledEtag\x88\x01\x01B\x18\n" +
	"\x16_poll_interval_secondsB\x11\n" +
	"\x0f_last_polled_atB\x1c\n" +
	"\x1a_last_polled_last_modifiedB\x13\n" +
	"\x11_last_polled_etag\"\xb9\x01\n" +
	"\x10TdmPolicyHistory\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12I\n" +
	"\n" +
	"tdm_policy\x18\x02 \x01(\x0e2*.exonex.cortex.v1alpha1.PublisherTdmPolicyR\ttdmPolicy\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf6\x01\n" +
	"\x15ListPublishersRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12@\n" +
	"\n" +
	"list_order\x18\x02 \x01(\x0e2!.exonex.cortex.v1alpha1.ListOrderR\tlistOrder\x12%\n" +
	"\x05limit\x18\x03 \x01(\x03B\n" +
	"\xbaH\a\"\x05\x18\xe8\a(\x01H\x00R\x05limit\x88\x01\x01\x12$\n" +
	"\x06offset\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"r\n" +
	"\x16ListPublishersResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x04R\n" +
	"totalCount\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.exonex.cortex.v1alpha1.PublisherR\x05items\"/\n" +
	"\x13GetPublisherRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"M\n" +
	"\x14GetPublisherResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.exonex.cortex.v1alpha1.PublisherR\x04item\"\x91\x02\n" +
	"\x13AddPublisherRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\aweb_url\x18\x03 \x01(\tR\x06webUrl\x1a\xaa\x01\n" +
	"\x04Feed\x12=\n" +
	"\tfeed_type\x18\x01 \x01(\x0e2 .exonex.cortex.v1alpha1.FeedTypeR\bfeedType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x127\n" +
	"\x15poll_interval_seconds\x18\x03 \x01(\x05H\x00R\x13pollIntervalSeconds\x88\x01\x01B\x18\n" +
	"\x16_poll_interval_seconds\"M\n" +
	"\x14AddPublisherResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.exonex.cortex.v1alpha1.PublisherR\x04item\"\xb8\x01\n" +
	"!GetPublishersForProcessionRequest\x12!\n" +
	"\flease_holder\x18\x01 \x01(\tR\vleaseHolder\x12Q\n" +
	"\x0elease_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x0f\xbaH\f\xaa\x01\t\"\x03\b\xd8\x042\x02\b<R\rleaseDuration\x12\x1d\n" +
	"\x05limit\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x05limit\"]\n" +
	"\"GetPublishersForProcessionResponse\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.exonex.cortex.v1alpha1.PublisherR\x05items\"G\n" +
	"\"GetPublishersOfLeaserHolderRequest\x12!\n" +
	"\flease_holder\x18\x01 \x01(\tR\vleaseHolder\"^\n" +
	"#GetPublishersOfLeaserHolderResponse\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.exonex.cortex.v1alpha1.PublisherR\x05items*~\n" +
	"\x12PublisherTdmPolicy\x12$\n" +
	" PUBLISHER_TDM_POLICY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPUBLISHER_TDM_POLICY_ALLOWED\x10\x01\x12 \n" +
	"\x1cPUBLISHER_TDM_POLICY_OPT_OUT\x10\x02*\x81\x01\n" +
	"\bFeedType\x12\x19\n" +
	"\x15FEED_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FEED_TYPE_HTML_SINGLE\x10\x01\x12\x18\n" +
	"\x14FEED_TYPE_HTML_CRAWL\x10\x02\x12\x11\n" +
	"\rFEED_TYPE_RSS\x10\x03\x12\x12\n" +
	"\x0eFEED_TYPE_ATOM\x10\x042\x92\x05\n" +
	"\x10PublisherService\x12q\n" +
	"\x0eListPublishers\x12-.exonex.cortex.v1alpha1.ListPublishersRequest\x1a..exonex.cortex.v1alpha1.ListPublishersResponse\"\x00\x12k\n" +
	"\fGetPublisher\x12+.exonex.cortex.v1alpha1.GetPublisherRequest\x1a,.exonex.cortex.v1alpha1.GetPublisherResponse\"\x00\x12k\n" +
	"\fAddPublisher\x12+.exonex.cortex.v1alpha1.AddPublisherRequest\x1a,.exonex.cortex.v1alpha1.AddPublisherResponse\"\x00\x12\x95\x01\n" +
	"\x1aGetPublishersForProcession\x129.exonex.cortex.v1alpha1.GetPublishersForProcessionRequest\x1a:.exonex.cortex.v1alpha1.GetPublishersForProcessionResponse\"\x00\x12\x98\x01\n" +
	"\x1bGetPublishersOfLeaserHolder\x12:.exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderRequest\x1a;.exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderResponse\"\x00B\xf5\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\x0fPublishersProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_publishers_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_publishers_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_publishers_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_publishers_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_publishers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_publishers_proto_rawDesc), len(file_exonex_cortex_v1alpha1_publishers_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_publishers_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_publishers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exonex_cortex_v1alpha1_publishers_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_exonex_cortex_v1alpha1_publishers_proto_goTypes = []any{
	(PublisherTdmPolicy)(0),                     // 0: exonex.cortex.v1alpha1.PublisherTdmPolicy
	(FeedType)(0),                               // 1: exonex.cortex.v1alpha1.FeedType
	(*Publisher)(nil),                           // 2: exonex.cortex.v1alpha1.Publisher
	(*Feed)(nil),                                // 3: exonex.cortex.v1alpha1.Feed
	(*TdmPolicyHistory)(nil),                    // 4: exonex.cortex.v1alpha1.TdmPolicyHistory
	(*ListPublishersRequest)(nil),               // 5: exonex.cortex.v1alpha1.ListPublishersRequest
	(*ListPublishersResponse)(nil),              // 6: exonex.cortex.v1alpha1.ListPublishersResponse
	(*GetPublisherRequest)(nil),                 // 7: exonex.cortex.v1alpha1.GetPublisherRequest
	(*GetPublisherResponse)(nil),                // 8: exonex.cortex.v1alpha1.GetPublisherResponse
	(*AddPublisherRequest)(nil),                 // 9: exonex.cortex.v1alpha1.AddPublisherRequest
	(*AddPublisherResponse)(nil),                // 10: exonex.cortex.v1alpha1.AddPublisherResponse
	(*GetPublishersForProcessionRequest)(nil),   // 11: exonex.cortex.v1alpha1.GetPublishersForProcessionRequest
	(*GetPublishersForProcessionResponse)(nil),  // 12: exonex.cortex.v1alpha1.GetPublishersForProcessionResponse
	(*GetPublishersOfLeaserHolderRequest)(nil),  // 13: exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderRequest
	(*GetPublishersOfLeaserHolderResponse)(nil), // 14: exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderResponse
	(*AddPublisherRequest_Feed)(nil),            // 15: exonex.cortex.v1alpha1.AddPublisherRequest.Feed
	(*ObjectMeta)(nil),                          // 16: exonex.cortex.v1alpha1.ObjectMeta
	(*Lease)(nil),                               // 17: exonex.cortex.v1alpha1.Lease
	(*timestamppb.Timestamp)(nil),               // 18: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),               // 19: google.protobuf.FieldMask
	(ListOrder)(0),                              // 20: exonex.cortex.v1alpha1.ListOrder
	(*durationpb.Duration)(nil),                 // 21: google.protobuf.Duration
}
var file_exonex_cortex_v1alpha1_publishers_proto_depIdxs = []int32{
	16, // 0: exonex.cortex.v1alpha1.Publisher.meta:type_name -> exonex.cortex.v1alpha1.ObjectMeta
	3,  // 1: exonex.cortex.v1alpha1.Publisher.feeds:type_name -> exonex.cortex.v1alpha1.Feed
	0,  // 2: exonex.cortex.v1alpha1.Publisher.tdm_policy:type_name -> exonex.cortex.v1alpha1.PublisherTdmPolicy
	4,  // 3: exonex.cortex.v1alpha1.Publisher.tdm_status_history:type_name -> exonex.cortex.v1alpha1.TdmPolicyHistory
	17, // 4: exonex.cortex.v1alpha1.Publisher.lease:type_name -> exonex.cortex.v1alpha1.Lease
	18, // 5: exonex.cortex.v1alpha1.Publisher.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: exonex.cortex.v1alpha1.Publisher.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: exonex.cortex.v1alpha1.Feed.feed_type:type_name -> exonex.cortex.v1alpha1.FeedType
	18, // 8: exonex.cortex.v1alpha1.Feed.last_polled_at:type_name -> google.protobuf.Timestamp
	18, // 9: exonex.cortex.v1alpha1.Feed.last_polled_last_modified:type_name -> google.protobuf.Timestamp
	0,  // 10: exonex.cortex.v1alpha1.TdmPolicyHistory.tdm_policy:type_name -> exonex.cortex.v1alpha1.PublisherTdmPolicy
	18, // 11: exonex.cortex.v1alpha1.TdmPolicyHistory.created_at:type_name -> google.protobuf.Timestamp
	19, // 12: exonex.cortex.v1alpha1.ListPublishersRequest.field_mask:type_name -> google.protobuf.FieldMask
	20, // 13: exonex.cortex.v1alpha1.ListPublishersRequest.list_order:type_name -> exonex.cortex.v1alpha1.ListOrder
	2,  // 14: exonex.cortex.v1alpha1.ListPublishersResponse.items:type_name -> exonex.cortex.v1alpha1.Publisher
	2,  // 15: exonex.cortex.v1alpha1.GetPublisherResponse.item:type_name -> exonex.cortex.v1alpha1.Publisher
	2,  // 16: exonex.cortex.v1alpha1.AddPublisherResponse.item:type_name -> exonex.cortex.v1alpha1.Publisher
	21, // 17: exonex.cortex.v1alpha1.GetPublishersForProcessionRequest.lease_duration:type_name -> google.protobuf.Duration
	2,  // 18: exonex.cortex.v1alpha1.GetPublishersForProcessionResponse.items:type_name -> exonex.cortex.v1alpha1.Publisher
	2,  // 19: exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderResponse.items:type_name -> exonex.cortex.v1alpha1.Publisher
	1,  // 20: exonex.cortex.v1alpha1.AddPublisherRequest.Feed.feed_type:type_name -> exonex.cortex.v1alpha1.FeedType
	5,  // 21: exonex.cortex.v1alpha1.PublisherService.ListPublishers:input_type -> exonex.cortex.v1alpha1.ListPublishersRequest
	7,  // 22: exonex.cortex.v1alpha1.PublisherService.GetPublisher:input_type -> exonex.cortex.v1alpha1.GetPublisherRequest
	9,  // 23: exonex.cortex.v1alpha1.PublisherService.AddPublisher:input_type -> exonex.cortex.v1alpha1.AddPublisherRequest
	11, // 24: exonex.cortex.v1alpha1.PublisherService.GetPublishersForProcession:input_type -> exonex.cortex.v1alpha1.GetPublishersForProcessionRequest
	13, // 25: exonex.cortex.v1alpha1.PublisherService.GetPublishersOfLeaserHolder:input_type -> exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderRequest
	6,  // 26: exonex.cortex.v1alpha1.PublisherService.ListPublishers:output_type -> exonex.cortex.v1alpha1.ListPublishersResponse
	8,  // 27: exonex.cortex.v1alpha1.PublisherService.GetPublisher:output_type -> exonex.cortex.v1alpha1.GetPublisherResponse
	10, // 28: exonex.cortex.v1alpha1.PublisherService.AddPublisher:output_type -> exonex.cortex.v1alpha1.AddPublisherResponse
	12, // 29: exonex.cortex.v1alpha1.PublisherService.GetPublishersForProcession:output_type -> exonex.cortex.v1alpha1.GetPublishersForProcessionResponse
	14, // 30: exonex.cortex.v1alpha1.PublisherService.GetPublishersOfLeaserHolder:output_type -> exonex.cortex.v1alpha1.GetPublishersOfLeaserHolderResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_publishers_proto_init() }
func file_exonex_cortex_v1alpha1_publishers_proto_init() {
	if File_exonex_cortex_v1alpha1_publishers_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_common_proto_init()
	file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[1].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[3].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_publishers_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_publishers_proto_rawDesc), len(file_exonex_cortex_v1alpha1_publishers_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_publishers_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_publishers_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_publishers_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_publishers_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_publishers_proto = out.File
	file_exonex_cortex_v1alpha1_publishers_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_publishers_proto_depIdxs = nil
}
