// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/publisher.proto

package cortexv1alpha1

import (
	v1 "github.com/alexzimmer96/exonex/pkg/api/exonex/api/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Publisher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// General metadata about the Resource.
	Meta *v1.ResourceMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// The UUID that is used to uniquely identify the Publisher.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The canonical name of the Publisher.
	CanonicalName string `protobuf:"bytes,3,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	// Alias names under which the Publisher is also known.
	NameAliases []string `protobuf:"bytes,4,rep,name=name_aliases,json=nameAliases,proto3" json:"name_aliases,omitempty"`
	// Annotations are small chunks of information that are added to a Document and can be queried.
	// They are stored as JSON object that is
	Annotations   *structpb.Struct `protobuf:"bytes,5,opt,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Publisher) Reset() {
	*x = Publisher{}
	mi := &file_exonex_cortex_v1alpha1_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Publisher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publisher) ProtoMessage() {}

func (x *Publisher) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publisher.ProtoReflect.Descriptor instead.
func (*Publisher) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *Publisher) GetMeta() *v1.ResourceMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Publisher) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Publisher) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *Publisher) GetNameAliases() []string {
	if x != nil {
		return x.NameAliases
	}
	return nil
}

func (x *Publisher) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_exonex_cortex_v1alpha1_publisher_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_publisher_proto_rawDesc = "" +
	"\n" +
	"&exonex/cortex/v1alpha1/publisher.proto\x12\x16exonex.cortex.v1alpha1\x1a\x18exonex/api/v1/meta.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xab\x02\n" +
	"\tPublisher\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.exonex.api.v1.ResourceMetaR\x04meta\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\bR\x02id\x12%\n" +
	"\x0ecanonical_name\x18\x03 \x01(\tR\rcanonicalName\x12!\n" +
	"\fname_aliases\x18\x04 \x03(\tR\vnameAliases\x12>\n" +
	"\vannotations\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x03R\vannotations:N\xeaAK\n" +
	"\x1acortex.exonex.io/Publisher\x12\x16publishers/{publisher}*\n" +
	"publishers2\tpublisherB\xf4\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\x0ePublisherProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_publisher_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_publisher_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_publisher_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_publisher_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_publisher_proto_rawDesc), len(file_exonex_cortex_v1alpha1_publisher_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_publisher_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exonex_cortex_v1alpha1_publisher_proto_goTypes = []any{
	(*Publisher)(nil),       // 0: exonex.cortex.v1alpha1.Publisher
	(*v1.ResourceMeta)(nil), // 1: exonex.api.v1.ResourceMeta
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_exonex_cortex_v1alpha1_publisher_proto_depIdxs = []int32{
	1, // 0: exonex.cortex.v1alpha1.Publisher.meta:type_name -> exonex.api.v1.ResourceMeta
	2, // 1: exonex.cortex.v1alpha1.Publisher.annotations:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_publisher_proto_init() }
func file_exonex_cortex_v1alpha1_publisher_proto_init() {
	if File_exonex_cortex_v1alpha1_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_publisher_proto_rawDesc), len(file_exonex_cortex_v1alpha1_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_publisher_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_publisher_proto_depIdxs,
		MessageInfos:      file_exonex_cortex_v1alpha1_publisher_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_publisher_proto = out.File
	file_exonex_cortex_v1alpha1_publisher_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_publisher_proto_depIdxs = nil
}
