// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/cortex/v1alpha1/scraping.proto

package cortexv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeTrigger int32

const (
	ScrapeTrigger_SCRAPE_TRIGGER_UNSPECIFIED ScrapeTrigger = 0
	ScrapeTrigger_SCRAPE_TRIGGER_FEED        ScrapeTrigger = 1
	ScrapeTrigger_SCRAPE_TRIGGER_CRAWL       ScrapeTrigger = 2
	ScrapeTrigger_SCRAPE_TRIGGER_MANUAL      ScrapeTrigger = 3
)

// Enum value maps for ScrapeTrigger.
var (
	ScrapeTrigger_name = map[int32]string{
		0: "SCRAPE_TRIGGER_UNSPECIFIED",
		1: "SCRAPE_TRIGGER_FEED",
		2: "SCRAPE_TRIGGER_CRAWL",
		3: "SCRAPE_TRIGGER_MANUAL",
	}
	ScrapeTrigger_value = map[string]int32{
		"SCRAPE_TRIGGER_UNSPECIFIED": 0,
		"SCRAPE_TRIGGER_FEED":        1,
		"SCRAPE_TRIGGER_CRAWL":       2,
		"SCRAPE_TRIGGER_MANUAL":      3,
	}
)

func (x ScrapeTrigger) Enum() *ScrapeTrigger {
	p := new(ScrapeTrigger)
	*p = x
	return p
}

func (x ScrapeTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScrapeTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_cortex_v1alpha1_scraping_proto_enumTypes[0].Descriptor()
}

func (ScrapeTrigger) Type() protoreflect.EnumType {
	return &file_exonex_cortex_v1alpha1_scraping_proto_enumTypes[0]
}

func (x ScrapeTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScrapeTrigger.Descriptor instead.
func (ScrapeTrigger) EnumDescriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_scraping_proto_rawDescGZIP(), []int{0}
}

// A ScrapeOrder is a concrete order to scrape one web resource and save it as a Document.
type ScrapeOrder struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta             *ObjectMeta            `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	PublisherId      string                 `protobuf:"bytes,3,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Trigger          ScrapeTrigger          `protobuf:"varint,5,opt,name=trigger,proto3,enum=exonex.cortex.v1alpha1.ScrapeTrigger" json:"trigger,omitempty"`
	TriggerReference *string                `protobuf:"bytes,6,opt,name=trigger_reference,json=triggerReference,proto3,oneof" json:"trigger_reference,omitempty"`
	Lease            *Lease                 `protobuf:"bytes,7,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	ScrapeResult     *ScrapeOrderResult     `protobuf:"bytes,8,opt,name=scrape_result,json=scrapeResult,proto3,oneof" json:"scrape_result,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScrapeOrder) Reset() {
	*x = ScrapeOrder{}
	mi := &file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeOrder) ProtoMessage() {}

func (x *ScrapeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeOrder.ProtoReflect.Descriptor instead.
func (*ScrapeOrder) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_scraping_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScrapeOrder) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ScrapeOrder) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

func (x *ScrapeOrder) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapeOrder) GetTrigger() ScrapeTrigger {
	if x != nil {
		return x.Trigger
	}
	return ScrapeTrigger_SCRAPE_TRIGGER_UNSPECIFIED
}

func (x *ScrapeOrder) GetTriggerReference() string {
	if x != nil && x.TriggerReference != nil {
		return *x.TriggerReference
	}
	return ""
}

func (x *ScrapeOrder) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *ScrapeOrder) GetScrapeResult() *ScrapeOrderResult {
	if x != nil {
		return x.ScrapeResult
	}
	return nil
}

func (x *ScrapeOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// A ScrapeOrderResult tracks metadata to a ScrapeOrder.
// It is typically present after the Order has been executed.
type ScrapeOrderResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status OrderStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=exonex.cortex.v1alpha1.OrderStatus" json:"status,omitempty"`
	// The status_reason field can be used to add additional context on why the ScrapeOrderResult is in the
	// current OrderStatus.
	StatusReason  *string                `protobuf:"bytes,2,opt,name=status_reason,json=statusReason,proto3,oneof" json:"status_reason,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeOrderResult) Reset() {
	*x = ScrapeOrderResult{}
	mi := &file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeOrderResult) ProtoMessage() {}

func (x *ScrapeOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeOrderResult.ProtoReflect.Descriptor instead.
func (*ScrapeOrderResult) Descriptor() ([]byte, []int) {
	return file_exonex_cortex_v1alpha1_scraping_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeOrderResult) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ScrapeOrderResult) GetStatusReason() string {
	if x != nil && x.StatusReason != nil {
		return *x.StatusReason
	}
	return ""
}

func (x *ScrapeOrderResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ScrapeOrderResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_exonex_cortex_v1alpha1_scraping_proto protoreflect.FileDescriptor

const file_exonex_cortex_v1alpha1_scraping_proto_rawDesc = "" +
	"\n" +
	"%exonex/cortex/v1alpha1/scraping.proto\x12\x16exonex.cortex.v1alpha1\x1a#exonex/cortex/v1alpha1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x03\n" +
	"\vScrapeOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04meta\x18\x02 \x01(\v2\".exonex.cortex.v1alpha1.ObjectMetaR\x04meta\x12!\n" +
	"\fpublisher_id\x18\x03 \x01(\tR\vpublisherId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12?\n" +
	"\atrigger\x18\x05 \x01(\x0e2%.exonex.cortex.v1alpha1.ScrapeTriggerR\atrigger\x120\n" +
	"\x11trigger_reference\x18\x06 \x01(\tH\x00R\x10triggerReference\x88\x01\x01\x128\n" +
	"\x05lease\x18\a \x01(\v2\x1d.exonex.cortex.v1alpha1.LeaseH\x01R\x05lease\x88\x01\x01\x12S\n" +
	"\rscrape_result\x18\b \x01(\v2).exonex.cortex.v1alpha1.ScrapeOrderResultH\x02R\fscrapeResult\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x14\n" +
	"\x12_trigger_referenceB\b\n" +
	"\x06_leaseB\x10\n" +
	"\x0e_scrape_result\"\xea\x01\n" +
	"\x11ScrapeOrderResult\x12;\n" +
	"\x06status\x18\x01 \x01(\x0e2#.exonex.cortex.v1alpha1.OrderStatusR\x06status\x12(\n" +
	"\rstatus_reason\x18\x02 \x01(\tH\x00R\fstatusReason\x88\x01\x01\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAtB\x10\n" +
	"\x0e_status_reason*}\n" +
	"\rScrapeTrigger\x12\x1e\n" +
	"\x1aSCRAPE_TRIGGER_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SCRAPE_TRIGGER_FEED\x10\x01\x12\x18\n" +
	"\x14SCRAPE_TRIGGER_CRAWL\x10\x02\x12\x19\n" +
	"\x15SCRAPE_TRIGGER_MANUAL\x10\x03B\xf3\x01\n" +
	"\x1acom.exonex.cortex.v1alpha1B\rScrapingProtoP\x01ZLgithub.com/alexzimmer96/exonex/pkg/api/exonex/cortex/v1alpha1;cortexv1alpha1\xa2\x02\x03ECX\xaa\x02\x16Exonex.Cortex.V1alpha1\xca\x02\x16Exonex\\Cortex\\V1alpha1\xe2\x02\"Exonex\\Cortex\\V1alpha1\\GPBMetadata\xea\x02\x18Exonex::Cortex::V1alpha1b\x06proto3"

var (
	file_exonex_cortex_v1alpha1_scraping_proto_rawDescOnce sync.Once
	file_exonex_cortex_v1alpha1_scraping_proto_rawDescData []byte
)

func file_exonex_cortex_v1alpha1_scraping_proto_rawDescGZIP() []byte {
	file_exonex_cortex_v1alpha1_scraping_proto_rawDescOnce.Do(func() {
		file_exonex_cortex_v1alpha1_scraping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_scraping_proto_rawDesc), len(file_exonex_cortex_v1alpha1_scraping_proto_rawDesc)))
	})
	return file_exonex_cortex_v1alpha1_scraping_proto_rawDescData
}

var file_exonex_cortex_v1alpha1_scraping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exonex_cortex_v1alpha1_scraping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exonex_cortex_v1alpha1_scraping_proto_goTypes = []any{
	(ScrapeTrigger)(0),            // 0: exonex.cortex.v1alpha1.ScrapeTrigger
	(*ScrapeOrder)(nil),           // 1: exonex.cortex.v1alpha1.ScrapeOrder
	(*ScrapeOrderResult)(nil),     // 2: exonex.cortex.v1alpha1.ScrapeOrderResult
	(*ObjectMeta)(nil),            // 3: exonex.cortex.v1alpha1.ObjectMeta
	(*Lease)(nil),                 // 4: exonex.cortex.v1alpha1.Lease
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(OrderStatus)(0),              // 6: exonex.cortex.v1alpha1.OrderStatus
}
var file_exonex_cortex_v1alpha1_scraping_proto_depIdxs = []int32{
	3, // 0: exonex.cortex.v1alpha1.ScrapeOrder.meta:type_name -> exonex.cortex.v1alpha1.ObjectMeta
	0, // 1: exonex.cortex.v1alpha1.ScrapeOrder.trigger:type_name -> exonex.cortex.v1alpha1.ScrapeTrigger
	4, // 2: exonex.cortex.v1alpha1.ScrapeOrder.lease:type_name -> exonex.cortex.v1alpha1.Lease
	2, // 3: exonex.cortex.v1alpha1.ScrapeOrder.scrape_result:type_name -> exonex.cortex.v1alpha1.ScrapeOrderResult
	5, // 4: exonex.cortex.v1alpha1.ScrapeOrder.created_at:type_name -> google.protobuf.Timestamp
	6, // 5: exonex.cortex.v1alpha1.ScrapeOrderResult.status:type_name -> exonex.cortex.v1alpha1.OrderStatus
	5, // 6: exonex.cortex.v1alpha1.ScrapeOrderResult.finished_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_exonex_cortex_v1alpha1_scraping_proto_init() }
func file_exonex_cortex_v1alpha1_scraping_proto_init() {
	if File_exonex_cortex_v1alpha1_scraping_proto != nil {
		return
	}
	file_exonex_cortex_v1alpha1_common_proto_init()
	file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[0].OneofWrappers = []any{}
	file_exonex_cortex_v1alpha1_scraping_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_cortex_v1alpha1_scraping_proto_rawDesc), len(file_exonex_cortex_v1alpha1_scraping_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_cortex_v1alpha1_scraping_proto_goTypes,
		DependencyIndexes: file_exonex_cortex_v1alpha1_scraping_proto_depIdxs,
		EnumInfos:         file_exonex_cortex_v1alpha1_scraping_proto_enumTypes,
		MessageInfos:      file_exonex_cortex_v1alpha1_scraping_proto_msgTypes,
	}.Build()
	File_exonex_cortex_v1alpha1_scraping_proto = out.File
	file_exonex_cortex_v1alpha1_scraping_proto_goTypes = nil
	file_exonex_cortex_v1alpha1_scraping_proto_depIdxs = nil
}
