//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type Artifacts struct {
	ID           uuid.UUID `sql:"primary_key"`
	Annotations  string
	Finalizers   pq.StringArray
	ArtifactType string
	DocumentID   uuid.UUID
	Name         string
	Payload      string
	Version      int64
	CreatedAt    time.Time `sql:"primary_key"`
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}
