//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type Documents struct {
	ID                  uuid.UUID `sql:"primary_key"`
	Annotations         string
	Finalizers          pq.StringArray
	PublisherID         uuid.UUID
	FileUploadCompleted bool
	FileMimeType        string
	FileSizeBytes       *int64
	FileStorageVolume   string
	FileStorageKey      string
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
}
