//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ArtifactTypes = newArtifactTypesTable("cortex", "artifact_types", "")

type artifactTypesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Annotations postgres.ColumnString
	Finalizers  postgres.ColumnStringArray
	APIGroup    postgres.ColumnString
	APIKind     postgres.ColumnString
	APIVersion  postgres.ColumnString
	Deprecated  postgres.ColumnBool
	Name        postgres.ColumnString
	Description postgres.ColumnString
	Schema      postgres.ColumnString
	Version     postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz
	DeletedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ArtifactTypesTable struct {
	artifactTypesTable

	EXCLUDED artifactTypesTable
}

// AS creates new ArtifactTypesTable with assigned alias
func (a ArtifactTypesTable) AS(alias string) *ArtifactTypesTable {
	return newArtifactTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtifactTypesTable with assigned schema name
func (a ArtifactTypesTable) FromSchema(schemaName string) *ArtifactTypesTable {
	return newArtifactTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtifactTypesTable with assigned table prefix
func (a ArtifactTypesTable) WithPrefix(prefix string) *ArtifactTypesTable {
	return newArtifactTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtifactTypesTable with assigned table suffix
func (a ArtifactTypesTable) WithSuffix(suffix string) *ArtifactTypesTable {
	return newArtifactTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtifactTypesTable(schemaName, tableName, alias string) *ArtifactTypesTable {
	return &ArtifactTypesTable{
		artifactTypesTable: newArtifactTypesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newArtifactTypesTableImpl("", "excluded", ""),
	}
}

func newArtifactTypesTableImpl(schemaName, tableName, alias string) artifactTypesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		AnnotationsColumn = postgres.StringColumn("annotations")
		FinalizersColumn  = postgres.StringArrayColumn("finalizers")
		APIGroupColumn    = postgres.StringColumn("api_group")
		APIKindColumn     = postgres.StringColumn("api_kind")
		APIVersionColumn  = postgres.StringColumn("api_version")
		DeprecatedColumn  = postgres.BoolColumn("deprecated")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		SchemaColumn      = postgres.StringColumn("schema")
		VersionColumn     = postgres.IntegerColumn("version")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn   = postgres.TimestampzColumn("deleted_at")
		allColumns        = postgres.ColumnList{IDColumn, AnnotationsColumn, FinalizersColumn, APIGroupColumn, APIKindColumn, APIVersionColumn, DeprecatedColumn, NameColumn, DescriptionColumn, SchemaColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns    = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, APIGroupColumn, APIKindColumn, APIVersionColumn, DeprecatedColumn, NameColumn, DescriptionColumn, SchemaColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns    = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, DeprecatedColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return artifactTypesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Annotations: AnnotationsColumn,
		Finalizers:  FinalizersColumn,
		APIGroup:    APIGroupColumn,
		APIKind:     APIKindColumn,
		APIVersion:  APIVersionColumn,
		Deprecated:  DeprecatedColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		Schema:      SchemaColumn,
		Version:     VersionColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		DeletedAt:   DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
