//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Documents = newDocumentsTable("cortex", "documents", "")

type documentsTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	Annotations         postgres.ColumnString
	Finalizers          postgres.ColumnStringArray
	PublisherID         postgres.ColumnString
	FileUploadCompleted postgres.ColumnBool
	FileMimeType        postgres.ColumnString
	FileSizeBytes       postgres.ColumnInteger
	FileStorageVolume   postgres.ColumnString
	FileStorageKey      postgres.ColumnString
	Version             postgres.ColumnInteger
	CreatedAt           postgres.ColumnTimestampz
	UpdatedAt           postgres.ColumnTimestampz
	DeletedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type DocumentsTable struct {
	documentsTable

	EXCLUDED documentsTable
}

// AS creates new DocumentsTable with assigned alias
func (a DocumentsTable) AS(alias string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DocumentsTable with assigned schema name
func (a DocumentsTable) FromSchema(schemaName string) *DocumentsTable {
	return newDocumentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DocumentsTable with assigned table prefix
func (a DocumentsTable) WithPrefix(prefix string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DocumentsTable with assigned table suffix
func (a DocumentsTable) WithSuffix(suffix string) *DocumentsTable {
	return newDocumentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDocumentsTable(schemaName, tableName, alias string) *DocumentsTable {
	return &DocumentsTable{
		documentsTable: newDocumentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newDocumentsTableImpl("", "excluded", ""),
	}
}

func newDocumentsTableImpl(schemaName, tableName, alias string) documentsTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		AnnotationsColumn         = postgres.StringColumn("annotations")
		FinalizersColumn          = postgres.StringArrayColumn("finalizers")
		PublisherIDColumn         = postgres.StringColumn("publisher_id")
		FileUploadCompletedColumn = postgres.BoolColumn("file_upload_completed")
		FileMimeTypeColumn        = postgres.StringColumn("file_mime_type")
		FileSizeBytesColumn       = postgres.IntegerColumn("file_size_bytes")
		FileStorageVolumeColumn   = postgres.StringColumn("file_storage_volume")
		FileStorageKeyColumn      = postgres.StringColumn("file_storage_key")
		VersionColumn             = postgres.IntegerColumn("version")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn           = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn           = postgres.TimestampzColumn("deleted_at")
		allColumns                = postgres.ColumnList{IDColumn, AnnotationsColumn, FinalizersColumn, PublisherIDColumn, FileUploadCompletedColumn, FileMimeTypeColumn, FileSizeBytesColumn, FileStorageVolumeColumn, FileStorageKeyColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns            = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, PublisherIDColumn, FileUploadCompletedColumn, FileMimeTypeColumn, FileSizeBytesColumn, FileStorageVolumeColumn, FileStorageKeyColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns            = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, FileUploadCompletedColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return documentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		Annotations:         AnnotationsColumn,
		Finalizers:          FinalizersColumn,
		PublisherID:         PublisherIDColumn,
		FileUploadCompleted: FileUploadCompletedColumn,
		FileMimeType:        FileMimeTypeColumn,
		FileSizeBytes:       FileSizeBytesColumn,
		FileStorageVolume:   FileStorageVolumeColumn,
		FileStorageKey:      FileStorageKeyColumn,
		Version:             VersionColumn,
		CreatedAt:           CreatedAtColumn,
		UpdatedAt:           UpdatedAtColumn,
		DeletedAt:           DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
