//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Publishers = newPublishersTable("cortex", "publishers", "")

type publishersTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	Annotations   postgres.ColumnString
	Finalizers    postgres.ColumnStringArray
	CanonicalName postgres.ColumnString
	Version       postgres.ColumnInteger
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz
	DeletedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PublishersTable struct {
	publishersTable

	EXCLUDED publishersTable
}

// AS creates new PublishersTable with assigned alias
func (a PublishersTable) AS(alias string) *PublishersTable {
	return newPublishersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PublishersTable with assigned schema name
func (a PublishersTable) FromSchema(schemaName string) *PublishersTable {
	return newPublishersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PublishersTable with assigned table prefix
func (a PublishersTable) WithPrefix(prefix string) *PublishersTable {
	return newPublishersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PublishersTable with assigned table suffix
func (a PublishersTable) WithSuffix(suffix string) *PublishersTable {
	return newPublishersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPublishersTable(schemaName, tableName, alias string) *PublishersTable {
	return &PublishersTable{
		publishersTable: newPublishersTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newPublishersTableImpl("", "excluded", ""),
	}
}

func newPublishersTableImpl(schemaName, tableName, alias string) publishersTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		AnnotationsColumn   = postgres.StringColumn("annotations")
		FinalizersColumn    = postgres.StringArrayColumn("finalizers")
		CanonicalNameColumn = postgres.StringColumn("canonical_name")
		VersionColumn       = postgres.IntegerColumn("version")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn     = postgres.TimestampzColumn("deleted_at")
		allColumns          = postgres.ColumnList{IDColumn, AnnotationsColumn, FinalizersColumn, CanonicalNameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns      = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, CanonicalNameColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns      = postgres.ColumnList{AnnotationsColumn, FinalizersColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return publishersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		Annotations:   AnnotationsColumn,
		Finalizers:    FinalizersColumn,
		CanonicalName: CanonicalNameColumn,
		Version:       VersionColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		DeletedAt:     DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
