// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/api/v1/annotations.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_ANNOTATIONS FieldType = 1
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_ANNOTATIONS",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_ANNOTATIONS": 1,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_exonex_api_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_exonex_api_v1_annotations_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_exonex_api_v1_annotations_proto_rawDescGZIP(), []int{0}
}

var file_exonex_api_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "exonex.api.v1.method_permission",
		Tag:           "bytes,50001,opt,name=method_permission",
		Filename:      "exonex/api/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "exonex.api.v1.field_read_permission",
		Tag:           "bytes,50001,opt,name=field_read_permission",
		Filename:      "exonex/api/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "exonex.api.v1.field_update_permission",
		Tag:           "bytes,50002,opt,name=field_update_permission",
		Filename:      "exonex/api/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldType)(nil),
		Field:         50003,
		Name:          "exonex.api.v1.field_type",
		Tag:           "varint,50003,opt,name=field_type,enum=exonex.api.v1.FieldType",
		Filename:      "exonex/api/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string method_permission = 50001;
	E_MethodPermission = &file_exonex_api_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// The field_read_permission annotation defines the required permission to read a field during a list- or get operation.
	// If the permission is defined and the caller does not have the required permissions, the field is excluded
	// from the response by setting it to either its zero value (for non-optional fields) or to null.
	//
	// optional string field_read_permission = 50001;
	E_FieldReadPermission = &file_exonex_api_v1_annotations_proto_extTypes[1]
	// The field_update_permission annotation defines the required permission to update a field using a Update operation.
	// If the permission is defined and the caller does not have the required permissions, a PERMISSION_DENIED
	// error will be returned.
	//
	// optional string field_update_permission = 50002;
	E_FieldUpdatePermission = &file_exonex_api_v1_annotations_proto_extTypes[2]
	// The field_type annotation can be used to define a custom field_type that results in a special treatment on field
	// updates.
	//
	// optional exonex.api.v1.FieldType field_type = 50003;
	E_FieldType = &file_exonex_api_v1_annotations_proto_extTypes[3]
)

var File_exonex_api_v1_annotations_proto protoreflect.FileDescriptor

const file_exonex_api_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1fexonex/api/v1/annotations.proto\x12\rexonex.api.v1\x1a google/protobuf/descriptor.proto*C\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FIELD_TYPE_ANNOTATIONS\x10\x01:M\n" +
	"\x11method_permission\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x10methodPermission:V\n" +
	"\x15field_read_permission\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\x13fieldReadPermission\x88\x01\x01:Z\n" +
	"\x17field_update_permission\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\tR\x15fieldUpdatePermission\x88\x01\x01:[\n" +
	"\n" +
	"field_type\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\x0e2\x18.exonex.api.v1.FieldTypeR\tfieldType\x88\x01\x01B\xb7\x01\n" +
	"\x11com.exonex.api.v1B\x10AnnotationsProtoP\x01Z:github.com/alexzimmer96/exonex/pkg/api/exonex/api/v1;apiv1\xa2\x02\x03EAX\xaa\x02\rExonex.Api.V1\xca\x02\rExonex\\Api\\V1\xe2\x02\x19Exonex\\Api\\V1\\GPBMetadata\xea\x02\x0fExonex::Api::V1b\x06proto3"

var (
	file_exonex_api_v1_annotations_proto_rawDescOnce sync.Once
	file_exonex_api_v1_annotations_proto_rawDescData []byte
)

func file_exonex_api_v1_annotations_proto_rawDescGZIP() []byte {
	file_exonex_api_v1_annotations_proto_rawDescOnce.Do(func() {
		file_exonex_api_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_api_v1_annotations_proto_rawDesc), len(file_exonex_api_v1_annotations_proto_rawDesc)))
	})
	return file_exonex_api_v1_annotations_proto_rawDescData
}

var file_exonex_api_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exonex_api_v1_annotations_proto_goTypes = []any{
	(FieldType)(0),                     // 0: exonex.api.v1.FieldType
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 2: google.protobuf.FieldOptions
}
var file_exonex_api_v1_annotations_proto_depIdxs = []int32{
	1, // 0: exonex.api.v1.method_permission:extendee -> google.protobuf.MethodOptions
	2, // 1: exonex.api.v1.field_read_permission:extendee -> google.protobuf.FieldOptions
	2, // 2: exonex.api.v1.field_update_permission:extendee -> google.protobuf.FieldOptions
	2, // 3: exonex.api.v1.field_type:extendee -> google.protobuf.FieldOptions
	0, // 4: exonex.api.v1.field_type:type_name -> exonex.api.v1.FieldType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exonex_api_v1_annotations_proto_init() }
func file_exonex_api_v1_annotations_proto_init() {
	if File_exonex_api_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_api_v1_annotations_proto_rawDesc), len(file_exonex_api_v1_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_exonex_api_v1_annotations_proto_goTypes,
		DependencyIndexes: file_exonex_api_v1_annotations_proto_depIdxs,
		EnumInfos:         file_exonex_api_v1_annotations_proto_enumTypes,
		ExtensionInfos:    file_exonex_api_v1_annotations_proto_extTypes,
	}.Build()
	File_exonex_api_v1_annotations_proto = out.File
	file_exonex_api_v1_annotations_proto_goTypes = nil
	file_exonex_api_v1_annotations_proto_depIdxs = nil
}
