// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: exonex/api/v1/meta.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotations are small chunks of information that are added to a Resource and can be queried.
	// They are stored as a flat JSON object.
	Annotations *structpb.Struct `protobuf:"bytes,1,opt,name=annotations,proto3" json:"annotations,omitempty"`
	// Finalizers are indicators that certain background actions for a Resource must be performed before the
	// Resource resource can be finally deleted from the Database.
	Finalizers []string `protobuf:"bytes,2,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	// An increasing counter that is used for optimistic concurrency locking.
	Version int64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// The time this Resource has been created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// The time this Resource has been updated the last time.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The time this Resource has been marked for deletion.
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMeta) Reset() {
	*x = ResourceMeta{}
	mi := &file_exonex_api_v1_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMeta) ProtoMessage() {}

func (x *ResourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_exonex_api_v1_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMeta.ProtoReflect.Descriptor instead.
func (*ResourceMeta) Descriptor() ([]byte, []int) {
	return file_exonex_api_v1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceMeta) GetAnnotations() *structpb.Struct {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ResourceMeta) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *ResourceMeta) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResourceMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResourceMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ResourceMeta) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_exonex_api_v1_meta_proto protoreflect.FileDescriptor

const file_exonex_api_v1_meta_proto_rawDesc = "" +
	"\n" +
	"\x18exonex/api/v1/meta.proto\x12\rexonex.api.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xe6\x02\n" +
	"\fResourceMeta\x12>\n" +
	"\vannotations\x18\x01 \x01(\v2\x17.google.protobuf.StructB\x03\xe0A\x03R\vannotations\x12#\n" +
	"\n" +
	"finalizers\x18\x02 \x03(\tB\x03\xe0A\x03R\n" +
	"finalizers\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x03B\x03\xe0A\x03R\aversion\x12>\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12C\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_atB\xb0\x01\n" +
	"\x11com.exonex.api.v1B\tMetaProtoP\x01Z:github.com/alexzimmer96/exonex/pkg/api/exonex/api/v1;apiv1\xa2\x02\x03EAX\xaa\x02\rExonex.Api.V1\xca\x02\rExonex\\Api\\V1\xe2\x02\x19Exonex\\Api\\V1\\GPBMetadata\xea\x02\x0fExonex::Api::V1b\x06proto3"

var (
	file_exonex_api_v1_meta_proto_rawDescOnce sync.Once
	file_exonex_api_v1_meta_proto_rawDescData []byte
)

func file_exonex_api_v1_meta_proto_rawDescGZIP() []byte {
	file_exonex_api_v1_meta_proto_rawDescOnce.Do(func() {
		file_exonex_api_v1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exonex_api_v1_meta_proto_rawDesc), len(file_exonex_api_v1_meta_proto_rawDesc)))
	})
	return file_exonex_api_v1_meta_proto_rawDescData
}

var file_exonex_api_v1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exonex_api_v1_meta_proto_goTypes = []any{
	(*ResourceMeta)(nil),          // 0: exonex.api.v1.ResourceMeta
	(*structpb.Struct)(nil),       // 1: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_exonex_api_v1_meta_proto_depIdxs = []int32{
	1, // 0: exonex.api.v1.ResourceMeta.annotations:type_name -> google.protobuf.Struct
	2, // 1: exonex.api.v1.ResourceMeta.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: exonex.api.v1.ResourceMeta.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: exonex.api.v1.ResourceMeta.deleted_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_exonex_api_v1_meta_proto_init() }
func file_exonex_api_v1_meta_proto_init() {
	if File_exonex_api_v1_meta_proto != nil {
		return
	}
	file_exonex_api_v1_meta_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exonex_api_v1_meta_proto_rawDesc), len(file_exonex_api_v1_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exonex_api_v1_meta_proto_goTypes,
		DependencyIndexes: file_exonex_api_v1_meta_proto_depIdxs,
		MessageInfos:      file_exonex_api_v1_meta_proto_msgTypes,
	}.Build()
	File_exonex_api_v1_meta_proto = out.File
	file_exonex_api_v1_meta_proto_goTypes = nil
	file_exonex_api_v1_meta_proto_depIdxs = nil
}
